rero/rero-ils-ui

projects/admin/src/app/app-routing.module.ts
projects/admin/src/app/record/aggregation-filter.spec.ts
projects/admin/src/app/record/aggregation-filter.ts

document: adds aggregations filters

---

projects/admin/src/app/record/brief-view/circ-policies-brief-view.component.ts
projects/admin/src/app/record/brief-view/documents-brief-view.component.ts
projects/admin/src/app/record/brief-view/item-types-brief-view.component.ts
projects/admin/src/app/record/brief-view/libraries-brief-view.component.ts
projects/admin/src/app/record/brief-view/patron-types-brief-view.component.ts
projects/admin/src/app/record/brief-view/patrons-brief-view.component.ts
projects/admin/src/app/record/brief-view/persons-brief-view.component.ts

admin: Fixes new detail url parameter on brief view

---

.github/PULL_REQUEST_TEMPLATE.md

* Updates PR template for translation process.
To update PR template for translation process.
N/A

template: update PR template

---

package-lock.json
projects/admin/src/app/app.module.ts
projects/admin/src/app/record/detail-view/item-type-detail-view.component.ts
projects/admin/src/app/service/record-routing.service.ts

- Task 1162: item type: implement detail view 
- Show item type detail view
- Confirm message on delete

item types: implement detail view

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/record/detail-view/patron-types-detail-view.component.ts
projects/admin/src/app/service/record-routing.service.ts

- Task 1163: patron type: implement detail view
- Show patron type detail view
- Confirm message on delete

patron types: implement detail view

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/record/brief-view/libraries-brief-view.component.ts
projects/admin/src/app/record/detail-view/library-detail-view/day-opening-hours/day-opening-hours.component.html
projects/admin/src/app/record/detail-view/library-detail-view/day-opening-hours/day-opening-hours.component.ts
projects/admin/src/app/record/detail-view/library-detail-view/exception-date/exception-date.component.html
projects/admin/src/app/record/detail-view/library-detail-view/exception-date/exception-date.component.ts
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.ts
projects/admin/src/app/service/record-routing.service.ts
projects/admin/src/app/translate/i18n/de.json
projects/admin/src/app/translate/i18n/en.json
projects/admin/src/app/translate/i18n/en_US.json
projects/admin/src/app/translate/i18n/fr.json
projects/admin/src/app/translate/i18n/it.json

- Task 1159: library: implement detail view
- Show library detail view
- Confirm message on delete

libraries: implement detail view

---

projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy-form.service.ts

- Fix bug on patron_type and item_type $ref generation
- Add a new circulation policy and save
- reopen to display the correct result

circulation policies: fix bug on settings

---

projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/translate/i18n/de.json
projects/admin/src/app/translate/i18n/en.json
projects/admin/src/app/translate/i18n/en_US.json
projects/admin/src/app/translate/i18n/fr.json
projects/admin/src/app/translate/i18n/it.json

* Updates start time translation in order to remove redundant content.
* Closes #33.
To close issue #33.
Check the start time error messages in the library editor.

translation: fix start time translation

---

README.md

- This is a part of US987 (public final admin)
- It adds more documentation in README.md file
Just read the README.md file on Github

README: complete it for project installation

---

projects/admin/src/app/class/user.ts
projects/admin/src/app/service/record-routing.service.ts
projects/admin/src/app/service/user.service.ts

- Fix for ressource access control
- Check access to ressource (new, update, delete) with different user (librarian and system librarian)

routing: add access control

---

projects/admin/src/app/record/custom-editor/libraries/exception-dates-edit/exception-dates-edit.component.html
projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html

- Add a star on required fields
- Go to libraries and add
- Check if the start is present on required field (library and exceptions sections)

libraries: add a star on required field

---

package-lock.json
package.json
projects/admin/src/app/service/record-routing.service.ts
projects/public-search/src/app/app-routing.module.ts

* Adds new parameters for aggregations to routing configuration for public-search and admin.
- Adds configuration pour aggregations
- Check aggregations on documents

general: upgrade ng-core to 0.0.17

---

projects/admin/src/app/record/brief-view/libraries-brief-view/location/location.component.ts
projects/admin/src/app/record/custom-editor/circulation-settings/circulation-mapping.service.ts
projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy-form.service.ts
projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy.service.ts
projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.ts
projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.html

* Corrects patron type id assignation.
* Corrects entry points.
* Corrects redirection after saving the ci-po.
* Corrects file indentation.
* Compacts ci-po detail view.
* Corrects location delete query (fix).
To fix ci-po editor.
To fix delete location query.
Part of https://github.com/rero/rero-ils-ui/issues/43.
Go to ci-po editor and create or edit a ci-po.

ci-po: fix editor

---

projects/admin/src/app/service/record-routing.service.ts

- Fixes source facet is open by default.
- Check if facet sources is open to person brief view

persons: fix sources facet

---

projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts

- Fixes start time and end time bug with value 00:00.
- Check library opening hours validation

library: reject hours with value 00:00

---

projects/public-search/src/app/app-routing.module.ts

* Expands source facet in persons view.
Part of https://github.com/rero/rero-ils-ui/issues/43.
In public search, go to persons tab and see the expanded facet.

public-search: expand persons facet

---

projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html

* Corrects code display when there is no address.
* Hide exception hours bloc if empty.
To correct libraries detail view.
Part of https://github.com/rero/rero-ils-ui/issues/43
Create a library without address and exception hours and check code is correctly displayed and exception hours bloc is hidden.

libraries: correct code display

---

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.ts

* Removes items from documents brief view.
To remove items from documents detail view as discussed with PO.
N/A

documents: simplify brief view

---

projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy.service.ts
projects/admin/src/app/record/custom-editor/libraries/library.component.ts

* Fixes back history for custom editor.
Part of https://github.com/rero/rero-ils-ui/issues/43
N/A

custom-editor: fix back history

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts
projects/public-search/src/app/translate/i18n/fr.json

* Improves display of holdings.
* Fixes unsubscribe.
Co-Authored-by: Alicia Zangger <alicia.zangger@rero.ch
Co-Authored-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>>
Improves display of holding by adding headers.
Cleans html code.
Go to document detail view and check holdings display.
Check with ebook too.

document: improve holding display

---

projects/admin/src/app/scss/styles.scss
projects/admin/src/app/scss/variables.scss

edit: fix editor validation colors

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts
projects/admin/src/app/record/editor/remote-select/remote-select.component.html
projects/admin/src/app/record/editor/remote-select/remote-select.component.ts
projects/admin/src/app/service/no-cache-header.service.ts
projects/public-search/src/app/app-routing.module.ts

* Fixes location name in the item detailed view.
* Fixes http request cache for firefox.
* Fixes select filtered by organisation and library such as item,
item_types.

misc: fixes issue for the workshops

---

README.md

* Updates documentation to add Transifex and GitHub translation workflow.
Task 1195 (storyless task)
Check translation section:
https://github.com/AoNoOokami/rero-ils-ui/tree/zaa-%231195-translation-documentation

documentation: update translation section

---

package-lock.json
package.json
projects/admin/src/app/service/record-routing.service.ts

* Adds new routing type for items to redirect after save.
* Closes rero/rero-ils/#376
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
Implements task 1116 of US985
https://tree.taiga.io/project/rero21-reroils/task/1116?kanban-status=1224895
Checkout https://github.com/rero/ng-core/pull/100
`npm pack` or `npm link`
Create or edit an item. Saving it should redirect to corresponding document detail view.
Check that redirection is not broken for other type of resource.

routing: redirect after saving a resource

---

package-lock.json
package.json
projects/admin/src/app/service/record-routing.service.ts

* Adds a preprocess step to remove dynamic fields when the editor load
record for edition. Theses fields comes from the dumps step and are not
in the JSONSchema.

editor: fix item and document update

---

.github/workflows/npmpublish-on-release.yml
scripts/release.sh

* Adds workflow config file.
* Adds script to automate release process.
To automate release and NPM publication.
The yml file must be on master to be considered for the workflow and should be triggered on push with tag = v.0.0.*

git: automate release process

---

projects/admin/src/app/record/detail-view/vendor-detail-view/vendor-detail-view.component.html

* Fixes html dl tag in vendor detail view.
Co-Authored-by: Laurent Dubois <laurent.dubois@itld-solutions.be>

Acquisition: fix html dl tag

---

projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/service/patron.service.ts

* Sorts items by transaction date.
* Fixes checkin issue due to merge.
* Removes "is loading" after action for better user experience.
Implements https://tree.taiga.io/project/rero21-reroils/task/1267?kanban-status=1224894
for US 813
Needs https://github.com/rero/rero-ils/pull/710
1. Checkout https://github.com/rero/rero-ils/pull/710, or US813 if already merged
2. Go to on loan tab of circulation ui for a patron.
3. Do a checkin by entering the barcode of an existing item in the input.
4. Checkout the same item by entering the barcode in the input.
5. It should be added at the top of the list (instead of the bottom).

circulation: sort items by transaction date

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts

- use the new structure of provisionActivity
- use https://github.com/rero/rero-ils/pull/705
- check field provisionActivity on document

document: refactoring provision activity field for new structure

---

projects/admin/src/app/record/detail-view/person-detail-view/person-detail-view.component.html
projects/admin/src/app/record/detail-view/person-detail-view/person-detail-view.component.ts

- #108 documents in person detail view
- Check Documents section at bottom of person detail view

person: implement documents on detail view

---

projects/admin/src/app/circulation/patron/card/card.component.html

* Adds link to patron profile on patron name.
* Removes link to itself on barcode.
Point described in the mockups but not implemented in US813 branch.
Part of https://github.com/rero/rero-ils-ui/issues/108
Go to User services, patrons, circulation view for a patron.
Click on the name. It should redirect to patron profile.

circulation: add link to patron profile

---

projects/admin/src/app/routes/items-route.ts

* close #697
- to filter locations.
- use this PR https://github.com/rero/rero-ils/pull/727
- Check menu locations on item editor.

item: filter locations with current library of user connected

---

package-lock.json
projects/admin/src/app/record/detail-view/acquisition-order-detail-view/order-lines/acquisition-order-lines.component.html
projects/admin/src/app/record/detail-view/acquisition-order-line-detail-view/acquisition-order-line-detail-view.component.html
projects/admin/src/app/routes/acquisition-order-lines-route.ts

* Implements link between order line and document.
* Fixes div alignment for order lines table in order detail view.
* Adds filter by user current library on acquisition account field in editor.
Co-Authored-by: Laurent Dubois <laurent.dubois@itld-solutions.be>
https://tree.taiga.io/project/rero21-reroils/task/1276?kanban-status=1224894
- Use https://github.com/rero/rero-ils/pull/719
- Create new order line on acquisition order.

acquisition: link order line to a document

---

projects/admin/src/app/app.component.html
projects/admin/src/app/app.component.scss
projects/admin/src/app/app.component.ts
projects/admin/src/app/menu/menu.component.html
projects/admin/src/app/menu/menu.component.scss

- https://github.com/rero/rero-ils-ui/issues/108 point: 22
- Check the logo in the header

header: replace text RERO ILS with the logo

---

projects/public-search/src/app/service/routing-init.service.ts

- https://github.com/rero/rero-ils-ui/issues/108 point 1
- Check count on tab person and page.

person tab: fix count

---

projects/admin/src/app/menu/menu.component.ts

- To add a new class on sub menu
- use https://github.com/rero/ng-core/pull/130
- Test the menu user (align right)

menu: add new option to add class on submenu

---

projects/admin/src/app/record/brief-view/libraries-brief-view/libraries-brief-view.component.ts
projects/admin/src/app/routes/items-route.ts

- To sort alphabetically.
- Check resource list.

resources: add sort option for libraries and locations

---

package.json

general: use version 0.0.30 of ng-core

---

projects/admin/src/app/menu/menu.component.ts
projects/admin/src/app/service/library-switch.service.ts

* Close #141
- to fix the display of menu on homepage
- http://localhost:4200/records/documents?q=&page=1&size=10
- click on logo to return to the homepage
- check if the menu is displayed

switch library: fix the display of the switch menu on the homepage

---

projects/admin/src/app/circulation/patron/loan/loan.component.ts

* Fixes '403 error' managing (checkout not allowed by ci-po).
* Fixes input clearing and focus.
To fix some wrong behaviours detected while testing on loan tab of circulation ui.
Do some checkin and checkout and verify that the input is cleared and has the focus.
Try with an item that is not allowed by ci-po (for example, Philippe Monnet who is a child cannot read books that are for 16+ year old (item_types=3))

circulation: fix on loan tab behaviour

---

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.ts
projects/public-search/src/app/document-brief/document-brief.component.html
projects/public-search/src/app/document-brief/document-brief.component.ts

* Adds provision activity publication on brief view.
* Removes unused code.
* Optimizes html code.
- To add provision activity publication on briefview
- Check document brief view (select language Arabic)

document: add provision activity publication on brief view

---

projects/admin/src/app/frontpage/frontpage.component.ts

- Check "My library" on board with switch library menu.

homepage: fix my library switch on board

---

projects/public-search/src/app/service/routing-init.service.ts

document: revert list headers to application/rero+json

---

projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts

* Fixes actions available on item.
* close rero/rero-ils#772
- To resolve bug on item actions available.
- Adds items on same document. With system librarian use different libraries.

item: fix item available actions on document detail view

---

package-lock.json
package.json

* Releases v0.0.11 and publishes it on NPM.

release: v0.0.11

---

.github/workflows/npmpublish-on-release.yml

* Fixes github 'npm publish on release' workflow.
To fix github action
N/A

git: fix github action

---

package-lock.json
package.json

* Releases v0.0.12 and publishes it on NPM.

release: v0.0.12

---

package.json

* Adds contributors to package.json file.
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
To add all contributors from rero-ils-ui in the package.json file.
Just check the package.json file. All people that contribute to rero-ils-ui project should be present.

project: update contributors list

---

projects/admin/src/app/circulation/checkout/checkout.component.html
projects/admin/src/app/circulation/checkout/checkout.component.spec.ts
projects/admin/src/app/circulation/checkout/checkout.component.ts
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/items-list/items-list.component.html
projects/admin/src/app/circulation/items.service.ts
projects/admin/src/app/circulation/items.ts
projects/admin/src/app/circulation/patron/loan/loan.component.spec.ts
projects/admin/src/app/circulation/patron/loan/loan.component.ts

* Fixes the display of patron info (only after a checkin).
* Fixes alignment between checked-in and checked-out items.
* Fixes space after pickup location name.
* Fixes flash messages for checkin.
* Removes unused code.
* Closes rero/rero-ils#793.
* Closes rero/rero-ils#827.
* Closes rero/rero-ils#830.
* closes rero/rero-ils#829.
To close issues mentioned above.
Needs https://github.com/rero/rero-ils/pull/824
* As a (system) librarian of a library A, make a checkout of an item to a patron (for example Giulia)
* As an other patron (Simonetta), make a request on this item with a pickup location different from library A.
* As (system) librarian, make a checkin of the item in the checkin form (User services > Circulation)
Expected …

circulation: fix display of patron in checkin view

---

projects/admin/src/app/guard/acq-order-line.guard.ts
projects/admin/src/app/guard/can-update.guard.ts
projects/admin/src/app/guard/library.guard.ts
projects/admin/src/app/guard/role.guard.ts
projects/admin/src/app/routes/acquisition-order-lines-route.ts
projects/admin/src/app/routes/budgets-route.ts
projects/admin/src/app/routes/circulation-policies-route.ts
projects/admin/src/app/routes/item-types-route.ts
projects/admin/src/app/routes/libraries-route.ts
projects/admin/src/app/routes/locations-route.ts
projects/admin/src/app/routes/patron-types-route.ts
projects/admin/src/app/routes/patrons-route.ts
projects/admin/src/app/routes/route-tool.service.ts

Create some guard to protect access to some 'new' form URL :
* Generic guard based on user role
* LibraryGuard : Check if the current logged user and it current library can manage the resource.
* Closes https://github.com/rero/rero-ils/issues/787

Add authorization management

---

projects/admin/src/app/app.component.ts
projects/admin/src/app/class/user.ts
projects/admin/src/app/guard/acq-order-line.guard.ts
projects/admin/src/app/guard/library.guard.ts
projects/admin/src/app/guard/role.guard.ts
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.ts

Before this PR, the 'add location' button was always displayed on each library page.
The purpose of this PR is to check if the current logged user has suffisant privileges to add a location to
the library.
This PR upgrades / improves / cleans some code lines linked to authorization access.

security: limit access to 'add location' button

---

projects/admin/src/app/circulation/checkin/checkin.component.html
projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/main-request/main-request.component.html
projects/admin/src/app/circulation/patron/loan/loan.component.html
projects/admin/src/app/circulation/patron/loan/loan.component.ts

* Removes previous fix that is useless now.
* Removes weird character in the licence text of templates.
https://tree.taiga.io/project/rero21-reroils/task/1386?kanban-status=1224894
Related to https://github.com/rero/ng-core/pull/158.
See issue description: #213.

search: remove useless code

---

projects/admin/src/app/circulation/patron/main/main.component.spec.ts
projects/admin/src/app/menu/menu.component.spec.ts
projects/admin/src/app/menu/menu.component.ts
projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.spec.ts
projects/admin/tests/utils.ts

* Fixes random errors due to the circulation main component.
* Enables tests for the menu component.
* Creates a new utils file for default mock services such as
RecordService.
* Changes order of operations in the menu component to pass the tests.
- To fix random travis tests failures.
- Run `ng test` several times. No error should happens.
- Open the debug console in the test browser no errors should be there.

tests: fix random failures

---

package-lock.json
package.json

* Releases v0.1.0 and publishes it on NPM.
* Moves to @rero/ng-core v0.1.0.

release: v0.1.0

---

projects/admin/src/app/circulation/circulation.module.ts

* Fixes a missing comma in circulation module.

Circulation : fix typo in circulation module

---

projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
projects/admin/src/app/service/loan.service.ts

* Adds 'Add' button at the top of request list to access 'add request
form'.
* Implements request deletion.
* Implements request pickup location edition.
Needs https://github.com/rero/rero-ils/pull/935
1. Got to the detailed view of an item.
2. Create a request for a patron.
3. Try to change the pickup location.
4. Cancel the request.
5. You can work with an existing request too.

request: implement request list edition in item detail view

---

package-lock.json
projects/admin/src/app/menu/menu.component.ts
projects/admin/src/app/pipe/bio-informations.pipe.ts
projects/admin/src/app/pipe/birth-date.pipe.ts
projects/admin/src/app/pipe/mef-title.pipe.ts
projects/admin/src/app/record/editor/remote-autocomplete/remote-autocomplete.component.ts
projects/public-search/src/app/person-brief/person-brief.component.html
projects/public-search/src/app/pipes/bio-informations.pipe.ts
projects/public-search/src/app/pipes/birth-date.pipe.ts
projects/public-search/src/app/pipes/mef-title.pipe.ts
projects/public-search/src/app/search-bar/search-bar.component.ts
projects/public-search/src/app/translate/loader/translate-loader.ts

- https://tree.taiga.io/project/rero21-reroils/task/1344
Use https://github.com/rero/rero-ils/pull/845 and http://mefdev.test.rero.ch
- `IDREF` in brief view of persons

display idref persons

---

.github/PULL_REQUEST_TEMPLATE.md

To add a dependencies section in the PR template, in which one can list corresponding PR in other projects. See also https://github.com/rero/rero-ils/pull/963.
Check the updates file.

documentation: add dependencies in PR template

---

package-lock.json
package.json

* Releases v0.1.2 and publishes it on NPM.

release: v0.1.2

---

projects/admin/src/app/record/custom-editor/libraries/exception-dates-edit/exception-dates-edit.component.html
projects/admin/src/app/record/custom-editor/libraries/exception-dates-list/exception-dates-list.component.html
projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts
projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/record/custom-editor/libraries/library.component.ts

* Adapts the library custom editor according the UX charts.
* When a day is defined closed, then the opening hours are now hide
in addition to be readonly/disabled
* Closes rero/rero-ils#675

libraries: adapt library custom editor

---

package-lock.json
package.json
projects/admin/src/app/record/detail-view/acquisition-order-detail-view/order-lines/acquisition-order-lines.component.html

release: v0.2.0

---

package-lock.json
package.json

* Releases v0.2.1 and publishes it on NPM.

release: v0.2.1

---

projects/admin/src/app/routes/acquisition-accounts-route.ts
projects/admin/src/app/routes/acquisition-order-lines-route.ts
projects/admin/src/app/routes/base-route.ts
projects/admin/src/app/routes/holdings-route.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/routes/locations-route.ts

* Allow transformation with parent reference ($ref) or parent identifier (PID).
- To fix te redirection after delete record on detail view
My PR depends on `https://github.com/rero/ng-core/pull/191`'s PR(s):
- Create a new item on document
- show new item on detail view
- click on delete button
- Redirection on document

routing: change redirectUrl function on route config

---

projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts

* Fixes loading of pickup locations menu in the case of the requested transaction.

item: Improve transactions on detailed view

---

package-lock.json
package.json

package: upgrade ng-core to version 0.5.0

---

package-lock.json
package.json

For `v0.3.0` release publication.
Check the changed files.

release: v0.3.0

---

projects/admin/src/app/circulation/patron/history/history-item/history-item.component.ts
projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.ts
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.ts
projects/admin/src/app/circulation/patron/requested/requested-item/requested-item.component.ts

* Replaces loan.pid by loan.item_pid.value to correspond to its new type
(object instead of string).
To adapt UI to new circulation backend (task 1412, US 1394)
https://tree.taiga.io/project/rero21-reroils/task/1412?kanban-status=1224895
https://github.com/rero/rero-ils/tree/US1394-invenio-circulation
Do code review only, please.

circulation: adapt loan object

---

projects/admin/src/app/circulation/patron/history/history-item/history-item.component.ts
projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.ts
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.ts
projects/admin/src/app/circulation/patron/requested/requested-item/requested-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts
projects/admin/src/app/service/loan.service.ts

* Adapts 'add request' in document and item detailed views.
To adapt 'add request' action
US: https://tree.taiga.io/project/rero21-reroils/us/1394?milestone=268117
US1394-invenio-circulation branch
https://github.com/rero/rero-ils/tree/US1394-invenio-circulation
If needed: create an item to be requested.
* Go to a (or the newly created) document detailed view and make a request for a patron.
* Check that the request is displayed in the item detailed view.
* Check that the queue list is updated accordingly in the 'add request' modal form.
You need to install rero-ils-ui (this PR) into rero-ils (US1394 branch): https://github.com/rero/developer-resources/blob/master/rero-instances/rero-ils-ui/ui-integration.md
* Go to …

circulation: adapt 'add request'

---

projects/admin/src/app/circulation/patron/history/history-item/history-item.component.ts
projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.ts
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.ts
projects/admin/src/app/circulation/patron/requested/requested-item/requested-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts
projects/admin/src/app/service/loan.service.ts

* Adapts 'cancel request' in item detailed view.
To adapt 'cancel request'
US 1394: https://tree.taiga.io/project/rero21-reroils/us/1394?milestone=268117
US1394-invenio-circulation branch
https://github.com/rero/rero-ils/tree/US1394-invenio-circulation
As a (system) librarian, go to an item detailed view with requests and cancel it.

circulation: adapt 'cancel request'

---

projects/admin/src/app/circulation/item/item.component.html

Updates the badge used to notify that an item is requested by another
patron : change exclamation icon to shopping-bag icon and display the
patron name.
* Closes rero/rero-ils#883

ui: better request badge into circulation module

---

package-lock.json
package.json

This commit add ngx-spinner dependency used in ng-core
to rero-ils-ui project.
Since ngx-spinner is integrated into ng-core dev, that raise `Module not found: Error: Can't resolve 'ngx-spinner’` on rero-ils-ui compilation

project: add ngx-spinner dependency

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/directives/tab-order.directive.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html

* Adds a custom directive allowing to order tabs
* Closes rero/rero-ils#1078
- Go to a document detail view for a documents with multiple tabs.
- Check tab order (should follow this order : get, marc, online, description)

ui: add directive to sort tabs

---

package-lock.json
package.json

package: upgrade ng-core to version 0.6.0

---

projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts
projects/admin/src/app/service/items.service.ts
projects/admin/src/app/service/loan.service.ts

* Adapts methods to validate a request and update request pickup location according to backend.
It corresponds to task 1618 of US1394.
https://tree.taiga.io/project/rero21-reroils/task/1618?kanban-status=1224894
https://tree.taiga.io/project/rero21-reroils/us/1394?milestone=268117
My PR depends on :
* rero/rero-ils US1394 branch
Login as a (sytem) librarian.
Go to an item detail view that has a request. If the request has not been validated, you should be able to change the pickup location.
Go to 'User services' > 'Requests' and validate a request. You should not be able to change the pickup location anymore if the item is at desk.

circulation: adapt 'validate request' and 'update loan pickup location'

---

README.md

- To add badges to the readme. 
- Check the readme of my repo branch

documentation: add badges to the README

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/frontpage/frontpage.component.html
projects/admin/src/app/frontpage/frontpage.component.ts
projects/admin/src/app/menu/menu.component.ts
projects/admin/src/app/record/brief-view/items-brief-view/items-brief-view.component.html
projects/admin/src/app/record/brief-view/items-brief-view/items-brief-view.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/service/items.service.ts
projects/admin/src/app/service/menu.service.ts

Us1491 item inventory list

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html

* Adds id html attribute in order to select DOM elements more easily for Cypress
tests.
To adapt the document detailed view for the tests with Cypress.
No dependency.
Code review only needed.
Used for: https://github.com/rero/rero-ils/pull/1116.

document: adapt detailed view for cypress tests

---

projects/admin/src/app/service/items.service.ts

New RERO circulation backend adds more parameter for actions.
For validate request action, `transaction_user_pid` is missing.
* Adds transaction_user_pid to data for a request validation.
New RERO circulation backend adds more parameter for actions.
For validate request action, `transaction_user_pid` is missing.
That's fixed with this PR.
My PR depends on :
Rero-ils US1394 branch
Login as a librarian and go to requests view (user services).
Validate a request.

circulation: adapt validate request

---

projects/admin/src/app/circulation/items-list/items-list.component.html

* Corrects header and content alignment in checkin/checkout view (with
patron info).
Header and content are not aligned in checkin/checkout view with patron info.
N/A
Login as a (system) librarian.
Go to User services > Patrons > Circulation and check the view

circulation: correct header alignment in checkin/checkout view

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/service/items.service.ts

Merge `US-fix-circulation-problems` to `zaa-US1394-adapt-circulation-ui`

Us fix circulation problems

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/items-list/items-list.component.html
projects/admin/src/app/circulation/patron/history/history-item/history-item.component.ts
projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.ts
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.ts
projects/admin/src/app/circulation/patron/requested/requested-item/requested-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts
projects/admin/src/app/service/items.service.ts
projects/admin/src/app/service/loan.service.ts

Merge the update of invenio-circulation and major refactoring of RERO ILS circulation module (US 1394)

Merge the update of invenio-circulation and major refactoring of RERO ILS circulation module (US 1394)

---

projects/admin/src/app/service/items.service.ts
projects/admin/src/app/service/loan.service.ts

* Fixes the display of the due date for a checkout with automatic
receive (checkout 4.1, scenario E, problem nb 10).
* Corrects docstring.
To fix problem nb 10:
Scenario E: after CHECKOUT_4.1
The loan due date is not displayed in the column “Circulation info”
This PR fixes also the problem nb 12 too.
N/A
Follow the scenario E until the step CHECKIN_3_2_2_1 (User A is impatient as well and tries to request the item again (impossible). User C requests it with pickup library C. Librarian A tries to check it out for user C (-> denied). User B returns the item at library B, the item goes in transit to library A for user A.
https://github.com/rero/rero-ils/blob/8f07db7586f59c43da37ea43384b4b4fb49412 …

circulation: fixes the display of the due date

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/record/brief-view/templates-brief-view.component.ts
projects/admin/src/app/record/detail-view/template-detail-view/template-detail-view.component.html
projects/admin/src/app/record/detail-view/template-detail-view/template-detail-view.component.ts
projects/admin/src/app/routes/templates-route.ts

* Creates brief and detail views for templates resources.
task 1690 of US1642
* https://github.com/rero/rero-ils/pull/1190
Go to templates brief view and some detail view

templates: create brief and detail views

---

projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/patron/card/card.component.html
projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/admin/src/app/record/brief-view/patrons-brief-view.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.html
projects/public-search/src/app/document-brief/document-brief.component.html

* Adapts templates of circulation service to make cypress test writing and maintenance
easier.
To adapt ui for cypress tests
* https://github.com/rero/rero-ils/pull/1181
Code review only. For testing see https://github.com/rero/rero-ils/pull/1181

ui: adapt templates for cypress tests

---

CHANGELOG.md
package-lock.json
package.json

- To make a minor release. 
- Check the changed files.

release: v0.5.1

---

package-lock.json
package.json
projects/admin/src/app/app.module.ts
projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.html
projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.spec.ts
projects/admin/src/app/record/custom-editor/libraries/exception-dates-edit/exception-dates-edit.component.html
projects/admin/src/app/record/custom-editor/libraries/library.component.html

* Removes obsolete package ngx-toogle-switch.
* Changes old toogle switch with the new syntax toogle switch.
* Closes rero/rero-ils#891
- Check toogle switch on screen library, exception dates and circulation policies

form: improve toogle switch

---

package-lock.json
package.json
projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/patron-transaction.service.spec.ts
projects/admin/src/app/circulation/patron-transaction.service.ts
projects/admin/src/app/guard/item-access.guard.ts
projects/admin/src/app/record/detail-view/budget-detail-view/acquisition-accounts/acquisition-accounts.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
projects/admin/src/app/record/detail-view/organisation-detail-view/budget-select/budget-select.component.ts
projects/admin/src/app/record/detail-view/person-detail-view/person-detail-view.component.ts
projects/admin/src/app/routes/acquisition-order-lines-route.ts
projects/admin/src/app/routes/holdings-route.ts
projects/admin/src/app/routes/import-documents-route.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/service/items.service.ts
projects/admin/src/app/service/library-switch.service.ts
projects/admin/src/app/service/library.service.ts
projects/admin/src/app/service/loan.service.ts
projects/admin/src/app/service/patron.service.ts

* Adds totalhits function from RecordService  on result of Elasticsearch.
- Elasticsearch 7 compatibility
- Check count on brief pages.
- Check application.

application: compatibility with Elasticsearch 7

---

projects/admin/src/app/app.component.ts
projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.spec.ts
projects/admin/src/app/service/app-init.service.ts
projects/admin/src/app/service/library-switch.service.ts
projects/admin/src/app/service/navigate.service.spec.ts
projects/admin/src/app/service/navigate.service.ts

* Adds a new navigate service.
* Improves library switch call.
- Bug on switch menu with app initialize.

app: Improve the library switch with new application initialization

---

projects/admin/src/app/class/user.ts
projects/admin/src/app/service/library-switch.service.ts

* Fixes the user storage key for the current library.

library: Fix storage key on library switch

---

projects/public-search/src/app/routes/collections-route.service.spec.ts
projects/public-search/src/app/routes/collections-route.service.ts
projects/public-search/src/app/routes/documents-route.service.spec.ts
projects/public-search/src/app/routes/documents-route.service.ts
projects/public-search/src/app/routes/resource-route-interface.ts
projects/public-search/src/app/routes/route-collection.service.ts

* Fixes a dynamic route with multiple resources on same definition.

routing: fix dynamic routing

---

.github/PULL_REQUEST_TEMPLATE.md

* Removes translations form the checklist, as they are managed in a specific branch now.
To update PR template according to new translation workflow.
N/A

git: update PR template

---

package-lock.json
package.json
projects/admin/src/app/routes/acquisition-order-lines-route.ts
projects/admin/src/app/routes/acquisition-orders-route.ts
projects/admin/src/app/routes/circulation-policies-route.ts
projects/admin/src/app/routes/collections-route.ts
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/holdings-route.ts
projects/admin/src/app/routes/item-types-route.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/routes/libraries-route.ts
projects/admin/src/app/routes/locations-route.ts
projects/admin/src/app/routes/patron-types-route.ts
projects/admin/src/app/routes/patrons-route.ts
projects/admin/src/app/routes/route-tool.service.ts
projects/admin/src/app/routes/templates-route.ts
projects/admin/src/app/routes/vendors-route.ts
projects/admin/src/app/service/record-permission.service.ts

This optimization reduces the number of calls to the API when requesting permissions.

permissions: optimize API calls

---

projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html
projects/admin/src/app/scss/styles.scss

Adapts the patron type resource detail view to include the display of
limits.
https://github.com/rero/rero-ils/tree/US1643-borrow-limits

patron_types: display restrictions on detailed view

---

CHANGELOG.md
package-lock.json
package.json

* Uses ng-core version 0.13.0.

release: v0.6.1

---

projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.html
projects/admin/src/app/service/items.service.ts

* Corrects a template to fix cypress tests after release 0.13.0.

ui: adapt templates to fix cypress tests

---

projects/admin/src/app/class/items.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
projects/admin/src/app/scss/styles.scss
projects/admin/src/app/service/loan.service.ts

On the item detailed view, you can display requests made by user about
this item. The request list should be sorted by creation date but
wasn't. This commit corrects this problem.
Closes rero/rero-ils#1314
https://github.com/rero/rero-ils/pull/1344

request: preserver request order.

---

projects/admin/src/app/circulation/checkin/checkin.component.html
projects/admin/src/app/circulation/patron/card/card.component.html
projects/admin/src/app/circulation/patron/card/card.component.ts
projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/circulation/patron/main/main.component.html
projects/admin/src/app/circulation/patron/main/main.component.ts
projects/admin/src/app/class/user.ts
projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html
projects/admin/src/app/record/detail-view/template-detail-view/template-detail-view.component.html
projects/admin/src/app/scss/styles.scss
projects/admin/src/app/service/patron.service.ts
projects/admin/src/app/service/user.service.ts
projects/admin/src/app/utils/utils.ts

merging `us1643-borrow-limits` to `v0.14`

Us1643 borrow limits

---

projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/item/item.component.scss
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/items-list/items-list.component.html
projects/admin/src/app/circulation/items-list/items-list.component.ts
projects/admin/src/app/circulation/patron/loan/loan.component.html
projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/service/patron.service.ts

This commits adds a sorting widget on some patron circulation tabs
(CI/CO, Pickup, Request). This widget allows to staff member to sort the
listed loans on some keys.
This commit also refactors the loan item display in patron profile for a
better display.

circulation: add loans sorting possibility.

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts

* Displays qualifier, status and note for identifiers.
To fix rero/rero-ils#1403
* https://github.com/rero/rero-ils/pull/1416

document: fix identifier display in detail view

---

projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.html
projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.ts
projects/admin/src/app/circulation/patron/pending/pending.component.html
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.html
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.ts

Adds the contributions statement for loaned, requested and pending items
in the circulation module.
Closes rero/rero-ils#1355

circulation: display authors for item in circulation.

---

package-lock.json
package.json
projects/admin/src/app/app.component.ts
projects/admin/src/app/app.module.ts
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/patron/main/main.component.ts
projects/admin/src/app/service/keyboard-shortcuts.service.spec.ts
projects/admin/src/app/service/keyboard-shortcuts.service.ts
projects/admin/src/app/widgets/custom-shortcut-help/custom-shortcut-help.component.html
projects/admin/src/app/widgets/custom-shortcut-help/custom-shortcut-help.component.scss
projects/admin/src/app/widgets/custom-shortcut-help/custom-shortcut-help.component.ts

Adds keyboard shortcuts to the professional interface. When the focus
is not set into an input element, if user press on some keyboard key
(or keys combination) an action is done (redirection, set focus, ...).
`npm ci`

ui: implement basic keyboard shortcuts

---

package-lock.json
package.json
projects/admin/src/app/app.module.ts

* Fixes errors for production build due to the @ngneat/hotkeys library.

release: v0.7.1

---

projects/admin/src/app/record/custom-editor/holding-editor/holding-editor.component.ts

For each invalid syntax in the prediction template, the preview
generation is interrupted. It fixes this by intercepting the error.
* Closes rero/rero-ils#1450.
- To fix:  rero/rero-ils#1450.
- Go to the holding serial editor and try to remove two `}` retype the `}}` the preview should continue to be generated.

holdings: fix prediction preview

---

projects/admin/src/app/api/local-field-api.service.spec.ts
projects/admin/src/app/api/local-field-api.service.ts
projects/admin/src/app/app.module.ts
projects/admin/src/app/error/error-page/error-page.component.ts
projects/admin/src/app/guard/can-add-local-fields.guard.spec.ts
projects/admin/src/app/guard/can-add-local-fields.guard.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding-detail/holding-detail.component.html
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
projects/admin/src/app/record/detail-view/local-field/local-field.component.html
projects/admin/src/app/record/detail-view/local-field/local-field.component.ts
projects/admin/src/app/routes/local-fields-route.ts
projects/admin/src/app/routes/route.service.ts
projects/admin/src/app/service/app-init.service.spec.ts
projects/admin/src/manual_translations.ts
projects/shared/src/lib/pipe/join.pipe.spec.ts
projects/shared/src/lib/pipe/join.pipe.ts
projects/shared/src/lib/shared.module.ts
projects/shared/src/public-api.ts

* Adds local fields on document, item and holdings (serial type).
* Adds holdings informations on the detail screen.
* https://github.com/rero/rero-ils/pull/1410
* https://github.com/rero/ng-core/pull/313

data: implement local fields

---

.gitignore
projects/admin/src/app/menu/menu-switch-library/menu-switch-library.component.spec.ts
projects/admin/src/app/menu/menu.component.spec.ts
projects/shared/src/lib/service/user.service.ts

* Strengthens professional interface access control with multiple
validations on the logged in user:
* Checks its role.
* Checks if the user is attached at least to one library.
* Checks if the user is attached to an invenio-user.
* Fixes init function on librarySwitchMenuService mock.
* Adds build folder on gitignore.

permissions: improve access control

---

projects/admin/src/app/menu/menu-switch-library/service/library-switch.service.spec.ts

test: fix user mock on library switch service

---

projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts

* closes #1399
- Check order on document view.

documents: group holdings by libraries

---

projects/admin/src/app/menu/service/menu-user-services.service.ts

Adds an entry into the services menu for the ILL request managements.

menus: add ILL request management into menu.

---

projects/admin/src/app/menu/menu-switch-library/menu-switch-library.component.ts

* Fixes library switch to prevent the redirection to occur before user confirmation.

library switch: fix redirection issue

---

CHANGELOG.md
package-lock.json
package.json

release: v0.9.0

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html

* Puts back some id html attribute that were removed. There are needed
to keep Cypress tests working.

tests: fix templates for cypress tests

---

projects/admin/src/app/routes/import-documents-route.ts

* closes #1571
* Adds organisation and language facets.
My PR depends on the following `rero-ils`'s PR:
* rero/rero-ils#1572

search: fix author facet of BnF import search view

---

CHANGELOG.md
package-lock.json
package.json

release: v0.10.0

---

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/shared/src/lib/view/thumbnail/thumbnail.component.html
projects/shared/src/lib/view/thumbnail/thumbnail.component.ts

* Improves elements alignment in brief and detailed views.

document: improve document views responsiveness

---

projects/public-search/src/app/search-bar/search-bar.component.ts
projects/public-search/src/index.html

* Presents the suggestions, as the query is typed, according to the
locale of the the user.
* Closes rero/rero-ils#1509.

search: adapt the suggestions to the locale

---

CHANGELOG.md
package-lock.json
package.json

release: v0.11.0

---

CHANGELOG.md
package-lock.json
package.json

release: v0.12.0

---

projects/admin/src/app/circulation/item/item.component.html

circulation: remove extra LoanID information

---

projects/public-search/src/app/api/item-api.service.spec.ts
projects/public-search/src/app/api/item-api.service.ts
projects/public-search/src/app/document-detail/holdings/holding/holding.component.html
projects/public-search/src/app/document-detail/holdings/items/items.component.html
projects/public-search/src/app/document-detail/holdings/items/items.component.spec.ts
projects/public-search/src/app/document-detail/holdings/items/items.component.ts

public-search: hide not received issues for public

---

projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.html
projects/public-search/src/app/document-detail/request/request.component.html

* Adds id html attributes to fix cypress tests.

tests: fix cypress tests

---

CHANGELOG.md
package-lock.json
package.json

release: v0.12.1

---

projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.style.scss

* Uses a darker gray to display the expected issues to improve the
readability.
* Closes rero/rero-ils#1717

issue: best visualization of expected issue.

---

projects/admin/src/app/api/loan-api.service.spec.ts
projects/admin/src/app/api/loan-api.service.ts
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/patron/main/main.component.html
projects/admin/src/app/circulation/patron/main/main.component.ts
projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html
projects/admin/src/app/circulation/services/patron-transaction.service.ts
projects/admin/src/app/service/patron.service.ts

* The patron fees total amount in now returned by the circulation
informations API. Updates code to reflect this change.
* Creates services to communicate with the backend Loan API to get the
preview overdue linked to a loan.

circulation: fix several problems

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html

Fixes document detail view to use all viewport available.

document: fix document detail view

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/classes/items.ts
projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.ts
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts
projects/admin/src/app/routes/issues-route.ts
projects/admin/src/app/service/holdings.service.ts
projects/admin/src/app/service/items.service.ts
projects/public-search/src/app/api/item-api.service.ts
projects/shared/src/lib/class/item-status.ts
projects/shared/src/public-api.ts

Moves ItemStatus and IssueItemStatus class to shared project and correct
import statements into projects.

general: fix import problems.

---

projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.html
projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.ts
projects/admin/src/app/routes/circulation-policies-route.ts
proxy.conf.json

* Fixes some display problems about circulation policies detail view.
* Closes rero/rero-ils#1389

admin: fix circulation policies detail view.

---

projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html

Request: always allow to add a request

---

package-lock.json
package.json
projects/admin/src/app/record/custom-editor/libraries/library.component.ts
projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts
projects/admin/src/app/record/detail-view/organisation-detail-view/budget-select-line/budget-select-line.component.ts

* Fixes the record service update method by adding the pid parameters.
* Updates @rero/ng-core dependency.

dependencies: use @rero/ng-core v1.6.0

---

CHANGELOG.md
package-lock.json
package.json

release: v0.13.1

---

projects/admin/src/app/menu/service/menu-user-services.service.ts
projects/admin/src/app/routes/collections-route.ts
projects/public-search/src/app/routes/collections-route.service.ts

* Closes rero/rero-ils#1672
- Rename "Collection" in "Exhibition/course"
My PR depends on `rero-ils`'s PR(s):
* rero/rero-ils#1815
- Check if all the changes in "Exhibition/race" are effective.

collections: rename into "Exhibition/course"

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-in-collection/holding-item-in-collection.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-note/holding-item-note.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-temporary-item-type/holding-item-temporary-item-type.component.ts

Action buttons related to each item on the document detail page had a
bad positioning. This could sometimes cause problem to click on them.

documents: fix items buttons position

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/pipe/subject-process.pipe.spec.ts
projects/admin/src/app/pipe/subject-process.pipe.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html

* Fixes the display of subjects with the new implementation.
- Fix the display of subjects
- Check subjects on document.

documents: update subject display

---

projects/admin/src/app/pipe/subject-process.pipe.spec.ts
projects/admin/src/app/pipe/subject-process.pipe.ts

documents: fix typo in subject process pipe

---

projects/shared/src/lib/pipe/get-translated-label.pipe.spec.ts
projects/shared/src/lib/pipe/get-translated-label.pipe.ts

pipe: translate value of getTranslatedLabel

---

projects/admin/src/app/circulation/patron/main/main.component.html

- Check tab history on circulation module

circulation: restore the patron history tab

---

projects/public-holdings-items/src/app/app-initializer.service.ts
projects/public-search/src/app/document-detail/request/request.component.ts

* Fixes translation on application initialisation.
* Fixes request on item only for patron.
- Language of the circulation information does not respect the interface language
- Check status on holdings/items

documents: fix translations on holdings/items

---

CHANGELOG.md
package-lock.json
package.json

release: v0.14.0

---

package-lock.json
package.json

release: v0.14.1

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
projects/admin/src/app/service/items.service.ts
projects/admin/src/manual_translations.ts

Closes rero/rero-ils#1820.
Closes rero/rero-ils#1798.
Co-Authored-by: Renaud Michotte <renaud.michotte@gmaiil.com>

translations: correct some static strings

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts

Item: fix last item deletion problem

---

projects/admin/src/app/record/brief-view/patrons-brief-view.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html
projects/admin/src/manual_translations.ts

Closes rero/rero-ils#1846.
Closes rero/rero-ils#1812.
Closes rero/rero-ils#1599.
Closes rero/rero-ils#1821.

documents: display identifiers detail if it exists

---

projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts

* Fixes some problems about the issue display on field `received_date`
and `status_date`.
* Related to issue rero/rero-ils#1654 (but not fix it).
- Should be tested with https://github.com/rero/rero-ils/pull/1894 as backend branch.
- Try to received a regular issue (long mode) with a different status than `received`.
- Check the issue detail view (use 'eye' icon) to see issue information.

issue: fix issue display problems

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/classes/patron-transaction.ts
projects/admin/src/app/circulation/patron/loan/loan.component.ts
projects/admin/src/app/circulation/services/patron-transaction.service.ts
projects/admin/src/app/classes/ill-request.ts
projects/admin/src/app/classes/items.ts
projects/admin/src/app/classes/library.ts
projects/admin/src/app/classes/loans.ts
projects/admin/src/app/record/brief-view/patrons-brief-view.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
projects/admin/src/app/service/items.service.ts
projects/admin/src/manual_translations.ts

1.3.0 to dev

---

projects/public-search/src/app/patron-profile/patron-profile-fees/patron-profile-fee/patron-profile-fee.component.html
projects/public-search/src/app/patron-profile/patron-profile-fees/patron-profile-fee/patron-profile-fee.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-fees/patron-profile-fees.component.html
projects/public-search/src/app/patron-profile/patron-profile-fees/patron-profile-fees.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-request/patron-profile-ill-request.component.html
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-request/patron-profile-ill-request.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-requests.component.html
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-requests.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loan/patron-profile-loan.component.html
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loan/patron-profile-loan.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loans.component.html
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loans.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-personal/patron-profile-personal.component.html
projects/public-search/src/app/patron-profile/patron-profile-personal/patron-profile-personal.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-requests/patron-profile-request/patron-profile-request.component.html
projects/public-search/src/app/patron-profile/patron-profile-requests/patron-profile-request/patron-profile-request.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-requests/patron-profile-requests.component.html
projects/public-search/src/app/patron-profile/patron-profile-requests/patron-profile-requests.component.spec.ts

* Removes unnecessary CSS rules.
* Improves HTML structure for better responsiveness.

users: improve patron profile responsiveness

---

projects/admin/src/app/routes/issues-route.ts
projects/admin/src/app/routes/items-route.ts

reports: improve inventory list for items
* Changes API endpoint for inventory list.
* Adapts configuration for export formats into item route.
* rero/rero-ils#1842
* rero/ng-core#384

reports: improve inventory list for items

---

projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html

- improve display of notifications

libraries: improve display of notification settings

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html

* Removes abstract and titlesProper fields.
* Adds summary fields.
* Closes rero/rero-ils#1620.
- https://github.com/rero/rero-ils/issues/1620
- Check summary field on document detail view.

documents: update field display

---

projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html

patron types: add a code field on the detail view

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/classes/library.ts
projects/admin/src/app/classes/notification.ts
projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts
projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/record/custom-editor/libraries/library.component.ts
projects/admin/src/app/record/custom-editor/libraries/pipe/notificationType.pipe.spec.ts
projects/admin/src/app/record/custom-editor/libraries/pipe/notificationType.pipe.ts
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html

* Implements three new notifications: booking, request and transit_notice.
* Implements a new field communication language.
* Customizes message by type of notifications.
- Implements 3 new notifications
My PR depends PR(s):
* https://github.com/rero/rero-ils/pull/1914
- Check notifications form

libraries: implement three new types of notification

---

projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html

- Bug on notification settings translation

libraries: fix translation on notification settings

---

projects/admin/src/app/menu/menu.component.ts

documents: enable the search bar on the detail view

---

projects/admin/src/app/record/detail-view/organisation-detail-view/organisation-detail-view.component.html

organisations: fix translation of labels

---

projects/admin/src/app/menu/menu.component.ts

ui: fix hide or show searchbar on pro interface

---

projects/public-search/src/app/document-detail/holdings/items/items.component.html
projects/public-search/src/app/document-detail/holdings/items/items.component.spec.ts

serials: inform when there's no item attached to the holdings

---

CHANGELOG.md
package-lock.json
package.json

release: v0.15.0

---

.github/labeler.yml

- To fix an error in the github labeler action yaml.

documentation: remove duplicate label rule

---

projects/admin/src/app/record/formly/type/cipo-patron-type-item-type/cipo-patron-type-item-type.component.ts
projects/admin/src/app/record/formly/type/cipo-patron-type-item-type/class/settings.ts

Closes rero/rero-ils#1859.
- check workflow into issue
-

editor: fix circulation policy setting widget

---

projects/public-search/src/app/api/ill-request-api.service.ts
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-request/patron-profile-ill-request.component.html
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-request/patron-profile-ill-request.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-requests.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-requests.component.ts
projects/public-search/src/app/patron-profile/patron-profile.component.spec.ts
projects/public-search/src/app/patron-profile/patron-profile.component.ts

ILL requests: fix public view

---

projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html
projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.html
projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.ts
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.html
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.ts
projects/admin/src/app/service/patron.service.ts
projects/public-search/src/app/patron-profile/patron-profile.component.spec.ts

circulation: display position into request queue

---

projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts

No checks needs to be done when the user email field is empty.

users: fix unique email check

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/public-search/src/app/document-detail/holdings/holding/holding.component.html
projects/public-search/src/app/document-detail/holdings/holding/holding.component.ts
projects/public-search/src/app/document-detail/item/item.component.html
projects/public-search/src/app/document-detail/item/item.component.ts

- translation problem
- Check circulation informations on document detail view

documents: fix translation on circulation informations

---

projects/admin/src/app/api/operation-logs-api.service.ts
projects/admin/src/app/circulation/patron/history/history-item/history-item.component.ts
projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.html
projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.spec.ts

* Restores operation logs and transaction history on the item detailed
of the professional interface and the patron history on the circulation
interface after the refactoring of the operation logs.
- Item: Check operation logs
- Item: Check circulation history
- circulation: Check patron history

Restores operation logs and transaction history

---

CHANGELOG.md
package-lock.json
package.json

- To release `rero-ils-ui` in `v0.16.0`.

release: v0.16.0

---

CHANGELOG.md
package-lock.json
package.json

- Release `v0.16.4`
- Check changed files.

release: v0.16.4

---

projects/admin/src/app/circulation/main-request/main-request.component.ts
projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html
projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.ts

circulation: improve requested loans tab

---

CHANGELOG.md
package-lock.json
package.json

- Release `v0.16.7`. 
- See changed files.

release: v0.16.7

---

projects/admin/src/app/acquisition/classes/order.ts
projects/admin/src/app/acquisition/components/account/account-detail-view/account-detail-view.component.html
projects/admin/src/app/acquisition/components/account/account-list/account-list.component.html
projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.html
projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.html
projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.ts
projects/admin/src/app/acquisition/components/order/order-detail-view/order-detail-view.component.html
projects/admin/src/app/acquisition/components/order/order-detail-view/order-line/order-line.component.html
projects/admin/src/app/acquisition/components/order/order-detail-view/order-line/order-line.component.ts
projects/admin/src/app/acquisition/routes/orders-route.ts
projects/admin/src/app/menu/service/menu-user-services.service.ts

* Updates order detail/brief views.
* Adds facet and sort filters on orders result view.
* Fixed orders brief/detail view.

acquisitions: order facets

---

projects/public-search/src/app/patron-profile/patron-profile-personal/patron-profile-personal.component.html

users: translate the gender

---

projects/admin/src/app/record/detail-view/ill-request-detail-view/ill-request-detail-view.component.html

* Improves the display of the ILL request by removing extra parenthesis in some fields.
* Closes #2062.

ill requests: removes extra parenthesis

---

CHANGELOG.md
package-lock.json
package.json

release: v0.16.2

---

projects/admin/src/app/api/local-field-api.service.ts

local fields: improve query result

---

projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html

Closes rero/rero-ils#2207.
https://github.com/rero/rero-ils/pull/2210

requests: display pickup location name

---

package-lock.json
package.json
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/holdings-route.ts

My PR depends:
* rero/ng-core#434
* rero/rero-ils#2219
- Check message on delete holdings (document view and holdings detail view)

holdings: customize the delete message

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/classes/typeahead/documents-typeahead.ts

* Closes rero/rero-ils#2249.
My PR depends:
* rero/ng-core#436

editor: add ISBN/ISSN on document typeahead

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/classes/library.ts
projects/admin/src/app/pipe/country-code-translate.pipe.spec.ts
projects/admin/src/app/pipe/country-code-translate.pipe.ts
projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts
projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/record/custom-editor/libraries/library.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding-shared-view/holding-shared-view.component.spec.ts
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html
projects/admin/src/app/record/operation-logs/operation-logs-dialog/operation-logs-dialog.component.spec.ts
projects/admin/src/app/record/operation-logs/operation-logs.component.spec.ts

* Updates the library custom editor to allow specify acquisition
settings.
* Updates the library detail view to display acquisition settings in a
new tab.
* Fixes deprecated Jasmine uni tests.

library: update library custom editor

---

projects/admin/src/app/menu/service/menu-user-services.service.ts

issues: late issues filtered by current library

---

projects/admin/src/app/service/record-permission.service.ts

* Closes rero/rero-ils#2102
My PR depends on  PR(s):
* rero/rero-ils#2271

fees: add message for delete information

---

CHANGELOG.md
package-lock.json
package.json

- For the `v0.17.0` release. 
- Check changed files.

release: v0.17.0

---

projects/public-search/src/app/document-detail/item/item.component.html

document: fix wrong URL on collection

---

CHANGELOG.md
package-lock.json
package.json

- To release `v0.17.1`. 
- Check changed files.

release: v0.17.1

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/main-request/main-request.component.ts

circulation: restore missing translations

---

projects/admin/src/app/acquisition/classes/order.ts
projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.html
projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.scss
projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.ts
projects/admin/src/app/acquisition/components/order/order-detail-view/order-detail-view.component.html
projects/admin/src/app/acquisition/components/order/order-detail-view/order-detail-view.component.ts
projects/admin/src/app/acquisition/components/order/order-summary/order-summary.component.html
projects/admin/src/app/acquisition/components/order/order-summary/order-summary.component.scss
projects/admin/src/app/acquisition/components/order/order-summary/order-summary.component.ts
projects/admin/src/app/acquisition/components/order/place-order-form/place-order-form.component.ts
projects/admin/src/app/acquisition/routes/orders-route.ts
projects/admin/src/app/guard/acq-order-line.guard.ts
projects/admin/src/app/scss/styles.scss

* Updates item counter into the order detail view.
* Adds display of item ordered counter and item received counter into
the order summary component.
* Fix CSS about `btn-show-more` class if included into a card section.

acquisition: item quantities display

---

projects/admin/src/app/circulation/patron/history/history-log/history-log.component.html

circulation: add item link on the patron history tab

---

projects/admin/src/app/api/import-source-api.service.ts
projects/admin/src/app/classes/external-source.ts
projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts
projects/admin/src/app/routes/import-documents-route.ts

* Adds Library of Congress catalog.
* Adds DNB catalog.
* Adds SLSP catalog.
* Adds UGent catalog.
* Adds KULeuven catalog.
Co-Authored-by: Benoit Erken <erken.benoit@gmail.com>
* rero/rero-ils#2394

import: add new sources to import from the web

---

projects/admin/src/app/api/import-source-api.service.ts
projects/admin/src/app/record/operation-logs/operation-logs.component.html
projects/admin/src/app/record/operation-logs/operation-logs.component.scss
projects/admin/src/app/record/operation-logs/operation-logs.component.ts

operation logs: Fix the window display if no record

---

projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.ts

acquisition: fix receipt date in order brief view

---

projects/admin/src/app/circulation/services/patron-transaction.service.ts
projects/admin/src/app/routes/import-documents-route.ts

When an error occurs on `PatronTransaction` operations, the error
message wasn't always displayed correctly. Fix this problem with default
message if no better option could be used.

circulation: fix patron transaction error message.

---

CHANGELOG.md
package-lock.json
package.json

release: v0.19.0

---

projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.html
projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.scss
projects/admin/src/app/acquisition/formly/type/select-account/select-account.component.html
projects/admin/src/app/acquisition/formly/type/select-account/select-account.component.scss

Add the account number/reference into the option list to help manager to
choose the correct account when adding an order line or an additional
fee (for reception).

acquisition: improve AcqAccount select editor widget

---

projects/admin/src/app/acquisition/classes/receipt.ts
projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-form.ts
projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt.ts
projects/admin/src/app/acquisition/formly/type/repeat-section.type.ts

* Adds options for show or hide trash on repeat section.
* Adds a checkbox to selected record.
* Adds a new field vat rate on order line.

acquisition: refactoring order lines on receipt form

---

projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.html

users: fix user editor title

---

projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html
projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.ts

* Adds a button to access patron circulation panel.
* Expands by default the user informations section.
* Closes rero/rero-ils#2533.

patrons: improve patron detailed view

---

projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event/patron-transaction-event.component.html

patrons: fix display of patron transaction event

---

projects/admin/src/app/circulation/circulation.module.ts
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/item/item.component.scss
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/pipe/get-loan-cipo.pipe.ts
projects/admin/src/app/classes/circ-policy.ts
projects/admin/src/app/classes/core.ts
projects/admin/src/app/scss/styles.scss
projects/admin/src/app/service/loan.service.ts

If logged user is a system librarian, a debug button is available on
patron circulation page for each item. This button displays raw
informations about the loan and the related circulation policy.
* [rero/rero-ils#2589](https://github.com/rero/rero-ils/pull/2589)

circulation: add debug information panels

---

projects/admin/src/app/acquisition/acquisition.module.ts
projects/admin/src/app/acquisition/classes/receipt.ts
projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.html
projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.scss
projects/admin/src/app/acquisition/components/order/order-detail-view/order-line/order-line.component.html
projects/admin/src/app/acquisition/components/order/order-summary/order-summary.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-detail-view/receipt-detail-view.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-form.ts
projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-view.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-view.component.ts
projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt.ts
projects/admin/src/app/acquisition/components/receipt/receipt-summary/receipt-summary.component.html
projects/admin/src/app/acquisition/pipes/receipt-line-total-amount.pipe.ts

* Updates receipt form display for a vertical alignment to allow more
spaces for input fields.
* Fixes some typo.
* Create a pipe to compute the reception line total amount.
* Improves some cascading styles for a better display.

acquisition: last changes

---

projects/admin/src/app/classes/core.ts
projects/admin/src/app/classes/library.ts
projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts
projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html

* Update the library custom editor to allow management of new `extra`
field available for any acquisition setting section.
* Updates the library detail view to display this new field.

library: 'extra' field management for acquisition setting

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.html
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
projects/admin/src/app/service/holdings.service.ts

- Allow librarian to request holding
- Adapted item-request component for both holding and item 
https://tree.taiga.io/project/rero21-reroils/task/2355

holdings: add request for holding in professional interface

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html

* Closes rero/rero-ils#2626.
* Fixes librarian detail view.

circulation: fix display patron profile on checkout

---

projects/public-holdings-items/src/index.html
projects/public-search/src/app/document-detail/holdings/holding/holding.component.html
projects/public-search/src/app/document-detail/holdings/holding/holding.component.scss
projects/public-search/src/app/document-detail/holdings/holding/holding.component.spec.ts
projects/public-search/src/app/document-detail/holdings/holding/holding.component.ts
projects/public-search/src/app/document-detail/holdings/holdings.component.html

Always collapse/hide items related to a serial holding in the document
detail view.
Closes rero/rero-ils#2502.

holdings: fix item collapsing.

---

projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html

patron: fix some translations

---

projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.html
projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.ts

circulation policies: fix detail view

---

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/public-search/src/app/document-brief/document-brief.component.html

document: fix title display on brief view

---

projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.html

Fixes some problem when displaying the detail information about a
circulation policy (reminders, fees).

circ_policies: fix detail view

---

projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html
projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.ts

patrons: display patron `creation_date` field

---

projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/routes/patrons-route.ts
projects/public-search/src/app/routes/documents-route.service.ts

- Fixes de default sort for documents in the public and admin view.
- Remove useless default sort options.
- Closes rero/rero-ils#2562.
- Closes rero/rero-ils#2527.
My PR depends on https://github.com/rero/ng-core/pull/468

search: fix default sort parameters

---

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/public-search/src/app/document-brief/document-brief.component.html

document: move edition statement into brief view

---

CHANGELOG.md
package-lock.json
package.json

release: v0.21.1

---

.github/labeler.yml
.github_changelog_generator

documentation: improve changelog generation and labeler

---

projects/public-search/src/app/document-detail/holdings/holding/holding.component.html

Solves [#2494](https://github.com/rero/rero-ils/issues/2494)
Review of PR https://github.com/rero/rero-ils/pull/2651

holdings: set items counter to number of public items

---

projects/public-search/src/app/api/holdings-api.service.ts

The sorting is done with the cascade organization, library and location.
- Check document detail view: Holdings/items sort

documents: add order on holdings/items

---

projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loans.component.ts

* Closes rero/rero-ils#2750.
- Check loans tab on patron profile

patron profile: change the number of loans to 20

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts

* Updates process to check duplicates during Import from the Web (use bf:Isbn, bf:Issn, bf:Lccn, bf:Doi)
Co-Authored-by: Benoit Erken <erken.benoit@gmail.com>
n/a
- In the professional view, try to import ISBN 9783111256863 from KULeuven. Click on Import. It should works now.

import: fix check of duplicates during import from the web

---

projects/admin/src/app/circulation/patron/loan/loan.component.ts

- Closes https://github.com/rero/rero-ils/issues/2401

circulation: disambiguate checkout error message

---

projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.html
projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
projects/admin/src/app/service/holdings.service.ts
projects/public-search/src/app/api/holdings-api.service.ts
projects/public-search/src/app/api/location-api.service.spec.ts
projects/public-search/src/app/api/location-api.service.ts
projects/public-search/src/app/classes/holdings.ts
projects/public-search/src/app/document-detail/holdings/holding/holding.component.html
projects/public-search/src/app/document-detail/holdings/holding/holding.component.ts
projects/public-search/src/app/document-detail/item/item.component.html
projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.html
projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.spec.ts
projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.ts
projects/public-search/src/app/document-detail/request/request.component.html
projects/public-search/src/app/document-detail/request/request.component.spec.ts
projects/public-search/src/app/document-detail/request/request.component.ts

Implement holdings request for global and professional interfaces

Merge US holding request to staging

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html

Fix display of serial items for other organisations.
- Comment in PR https://github.com/rero/rero-ils/pull/2811

documents: fix display of serial items for other organisations

---

projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts

Fix request of item in detail view.
- Comments in https://github.com/rero/rero-ils/pull/2811

items: fix request of item in detail view

---

CHANGELOG.md
package-lock.json
package.json

release: v0.22.0

---

projects/admin/src/app/circulation/checkin/checkin.component.ts

circulation: enter patron barcode when checkin form contains items

---

projects/admin/src/app/record/detail-view/document-detail-view/holding-detail/holding-detail.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html

- Closes https://github.com/rero/rero-ils/issues/2276
- Closes https://github.com/rero/rero-ils/issues/2752

translations: fix missing translations

---

projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html

* Closes https://github.com/rero/rero-ils/issues/2727

patron view: fix missing translations

---

CHANGELOG.md
package-lock.json
package.json

release: v0.23.0

---

projects/admin/src/app/circulation/main-request/main-request.component.ts
projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html

requests: add location/pickup-location sort criteria.

---

projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.ts

* Fixes a string that was not correctly extracted for translation

translations: fix missing request translation

---

projects/public-search/src/app/routes/documents-route.service.ts

* Adds config to export documents in public search.
* rero/rero-ils#2898

documents: export records

---

projects/shared/src/lib/view/thumbnail/thumbnail.component.scss

document: fix size of the thumbnail on mobile brief view

---

projects/admin/src/app/acquisition/routes/orders-route.ts

* Adds config to export orders in professionnal view.
* rero/rero-ils#2949

aquisitions: export orders

---

projects/admin/src/app/record/detail-view/document-detail-view/holding-organisation/holding-organisation.component.html

fix: extract missing translation

---

projects/admin/src/app/menu/menu-user/menu-user.component.html
projects/admin/src/app/menu/menu-user/menu-user.component.ts
projects/admin/src/app/menu/service/library-switch-menu-storage.service.spec.ts
projects/admin/src/app/menu/service/library-switch-menu-storage.service.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/service/app-initializer.service.ts

* Adds a library switch storage service.
* Adds a event on menu user to track signout.

library switch menu: fix storage current library

---

CHANGELOG.md
package-lock.json
package.json

release: v0.24.0

---

projects/admin/src/app/app.component.html

 templates: update footer info

---

package-lock.json
package.json
projects/admin/src/app/acquisition/components/account/account-list/account-list.component.html
projects/admin/src/app/acquisition/components/account/account-list/account-list.component.ts
projects/admin/src/app/acquisition/routes/accounts-route.ts
projects/admin/src/app/acquisition/routes/orders-route.ts

* Adds config to accounts route.
* Configures export button component.
* rero/rero-ils#2957
* rero/ng-core#504

acquisitions: export accounts

---

package-lock.json
package.json
projects/admin/src/app/acquisition/components/account/account-list/account-list.component.html
projects/admin/src/app/acquisition/components/account/account-list/account-list.component.ts
projects/admin/src/app/acquisition/routes/accounts-route.ts
projects/admin/src/app/acquisition/routes/orders-route.ts

merge US-Acquisition-export

---

CHANGELOG.md
package-lock.json
package.json

release: v0.25.0

---

projects/admin/src/app/api/document-api.service.spec.ts
projects/admin/src/app/api/document-api.service.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts

documents: add linked documents button

---

projects/public-search/src/app/document-detail/holdings/holding/holding.component.html
projects/public-search/src/app/document-detail/item/item.component.html

holdings: fix display in small screens

---

projects/public-search/src/app/patron-profile/patron-profile-document/patron-profile-document.component.html
projects/public-search/src/app/patron-profile/patron-profile-document/patron-profile-document.component.ts

patron profile: fix wrong url on the contributor

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts

If no identifier has been selected for the control, we try to search by the main title
* Closes rero/rero-ils#3031.

document: improve import control

---

projects/admin/src/app/routes/circulation-policies-route.ts
projects/admin/src/app/routes/collections-route.ts
projects/admin/src/app/routes/corporate-bodies-route.ts
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/ill-requests-route.ts
projects/admin/src/app/routes/import-documents-route.ts
projects/admin/src/app/routes/issues-route.ts
projects/admin/src/app/routes/item-types-route.ts
projects/admin/src/app/routes/libraries-route.ts
projects/admin/src/app/routes/loans-route.ts
projects/admin/src/app/routes/patron-types-route.ts
projects/admin/src/app/routes/patrons-route.ts
projects/admin/src/app/routes/persons-route.ts
projects/admin/src/app/routes/templates-route.ts
projects/admin/src/app/routes/vendors-route.ts

* Adds filters on some resources.
* Closes rero/rero-ils#2576.

search result: show facets on no result found

---

projects/admin/src/app/circulation/patron/history/history-log/history-log.component.html
projects/public-search/src/app/patron-profile/patron-profile-histories/patron-profile-history/patron-profile-history.component.html
projects/shared/src/lib/pipe/contribution-filter.pipe.spec.ts
projects/shared/src/lib/pipe/contribution-filter.pipe.ts

In the case of a local contribution, the preferred_name field should be used for display.

patron history: fix contributions display

---

CHANGELOG.md
package-lock.json
package.json

release: v14.0.1

---

angular.json
projects/admin/src/app/api/permission-api.service.spec.ts
projects/admin/src/app/api/permission-api.service.ts
projects/admin/src/app/menu/menu-definition/menu-app.ts
projects/admin/src/app/menu/menu-switch-library/menu-switch-library.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.html
projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
projects/admin/src/app/record/detail-view/local-field/local-field.component.html
projects/admin/src/app/record/detail-view/local-field/local-field.component.ts
projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.html
projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.scss
projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.ts
projects/admin/src/app/routes/import-documents-route.ts
projects/admin/src/app/routes/items-route.ts
projects/public-search/src/app/document-detail/holdings/holding/holding.component.html

permissions : Fix permission problems

---

projects/admin/src/app/record/brief-view/items-brief-view/items-brief-view.component.html
projects/admin/src/app/routes/items-route.ts

* Adds current_pending_requests order.
* Adds current_pending_requests fields on brief view.
* [rero/rero-ils#3222](https://github.com/rero/rero-ils/pull/3222)

inventory: current pending requests

---

projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts

Uses the new `sort_date` field to sort issue into the holdings detail view.
https://github.com/rero/rero-ils/pull/3226

issues: fix issue sorting

---

projects/admin/src/app/api/local-field-api.service.ts
projects/admin/src/app/record/detail-view/local-field/local-field.component.html
projects/admin/src/app/record/detail-view/local-field/local-field.component.ts

* Closes https://github.com/rero/rero-ils/issues/2994

local_fields: fix local fields orders

---

projects/admin/src/app/circulation/patron/patron-transactions/patron-fee/patron-fee.component.ts
projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.ts

Fix subscription to modal dialog box when adding a manual fee to prevent unknown component subscription.

circulation: fix manual fee modal dialog

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/menu/menu-definition/menu-app.ts
projects/admin/src/app/record/brief-view/statistics-cfg-brief-view-component.ts
projects/admin/src/app/record/detail-view/statistics-cfg-detail-view/statistics-cfg-detail-view.component.html
projects/admin/src/app/record/detail-view/statistics-cfg-detail-view/statistics-cfg-detail-view.component.ts
projects/admin/src/app/routes/route.service.ts
projects/admin/src/app/routes/statistics-cfg-route.ts
projects/shared/src/lib/util/permissions.ts

* Adds statistics configuration to the admin menu.
* Adds brief view.
* Adds detail view.

statistics: add brief and detail view config

---

projects/admin/src/app/record/brief-view/statistics-cfg-brief-view-component.ts
projects/admin/src/app/record/detail-view/statistics-cfg-detail-view/statistics-cfg-detail-view.component.html
projects/admin/src/app/routes/statistics-cfg-route.ts

* Adds routes for edit and new.
* Improves brief and detail views.

statistics: add crud to stats config

---

projects/admin/src/app/acquisition/components/order/order-detail-view/order-detail-view.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-list/receipt-list.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-summary/receipt-summary.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loan/patron-profile-loan.component.html
projects/public-search/src/manual_translation.ts

translations: fix string translation i18n pipe

---

projects/admin/src/app/record/search-view/document-record-search/document-record-search.component.html
projects/admin/src/app/routes/base-route.ts
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/route-tool.service.ts
projects/admin/src/app/service/organisation.service.ts
projects/shared/src/lib/service/user.service.ts

* Closes rero/rero-ils#2891.
https://github.com/rero/ng-core/pull/541

documents: default search filters on resource search input

---

projects/admin/src/app/circulation/checkin/checkin.component.html
projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/patron/card/card.component.html
projects/admin/src/app/circulation/patron/card/card.component.ts
projects/admin/src/app/circulation/patron/loan/loan.component.ts

circulation: fix clear patron button display

---

projects/admin/src/app/menu/menu-definition/menu-app.ts
projects/admin/src/app/record/detail-view/permission-detail-view/permission-detail-view.component.html

Co-authored-by: Pascal Repond <pascal.repond@rero.ch>

translations: add missing translate attribute

---

projects/admin/src/app/menu/service/library-switch-menu.service.ts

library switch menu: fix sort by name

---

projects/admin/src/app/record/detail-view/ill-request-detail-view/ill-request-detail-view.component.html
projects/admin/src/app/record/detail-view/library-detail-view/location/location.component.html

* Adds a icon to indicate the location is type ill_request in the list.
* Updates pickup_name with ill_pickup_name on ill request detail view.

ill request: ill pickup name

---

projects/admin/src/app/routes/items-route.ts

Added descending sorting on barcode, call number
and second call number fields.
* Closes rero/rero-ils#2991.

inventory list: add descending sorting

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts
projects/public-search/src/app/api/item-api.service.ts

items: update default sort for serial holding to `issue_sort_date`

---

projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.html
projects/admin/src/app/routes/issues-route.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/service/holdings.service.ts
projects/shared/src/lib/class/item-status.ts

* Removes references to removed "CLAIMED" issue status.
* Adapts item issues route for new facets : claims_count and claims_date

items: claim issue facets

---

angular.json
projects/admin/src/app/app.module.ts
projects/admin/src/app/classes/library.ts
projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts
projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/record/custom-editor/libraries/library.component.scss
projects/admin/src/app/record/custom-editor/libraries/library.component.ts
projects/admin/src/app/shared/primeng-import/primeng-import.module.ts

* Refactors `Library` resource editor to allow serial acquisition
data management.
* Use PrimeNg elements in this editor for coherence.

library: improve `Library` editor

---

projects/admin/src/app/record/detail-view/library-detail-view/day-opening-hours/day-opening-hours.component.ts
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.scss
projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.ts

* Refactors the library detail view using accordion due to new data to
display. Using tabs was not more efficient way due to horizontal
scrolling  of theses tabs with a new entry.

library:  refactoring library detailed view

---

CHANGELOG.md
package-lock.json
package.json

release: v14.3.0

---

projects/admin/src/app/routes/items-route.ts

Deleted the injection of the date in the route.
This functionality is transferred to the jsonschema.

item: delete the default value

---

projects/admin/src/app/api/ill-request-api.service.spec.ts
projects/admin/src/app/api/ill-request-api.service.ts
projects/admin/src/app/circulation/circulation-routing.module.ts
projects/admin/src/app/circulation/circulation.module.ts
projects/admin/src/app/circulation/circulation.scss
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/patron/ill-request/ill-request-item/ill-request-item.component.html
projects/admin/src/app/circulation/patron/ill-request/ill-request-item/ill-request-item.component.ts
projects/admin/src/app/circulation/patron/ill-request/ill-request.component.html
projects/admin/src/app/circulation/patron/ill-request/ill-request.component.ts
projects/admin/src/app/circulation/patron/main/main.component.html
projects/admin/src/app/circulation/patron/main/main.component.ts
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-request/patron-profile-ill-request.component.html
projects/public-search/src/app/pipe/journal-volume.pipe.spec.ts
projects/public-search/src/app/pipe/journal-volume.pipe.ts

* Adds a new tab to display pending ILL requests.
* Fixes the problem on separator parameter in JournalVolume pipe.
* Fixes the typing of the journal parameter to the JournalVolume pipe.
* Closes rero/rero-ils#2165.
ILS: https://github.com/rero/rero-ils/pull/3322

circulation: add ill requests tab

---

projects/admin/src/app/classes/typeahead/mef-typeahead.ts
projects/admin/src/app/routes/corporate-bodies-route.ts
projects/admin/src/app/routes/persons-route.ts
projects/public-search/src/app/routes/documents-route.service.ts
projects/shared/src/lib/service/search-bar-config.service.ts
projects/shared/src/lib/view/brief/organisation-brief/organisation-brief.component.ts
projects/shared/src/lib/view/brief/person-brief/person-brief.component.ts

* Renames `entities` to `remote_entities`.
* rero/rero-ils#3368

entities: replace with new resource name

---

projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event-form/patron-transaction-event-form.component.ts

- Addresses RT 566
- Depends on https://github.com/rero/rero-ils/pull/3373

fees: add invoice payment method

---

projects/public-search/src/app/patron-profile/patron-profile-document/patron-profile-document.component.html
projects/public-search/src/app/patron-profile/patron-profile-document/patron-profile-document.component.ts
projects/shared/src/lib/view/contribution/contribution.component.html

Contributions were not displayed in the public view of the reader folder.
* Limits display to 3 contributions.
* Fixes the link to the public view contribution.
* Closes rero/rero-ils#3380.

patron profile: fix bug on contributions

---

projects/public-search/src/app/api/loan-api.service.ts
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loan/patron-profile-loan.component.html
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loan/patron-profile-loan.component.ts
projects/public-search/src/app/patron-profile/patron-profile.component.html
projects/public-search/src/app/patron-profile/patron-profile.component.ts
projects/public-search/src/app/patron-profile/patron-profile.service.ts

patron profile: show overdue preview fees

---

projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/received-issue/received-issue.component.ts
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts

* Closes https://github.com/rero/rero-ils/issues/1705.

holdings: issue creation permission management

---

package-lock.json
package.json
projects/admin/src/app/acquisition/routes/accounts-route.ts
projects/admin/src/app/acquisition/routes/order-lines-route.ts
projects/admin/src/app/acquisition/routes/orders-route.ts
projects/admin/src/app/acquisition/routes/receipt-lines-route.ts
projects/admin/src/app/acquisition/routes/receipts-route.ts
projects/admin/src/app/circulation/services/loan-fixed-date.service.spec.ts
projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.html
projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.ts
projects/admin/src/app/record/custom-editor/holding-editor/holding-editor.component.html
projects/admin/src/app/record/custom-editor/holding-editor/holding-editor.component.ts
projects/admin/src/app/record/custom-editor/libraries/library.component.ts
projects/admin/src/app/routes/circulation-policies-route.ts
projects/admin/src/app/routes/collections-route.ts
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/holdings-route.ts
projects/admin/src/app/routes/ill-requests-route.ts
projects/admin/src/app/routes/item-types-route.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/routes/libraries-route.ts
projects/admin/src/app/routes/local-fields-route.ts
projects/admin/src/app/routes/locations-route.ts
projects/admin/src/app/routes/organisations-route.ts
projects/admin/src/app/routes/patron-types-route.ts
projects/admin/src/app/routes/patrons-route.ts
projects/admin/src/app/routes/templates-route.ts
projects/admin/src/app/routes/vendors-route.ts
projects/public-search/src/app/patron-profile/patron-profile-personal/patron-profile-personal.component.spec.ts

A confirmation message is displayed if the user leaves the form without saving it.
* Closes rero/rero-ils#2104.
- https://github.com/rero/ng-core/pull/554

editor: add can deactivate guard

---

projects/admin/src/app/app.module.ts
projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts
projects/admin/src/app/record/formly/type/entity-typeahead/add-entity-local-form/add-entity-local-form.component.html
projects/admin/src/app/record/formly/type/entity-typeahead/add-entity-local-form/add-entity-local-form.component.ts
projects/admin/src/app/record/formly/type/entity-typeahead/add-entity-local.component.ts
projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.component.html
projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.component.ts
projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.interface.ts

editor: allow local entities creation from document editor

---

projects/shared/src/lib/view/contribution/contribution.component.html
projects/shared/src/lib/view/contribution/contribution.component.ts

The contributions link now relaunches a document search.

document: adapt link on contribution field

---

CHANGELOG.md
package-lock.json
package.json

release: v14.4.0

---

projects/admin/src/app/api/ill-request-api.service.ts
projects/admin/src/app/circulation/patron/ill-request/ill-request-item/ill-request-item.component.html
projects/admin/src/app/circulation/patron/ill-request/ill-request-item/ill-request-item.component.ts
projects/admin/src/app/circulation/patron/ill-request/ill-request.component.html
projects/admin/src/app/circulation/patron/ill-request/ill-request.component.ts
projects/admin/src/manual_translations.ts

ILL Request: better display into patron circulation

---

projects/admin/src/manual_translations.ts

translations: add missing menu manual translation

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html
projects/shared/src/lib/pipe/get-translated-label.pipe.ts

* Closes rero/rero-ils#3370.
* Fix label used for "status" column in holding detail view (only for serial holding).

issues: fix status display into holding detail view

---

projects/admin/src/app/circulation/checkin/checkin.component.ts

* Shows the libray name when the item is in transit.

circulation: uniformize the item in transit message

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/shared/src/lib/view/brief/part-of/part-of.component.html
projects/shared/src/lib/view/brief/part-of/part-of.component.ts

Use of the title field available in the data.
If not present, a document request is made.

document: partOf optimization

---

projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.html
projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.scss

* Fixes https://github.com/rero/rero-ils/issues/3440.

operation history: fix pickup location label

---

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts
projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.ts

fix: certain texts get unselected on keystroke

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html

document: improved display of genre form field

---

package-lock.json
package.json
projects/admin/src/app/classes/typeahead/mef-typeahead.ts
projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts
projects/admin/src/app/record/detail-view/entities-detail-view/local/entities-local-detail-view.component.ts
projects/admin/src/app/record/detail-view/entities-detail-view/local/local-organisation-detail-view/local-organisation-detail-view.component.html
projects/admin/src/app/record/detail-view/entities-detail-view/local/local-person-detail-view/local-person-detail-view.component.html
projects/admin/src/app/record/detail-view/entities-detail-view/local/local-place-detail-view/local-place-detail-view.component.html
projects/admin/src/app/record/detail-view/entities-detail-view/local/local-topic-detail-view/local-topic-detail-view.component.html
projects/public-search/src/app/routes/documents-route.service.spec.ts
projects/shared/src/lib/view/contribution/contribution.component.html
projects/shared/src/lib/view/contribution/contribution.component.ts

When importing documents, links to contributions and topics must be disabled.

document import: disable links

---

projects/shared/src/lib/interface/i-availability.ts
projects/shared/src/lib/view/availability/availability.component.html

availability: fix for the number of requests

---

projects/admin/src/app/service/keyboard-shortcuts.service.ts

fix: help shortcut

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts

* ILS: [items: sorting for standard holdings](https://github.com/rero/rero-ils/pull/3461)

items: sorting for standard holdings

---

projects/admin/src/app/record/detail-view/entities-detail-view/remote/entities-remote-detail-view.component.html
projects/admin/src/app/record/detail-view/entities-detail-view/remote/entities-remote-detail-view.component.ts
projects/admin/src/manual_translations.ts

entities: add place and temporal display

---

projects/admin/src/app/api/operation-logs-api.service.ts
projects/public-search/src/app/api/operation-logs-api.service.ts

Added loan type filter to have only one type in the history.
* Closes rero/rero-ils#3469.

history: fix duplicate records

---

projects/admin/src/app/record/custom-editor/libraries/library.component.html
projects/admin/src/app/record/custom-editor/libraries/library.component.ts

library: fix communication language on add

---

projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.html
projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.scss

* Fixes the classname so that it is considered by the scss file to load fontawesome.

transaction history: fix missing icon

---

CHANGELOG.md
package-lock.json
package.json

release: v14.5.0

---

projects/admin/src/app/menu/service/library-switch-menu.service.ts

library switch: always show the menu

---

projects/admin/src/app/menu/menu-mobile/menu-mobile.component.html
projects/admin/src/app/menu/menu-mobile/menu-mobile.component.ts
projects/admin/src/app/menu/menu-mobile/sub-menu/sub-menu.component.html
projects/admin/src/app/menu/menu-mobile/sub-menu/sub-menu.component.ts
projects/admin/src/app/menu/menu-switch-library/menu-switch-library.component.ts
projects/admin/src/app/menu/menu.component.html
projects/admin/src/app/menu/service/library-switch-menu-event.service.ts

library switch: fix switch on mobile

---

projects/admin/src/app/circulation/checkin/checkin.component.ts

* Closes https://github.com/rero/rero-ils/issues/3509.

circulation: fix checkin patron info

---

projects/admin/src/app/menu/menu-definition/menu-app.ts
projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html

* Changes some icons to more adapted versions.
* Closes https://github.com/rero/rero-ils/issues/1645.

menus: add new icons

---

projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts

documents: fix notes display

---

projects/admin/src/app/circulation/patron/loan/loan.component.html
projects/admin/src/app/circulation/patron/loan/loan.component.ts

* Closes rero/rero-ils#2616.
- https://github.com/rero/rero-ils/pull/3549

circulation: add sort on location (checkout)

---

projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/patrons-route.ts
projects/public-search/src/app/routes/documents-route.service.ts

* Adds patron search filters.
* Updates document search filters.
- https://github.com/rero/rero-ils/pull/3546

patron: add blocked and expired filters

---

angular.json
projects/admin/src/app/routes/documents-route.ts
projects/public-search/src/app/routes/documents-route.service.ts

* Adds datepicker css to the configuration.
- https://github.com/rero/rero-ils/pull/3528

document: add acquisition aggregation

---

projects/admin/src/app/acquisition/routes/orders-route.ts
projects/admin/src/app/routes/vendors-route.ts

* Adds new sort config for vendors and orders.
* https://github.com/rero/rero-ils/pull/3490

acquisition: add sort config

---

projects/admin/src/app/circulation/checkin/checkin.component.ts
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/item/item.component.ts
projects/admin/src/app/circulation/items-list/items-list.component.html
projects/admin/src/app/classes/items.ts

Show item information on check-in list with no active loan.
* Closes rero/rero-ils#3512.

circulation: item on check-in list without loan

---

projects/admin/src/app/routes/ill-requests-route.ts

- Depends on https://github.com/rero/rero-ils/pull/3567.

ill requests: adapt facet label

---

projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.html

- Closes https://github.com/rero/rero-ils/issues/3568.
- Depends on https://github.com/rero/rero-ils/pull/3576.

patron: fix total pending requests number

---

package-lock.json
package.json
projects/admin/src/app/api/library-api.service.spec.ts

- Fixes vulnerabilities.
- Updates ng-core version.
- Fixes failing test.

dependencies: update

---

projects/admin/src/app/acquisition/acquisition.module.ts
projects/admin/src/app/acquisition/acquisition.scss
projects/admin/src/app/acquisition/components/order/order-detail-view/order-line/order-line.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-detail-view/receipt-detail-view.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-detail-view/receipt-detail-view.component.scss
projects/admin/src/app/acquisition/components/receipt/receipt-detail-view/receipt-detail-view.component.ts
projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-form.ts
projects/admin/src/app/acquisition/components/receipt/receipt-summary/receipt-summary.component.html
projects/admin/src/app/acquisition/formly/type/field-document-brief-view.type.ts
projects/shared/src/lib/component/documents/document-brief-view/document-brief-view.component.html
projects/shared/src/lib/component/documents/document-brief-view/document-brief-view.component.scss
projects/shared/src/lib/component/documents/document-brief-view/document-brief-view.component.ts
projects/shared/src/lib/pipe/identifiedby-label.pipe.ts
projects/shared/src/lib/shared.module.ts
projects/shared/src/public-api.ts

* Adds document brief view component.
* Adds new formly field type to display document informations.
* https://github.com/rero/rero-ils/pull/3490
Check document information in :
- order detail view (order line and receipt tabs : 
- receipt detail view
- receipt form

acquisition: displaying more document information

---

projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html

* Adds temporary location name on request screen.
* Closes rero/rero-ils#3611.
- https://github.com/rero/rero-ils/pull/3621

feat(circulation): add temporary location name

---

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/routes/documents-route.ts
projects/public-holdings-items/src/index.html
projects/public-search/src/app/document-detail/holdings/holdings.component.html
projects/public-search/src/app/routes/documents-route.service.ts
projects/shared/src/lib/component/documents/files/files.component.html
projects/shared/src/lib/component/documents/files/files.component.scss
projects/shared/src/lib/component/documents/files/files.component.ts
projects/shared/src/lib/shared.module.ts
projects/shared/src/public-api.ts

* Adds the file list in the document detailed view using primeng.
* Adds "search in fulltext" button in the professionnal and public view.
* Changes the html page title for the document holding files view.

files: add files in the document detailed view

---

projects/admin/src/app/menu/menu-definition/menu-app.ts
projects/admin/src/app/routes/items-route.ts
projects/admin/src/app/routes/loans-route.ts
projects/admin/src/app/routes/patron-transaction-events-route.ts

* Requested by clients in RT738.
* Also fixes some facets inconsistencies in items, fees and loans
searches.

fix(inventory list): remove default lib filter

---

projects/admin/src/app/circulation/patron/ill-request/ill-request.component.ts
projects/public-search/src/app/api/ill-request-api.service.ts
projects/public-search/src/app/patron-profile/patron-profile-ill-requests/patron-profile-ill-requests.component.ts

The "remove_archived" parameter is used to filter the list of results.
* Closes rero/rero-ils#3527.
- https://github.com/rero/rero-ils/pull/3637

fix(ill): add filter parameter

---

projects/admin/src/app/routes/base-route.ts
projects/admin/src/app/routes/holdings-route.ts
projects/admin/src/app/routes/items-route.ts

Access to the resource was limited to the current organisation.
This protects sensitive data on professional view.

chore(permissions): item and holdings

---

projects/admin/src/app/circulation/patron/patron-transactions/patron-fee/patron-fee.component.ts

* Fixes the options with the new formly configuration structure.

fix(fee): form options on add manual fee

---

projects/admin/src/app/service/bucket-name.service.ts

* Adds owning_library key to translate library name on filter name translation service.

fix(filter): add a new key for translation

---

package-lock.json
package.json
projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts
projects/admin/src/app/record/formly/type/entity-typeahead/add-entity-local-form/add-entity-local-form.component.ts
projects/public-search/src/app/patron-profile/patron-profile-personal-editor/patron-profile-personal-editor.component.ts

- [fix(editor): process json schema](https://github.com/rero/ng-core/pull/608)

fix(editor): use the new process json schema

---

.editorconfig
projects/admin/src/app/app.module.ts
projects/admin/src/app/circulation/services/loan-fixed-date.service.spec.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail/document-detail.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail/document-detail.component.ts
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/service/record-permission.service.ts
projects/admin/src/app/service/resources-files.service.spec.ts
projects/admin/src/app/service/resources-files.service.ts
projects/public-search/src/app/patron-profile/patron-profile-menu/patron-profile-menu.component.ts
projects/shared/src/lib/component/documents/files/files.component.ts
projects/shared/src/lib/util/permissions.ts
projects/shared/src/scss/styles.scss

* Adds files list and file uploads on the professionnal views.
* Adds icons depending of the mime types.
Need: https://github.com/rero/ng-core/pull/601

files: add upload file support

---

projects/admin/src/app/service/resources-files.service.ts
projects/public-holdings-items/src/index.html
projects/shared/src/lib/component/documents/files/files.component.html
projects/shared/src/lib/component/documents/files/files.component.scss
projects/shared/src/lib/component/documents/files/files.component.ts
projects/shared/src/lib/pipe/fa-icon-class.pipe.spec.ts
projects/shared/src/lib/pipe/fa-icon-class.pipe.ts
projects/shared/src/lib/shared.module.ts
proxy.conf.json
proxy/proxy.admin.conf.json

* Adds a button to preview the file before uploads.

files: add preview feature

---

angular.json
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/files-collections/files-collections.component.html
projects/admin/src/app/record/detail-view/document-detail-view/files-collections/files-collections.component.ts
projects/public-holdings-items/src/index.html
projects/public-search/src/app/scss/styles.scss
projects/shared/src/lib/component/documents/files/files.component.html
projects/shared/src/lib/component/documents/files/files.component.scss
projects/shared/src/lib/component/documents/files/files.component.ts
projects/shared/src/lib/modules/prime-ng-import/prime-ng-import.module.ts
projects/shared/src/scss/styles.scss

* Uses primeng bootstra4 theme to avoid layout problems.
* Adds a custom pager for the the files carousel.
* Adds an input to filter the files in the carousel.
* Makes the carousel reponsive.

files: add a pager and a input filter on the files carousel

---

package-lock.json
package.json
projects/admin/src/app/app.module.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/document-detail/document-detail.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/files-collections/files-collections.component.html
projects/admin/src/app/record/detail-view/document-detail-view/files-collections/files-collections.component.scss
projects/admin/src/app/record/detail-view/document-detail-view/files-collections/files-collections.component.ts
projects/admin/src/app/record/detail-view/document-detail-view/files-collections/upload-files/upload-files.component.html
projects/admin/src/app/record/detail-view/document-detail-view/files-collections/upload-files/upload-files.component.ts
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/service/record-permission.service.ts
projects/admin/src/app/service/resources-files.service.ts
projects/shared/src/lib/component/documents/files/files.component.html
projects/shared/src/lib/component/documents/files/files.component.ts

* Updates primeng dependency.
* Creates a specific upload files components.
* Adds loading wheels.

files: optimizes the files loading time.

---

package-lock.json
projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.component.ts

* Fixes typeahead value deletion.
* Fixes refresh label value on typeahead after insert.
* Updates dependencies.
* Closes rero/rero-ils#3661.

fix(editor): entity typeahead clear value

---

CHANGELOG.md
package-lock.json
package.json
projects/admin/src/assets/rero-ils-ui/admin/i18n/de.json
projects/admin/src/assets/rero-ils-ui/admin/i18n/fr.json

* Also fixes two translations.

release: v17.0.1

---

projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.ts

- Closes https://github.com/rero/rero-ils/issues/3716.

acquisition editor: fix missing initial value in the account select

---

package-lock.json
projects/admin/src/app/circulation/item/item.component.html
projects/admin/src/app/circulation/patron/history/history-log/history-log.component.html
projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.html
projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.html
projects/public-search/src/app/patron-profile/patron-profile-document/patron-profile-document.component.html
projects/public-search/src/app/patron-profile/patron-profile-histories/patron-profile-history/patron-profile-history.component.html

* Displays enumerationAndChronology field as a badge in public and pro patron profile next to document title.
* Closes [#3744](https://github.com/rero/rero-ils/issues/3744).
* Updates vulnerable dependencies.

feat(circulation): enhance enumeration and chronology display

---

projects/shared/src/lib/view/thumbnail/thumbnail.component.ts

Display thumbnail by isbn, if no thumbnail link is available in the electronicLocator field.
* Closes https://github.com/rero/rero-ils/issues/3755.

fix(thumbnail): display by isbn if no link

---

projects/admin/src/app/record/detail-view/entities-detail-view/remote/remote-topic-detail-view/remote-topic-detail-view.component.html

* Adds fields narrower, closeMatch and exactMatch in topic and places entity detailed views.

fix(entities): add fields in pro detailed view

---

package-lock.json
package.json
projects/admin/src/app/app-routing.module.ts
projects/admin/src/app/menu/menu-definition/menu-app.ts
projects/admin/src/app/migration/conversion/record/brief-view/migration-data/migration-data.component.html
projects/admin/src/app/migration/conversion/record/brief-view/migration-data/migration-data.component.ts
projects/admin/src/app/migration/conversion/record/detail-view/migration-data/migration-data.component.html
projects/admin/src/app/migration/conversion/record/detail-view/migration-data/migration-data.component.scss
projects/admin/src/app/migration/conversion/record/detail-view/migration-data/migration-data.component.ts
projects/admin/src/app/migration/conversion/record/detail-view/pipes/highlight-json.pipe.ts
projects/admin/src/app/migration/deduplication/record/brief-view/migration-data-deduplication/migration-data-deduplication.component.html
projects/admin/src/app/migration/deduplication/record/brief-view/migration-data-deduplication/migration-data-deduplication.component.scss
projects/admin/src/app/migration/deduplication/record/brief-view/migration-data-deduplication/migration-data-deduplication.component.ts
projects/admin/src/app/migration/deduplication/record/brief-view/migration-metadata/migration-metadata.component.html
projects/admin/src/app/migration/deduplication/record/brief-view/migration-metadata/migration-metadata.component.scss
projects/admin/src/app/migration/deduplication/record/brief-view/migration-metadata/migration-metadata.component.ts
projects/admin/src/app/migration/deduplication/record/search/migration-search-page.component.ts
projects/admin/src/app/migration/deduplication/record/search/migration-search/migration-search.component.html
projects/admin/src/app/migration/deduplication/record/search/migration-search/migration-search.component.ts
projects/admin/src/app/migration/migration-routing.module.ts
projects/admin/src/app/migration/migration.module.ts
projects/admin/src/app/migration/record/brief-view/migration/migration.component.html
projects/admin/src/app/migration/record/brief-view/migration/migration.component.ts
projects/admin/src/manual_translations.ts
projects/shared/src/lib/util/permissions.ts

The test failed because of:
- depends to: https://github.com/rero/ng-core/pull/643

migrations: create migration module

---

projects/admin/src/app/circulation/patron/loan/circulation-settings/circulation-settings.component.ts
projects/admin/src/app/circulation/patron/loan/loan.component.html
projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html
projects/admin/src/app/migration/deduplication/record/brief-view/migration-data-deduplication/migration-data-deduplication.component.html
projects/admin/src/app/record/brief-view/loans-brief-view/loans-brief-view.component.ts
projects/admin/src/app/record/brief-view/patron-transaction-events-brief-view/patron-transaction-events-brief-view.component.ts
projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.html
projects/admin/src/app/record/detail-view/entities-detail-view/remote/entities-remote-detail-view.component.html
projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.ts
projects/admin/src/app/scss/styles.scss
projects/admin/src/app/utils/roles.ts
projects/admin/src/app/utils/utils.ts
projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loan/patron-profile-loan.component.html
projects/public-search/src/app/pipe/loan-status-badge.pipe.ts
projects/shared/src/lib/component/entities/entity-brief-view/entity-brief-view.component.ts

* Fixes `warn` severity components.
* Forces white text color for secondary tags that are links.

fix(theme): colors

---

projects/admin/src/app/scss/styles.scss

* Linked to https://github.com/rero/ng-core/pull/688

chore(theme): move tag link color to ng-core

---

projects/admin/src/app/acquisition/components/order/order-detail-view/order-detail-view.component.html
projects/admin/src/app/acquisition/components/order/order-detail-view/order-detail-view.component.ts
projects/admin/src/app/acquisition/components/order/order-detail-view/order-lines/order-lines.component.html
projects/admin/src/app/acquisition/components/receipt/receipt-list/receipt-list.component.ts

Once an order has been received, the button must be deactivated. 
Permissions are loaded when this component is displayed.
* Fixes maximum call stack on the place order dialog.

fix(acquisition): disabled button on receipt

---

projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts
projects/public-search/src/app/patron-profile/patron-profile-personal-editor/patron-profile-personal-editor.component.ts

* Displayed the validation errors when the form is submited.

feat: display validation errors on submit

---

projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.html

* adds filter.
* adds menu height enlargement.
__Screen__

style(acquisition): account select menu

---

projects/admin/src/app/circulation/item/item.component.ts

* Moves the loans and other informations based on item in a ngOnChange method.

fix(circulation): fix highlight loans that are late

---

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-header/holding-header.component.ts
projects/admin/src/app/routes/documents-route.ts
projects/admin/src/app/routes/holdings-route.ts
projects/admin/src/app/routes/items-route.ts

* Fixes the retourn of the deleteMessage function for items and documents.
* Fixes assignation of the holdings data signal.

fix: resource delete message

---

projects/admin/src/app/record/editor/formly/primeng/entity-autocomplete/add-entity-local-form/add-entity-local-form.component.ts
projects/admin/src/app/record/editor/formly/primeng/entity-autocomplete/entity-autocomplete.component.ts

* Fixes the loop on open the dialog with showOnFocus is false.
* Closes https://github.com/rero/rero-ils/issues/3842.

fix: fix bad key for local entity genre-form

---

projects/admin/src/app/acquisition/components/order/order-summary/order-summary.component.html
projects/admin/src/app/acquisition/components/vendors/vendor-detail-view/vendor-detail-view.component.html

Display vendor notes and VAT rate in vendor detailed view. 
Display vendor notes and link in order detailed view.
Closes https://github.com/rero/rero-ils/issues/3821.

feat(acquisition): display vendor notes

---

projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.html

fix: missing notification info in circulation history

---

projects/admin/src/app/circulation/patron/pending/pending.component.html

fix(circulation): wrong request disappears when deleted

---

projects/admin/src/app/menu/menu-definition/menu-user.ts
projects/admin/src/app/menu/menu-user/menu-user.component.html

* The signout link is now opened in the same tab.
* Closes rero/rero-ils#3904.

fix(menu): open signout link in a new tab

---

package-lock.json
package.json
projects/public-search/src/app/patron-profile/patron-profile.component.html
projects/public-search/src/app/patron-profile/patron-profile.component.ts

* Adds the patron barcode with code39.
* Hides the fee tag if amount is zero
* Closes rero/rero-ils#3838.

feat: display barcode on public patron profile

---

projects/public-search/src/index.html
projects/search-bar/src/app/app.module.ts
projects/search-bar/src/index.html
projects/shared/src/lib/component/remote-search/remote-search.component.ts

fix(translate): add logic to translate messages

---

projects/admin/src/app/service/record-permission.service.spec.ts
projects/admin/src/app/service/record-permission.service.ts

* Depends on https://github.com/rero/rero-ils/pull/3959.

chore(record): improve messages translation
