.travis.yml, angular.json
* BETTER Disable optimizations on production build to avoid errors when application is loaded in Invenio webpack.
* FIX Deactivate cache on node_modules in Travis configuration, to avoid error on @cospired package on travis tests.
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
=> build: Optimization on build

projects/public-search/src/app/app-routing.module.ts, projects/public-search/src/app/app.module.ts, projects/public-search/src/app/document-brief/document-brief.component.html, projects/public-search/src/app/document-brief/document-brief.component.scss, projects/public-search/src/app/document-brief/document-brief.component.ts, projects/public-search/src/app/person-brief/person-brief.component.html, projects/public-search/src/app/person-brief/person-brief.component.spec.ts, projects/public-search/src/app/person-brief/person-brief.component.ts, projects/public-search/src/app/pipes/bio-informations.pipe.spec.ts, projects/public-search/src/app/pipes/bio-informations.pipe.ts, projects/public-search/src/app/pipes/birth-date.pipe.spec.ts, projects/public-search/src/app/pipes/birth-date.pipe.ts, projects/public-search/src/app/pipes/mef-title.pipe.spec.ts, projects/public-search/src/app/pipes/mef-title.pipe.ts, projects/public-search/src/app/record.service.spec.ts, projects/public-search/src/app/record.service.ts, tsconfig.json
Implements tasks #1061 of US986
* NEW Adds documents and person filters
* NEW Adds detailed display of search results
`cd rero-ils-ui`
`git fetch rero pull/8/head:PR8`
`git checkout PR8`
`npm run build`
`ng serve public-search`
**/!\ rero-ils server must be running**
* Brief view should look like the screenshot below
* Filtering with facets should work
* Clicking on a link should redirect to flask detail view (document title & person name)
=> public-search: complete brief view

projects/admin/src/app/app-routing.module.ts, projects/admin/src/app/record/brief-view/libraries-brief-view.component.ts, projects/admin/src/app/record/record-status.ts
* Enables locations and libraries edit and delete buttons for librarians from external libraries.
* Closes #488
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
- should connect to the `dev` of `rero-ils`
- login as a `librarian: reroilstest+virgile@gmail.com` 
- display available libraries and locations @  http://localhost:4200/records/libraries?size=10&page=1&q=
- you will have edit/delete buttons enabled only for one library and its locations.
- login as a `system_librarian: reroilstest@gmail.com` 
- display available libraries and locations @  http://localhost:4200/records/libraries?size=10&page=1&q=
- you will have edit/delete buttons enabled for all libraries and locations of this organisation
=> record: disable locations buttons for external librarians

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
* NEW Adds default PR and issue template.
To use same the templates than rero-ils (projects standardization)
N/A
=> git: add PR and issue template

projects/public-search/src/app/document-brief/document-brief.component.html, projects/public-search/src/app/document-brief/document-brief.component.spec.ts, projects/public-search/src/app/person-brief/person-brief.component.html, projects/public-search/src/app/person-brief/person-brief.component.spec.ts
* BETTER Repares documents and persons detail links.
Implements task 1184 of US 987
- Clone the PR
- If needed: `npm install`
- `npm run start-public-search-proxy` (needs localhost:5000 to be served in https and login as admin or system librarian)
- Go to public search view
- On mouse hover on documents or persons link, the url should not be Object[Object] anymore but the corresponding url to access detail page on rero-ils.
After cloning this PR:
- `npm pack`
- Go to assets folder of rero-ils instance
- `npm install [path/to/rero-ils-ui.tgz]`
-  Go to public search view
- Click on documents or persons links and check that navigation is successful
=> public-search: repare detail links

projects/public-search/src/app/document-brief/document-brief.component.html, projects/public-search/src/app/person-brief/person-brief.component.html, proxy.conf.json
* Adds proxy rules for documents and persons detail views.
* Adapt html templates accordingly.
To fix links to documents and persons detail views with proxy configuration.
Part of https://github.com/rero/rero-ils-ui/issues/43.
Got to documents and persons brief views and test links.
=> public-search: implement proxy rules for detail views

projects/admin/src/app/record/custom-editor/libraries/library.component.html, projects/admin/src/app/record/custom-editor/libraries/library.component.ts
- Fixes reset of form to remove already data.
- Show list of librairies, edit a library, use back of navigator and add a new library.
=> libraries: Fix form reset creation

projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.html, projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.ts, projects/admin/src/app/record/custom-editor/libraries/library.component.html, projects/admin/src/app/record/custom-editor/libraries/library.component.ts
* Disables POST when clicking on cancel button (prevent default).
Part of https://github.com/rero/rero-ils-ui/issues/43:
29. New circulation policies > Cancel. Got a an error: rero_ils_admin_ui.4706512e.js:2 POST https://ilsdev.test.rero.ch/api/circ_policies/ 400 (BAD REQUEST) on console.log.
Go to the ci-po or the library editor and click on cancel button. There should be no POST any more.
=> editor: fix post when cancelling

package.json, projects/public-search/src/app/app-routing.module.ts
* Enables the search input on all the public-views persons tabs.
- To fix: rero/rero-ils-ui#43. Persons search input visibility.
__Note:__ This depend to a new ng-core release. Needs the following PR: https://github.com/rero/ng-core/pull/76
=> public-search: show the search input for persons

projects/admin/src/app/menu/menu.component.html
* Replaces the link of the logo to go back to public view from admin ui.
To allow users to go to the public view from the admin ui.
`npm run pack`
`cd INVENIO_INSTANCE_PATH/static` (rero-ils)
`npm install path/to/rero-ils-ui//rero-rero-ils-ui-x.x.x.tgz`
Go to localhost:5000/professional
Click on RERO ILS logo
You should go back to Rero Ils home page (not admin home page).
=> ui: link to rero-ils

projects/admin/src/app/menu/menu.component.spec.ts, projects/admin/src/app/menu/menu.component.ts, projects/admin/src/app/translate/i18n/de.json, projects/admin/src/app/translate/i18n/en.json, projects/admin/src/app/translate/i18n/en_US.json, projects/admin/src/app/translate/i18n/fr.json, projects/admin/src/app/translate/i18n/it.json
* Adds entry menu 'switch to public view' to main menu.
- Adds possibility to switch to public interface.
- Check the new entry before "Menu"
=> menu: add 'switch to public view' entry menu

.github/workflows/npmpublish.yml, .npmrc, package.json
* Adds config file to automate publication on Github Package Registry.
To automate testing using published package.
N/A
=> git: publish on github registry

projects/admin/src/app/app.component.ts, projects/admin/src/app/service/organisation.service.spec.ts, projects/admin/src/app/service/organisation.service.ts
- To load organisation record globally
=> service: add new service to load organisation before application start

package-lock.json, package.json, projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/item/item.component.ts, projects/admin/src/app/circulation/items-list/items-list.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.ts
* Sets focus on search input after actions.
* Fixes "hasFees" condition to highlight the checked in items.
https://tree.taiga.io/project/rero21-reroils/task/1272?kanban-status=1224895
Needs https://github.com/rero/ng-core/pull/122
Go to on loan tab of circulation ui.
Do some actions (checkin, checkout, renewal).
Focus should be set on search input after each action.
=> circulation: set focus in input search

projects/admin/src/app/circulation/checkout/checkout.component.html, projects/admin/src/app/circulation/checkout/checkout.component.ts
* Sets focus on search input on init and after actions.
To complete https://tree.taiga.io/project/rero21-reroils/task/1272?kanban-status=1224897
Go to User services ->Circulation: the focus should be set on search input.
=> circulation: set focus on search input

projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
* Improves action on item (hide action if user is not in the same library).
* Fixes remove key available on preUpdateRecord.
- https://github.com/rero/rero-ils-ui/issues/108 point 29
- Check action on page document (section items)
=> item: hide action button on item if the user is not in the same library

projects/admin/src/app/circulation/checkout/checkout.component.ts, projects/admin/src/app/circulation/items.service.ts, projects/admin/src/app/circulation/main-request/main-request.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts
* Adds current library pid as parameter to apply actions.
Corrects 33. of https://github.com/rero/rero-ils-ui/issues/108
Needs https://github.com/rero/rero-ils/pull/749
As a system librarian (for example Astrid):
1. Do a checkin in an other library than the item's home library to put an item in transit.
2. Switch to the destination library.
3. Then scan the barcode. Item should be on shelf.
=> circulation: correct pickup location for actions

projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.ts, projects/admin/src/app/record/detail-view/organisation-detail-view/organisation-detail-view.component.html, projects/admin/src/app/record/detail-view/organisation-detail-view/organisation-detail-view.component.ts, projects/admin/src/app/routes/acquisition-order-lines-route.ts, projects/admin/src/app/routes/acquisition-orders-route.ts, projects/admin/src/app/routes/budgets-route.ts, projects/admin/src/app/routes/circulation-policies-route.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/item-types-route.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/routes/libraries-route.ts, projects/admin/src/app/routes/locations-route.ts, projects/admin/src/app/routes/patron-types-route.ts, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/routes/persons-route.ts, projects/admin/src/app/routes/route-tool.service.ts, projects/admin/src/app/routes/vendors-route.ts, projects/admin/src/app/service/record-permission-message.service.ts, projects/admin/src/app/service/record-permission.service.spec.ts, projects/admin/src/app/service/record-permission.service.ts, projects/public-search/src/app/service/routing-init.service.ts
* Adds new service record permission.
* Fixes organisation active budget switch only with role system_librarian.
- optimize documents views
- dependency: https://github.com/rero/rero-ils/pull/760
- Check document brief view on professional and public view
=> general: implement new service record permission

README.md, projects/admin/src/app/circulation/item/item.component.html
* Displays library name while loan is in transit status
* Fixes #769
Because of https://github.com/rero/rero-ils/issues/769
Cf. issue 769 to check
=> circulation: display library name while transit

projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
* Changes the display in the document detailed view for holdings: the
library name replace the library code.
* Enhances the holdings column alignment in the document detailed view to
be more consistent with the public detailed view.
* Closes #776.
Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
- Should fixes #776
- Go to a document detailed view with holding check the holding location in the card header.
=> document: display library name instead of code

projects/admin/src/app/circulation/item/item.component.html
* Removes location name after 'in transit to' information.
This correction was esked by PO.
N/A
=> circulation: fix in transit to issue

projects/admin/src/app/circulation/checkout/checkout.component.ts, projects/admin/src/app/circulation/main-request/main-request.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts
* Takes into account the library switch for system librarian.
* Closes rero/rero-ils#775.
* Gets the current library from the current logged user instead of the
library switch service.
- Should fix: #775.
- Go to the admin view with a system librarian.
- Go to the requests list, check the displayed list.
- Go to the admin main page, switch the library.
- Go to the requests list => it should be different.
=> circulation: fix requests list with library switch

projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/item-availability/item-availability.component.html, projects/admin/src/app/service/loan.service.ts
* Removes redundant requests information.
* Adds item status.
* Displays requests for items at desk.
* Closes rero/rero-ils#798.
To close this issue: https://github.com/rero/rero-ils/issues/798.
1. Make a checkin of an item with request so that it will become 'at desk'.
2. Then, in the item detailed view:
* Check that the request is displayed.
* Check that `Request: [nb of requests]` is removed
* Check that the status is displayed after the red or green dot after `Availability:`
=> item: fix circulation info in detail view

projects/admin/src/app/circulation/main-request/main-request.component.html, projects/admin/src/app/circulation/main-request/main-request.component.ts
* Sets focus in search input after validation.
* Closes rero/rero-ils#803.
To close rero/rero-ils#803
1. In admin view, got to User services > Requests
2. Validate a request by scanning a barcode in the list.
3. Check that the focus is set to the search input.
=> validate request form: set focus in search input

projects/admin/src/app/scss/styles.scss
* Fixes css file to display small badges on person search view
* Closes #169
- Log in as a librarian.
- Display the professional person search view.
- Badges should be small as expected
before
after
=> styles: display small badges on person search view

projects/admin/src/app/app.module.ts, projects/admin/src/app/error/error-page/error-page.component.ts, projects/admin/src/app/guard/can-update.guard.ts, projects/admin/src/app/routes/acquisition-accounts-route.ts, projects/admin/src/app/routes/acquisition-order-lines-route.ts, projects/admin/src/app/routes/acquisition-orders-route.ts, projects/admin/src/app/routes/budgets-route.ts, projects/admin/src/app/routes/circulation-policies-route.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/item-types-route.ts, projects/admin/src/app/routes/libraries-route.ts, projects/admin/src/app/routes/locations-route.ts, projects/admin/src/app/routes/organisations-route.ts, projects/admin/src/app/routes/patron-types-route.ts, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/routes/route.service.ts, projects/admin/src/app/routes/vendors-route.ts
Add guard for any resources to disallow access to the editor based on user permissions API.
Add basic error page management
* Without this fix, user can access to a resources editor but cannot apply any changes (backend return 403 - forbidden).
* With this fix, user without required privileges cannot access to the resource editor.
* Closes rero/rero-ils#575
- Log as 'reroilstest+virgile@gmail.com'
- Go to professional interface
- Try to access to 'records/libraries/edit/3' --> KO : You should be redirect to homepage
- Try to access to 'records/libraries/edit/4' --> OK
- Try to access other resources for more tests
=> security : protect access to the resource editor

projects/public-search/src/app/document-brief/document-brief.component.html, projects/public-search/src/app/translate/loader/translate-loader.ts
* Display cover image as link if electronic location type is coverImage.
To complete US 1262 https://tree.taiga.io/project/rero21-reroils/us/1262?milestone=257446
Needs https://github.com/rero/rero-ils/pull/848
1. Edit a record to add an electronic location with a type `Covert art` (suggested url: https://d2v9ipibika81v.cloudfront.net/uploads/sites/21/Africa-990x684.jpg)
1. Go to the brief view in public interface
1. Check that the cover image is a working link
=> document: fix cover image in brief view

projects/admin/src/app/routes/locations-route.ts
Several fields needs to be unique by library, such as is_online, pickup name, etc. , when a location is created
or updated. This check did not work since a refactoring.
Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
- Unique validation for is_online and pickup name for locations.
- Create or edit a new location for a library with existing online or pickup location. An error should appears when we try to create a second online location or a location with an existing pickup name.
- a validation should be done in the backend to detect frontend validation failure.
=> editor: fix uniqueness check value for locations

package-lock.json, package.json, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/translate/i18n/de.json, projects/admin/src/app/translate/i18n/en.json, projects/admin/src/app/translate/i18n/en_US.json, projects/admin/src/app/translate/i18n/es.json, projects/admin/src/app/translate/i18n/fr.json, projects/admin/src/app/translate/i18n/it.json
* use ng-core component "read-more" to truncate text and add a "show more" link to abstract.
* linked to ng-core rero/ng-core#138
Co-Authored-by: Benoit Erken <erken.benoit@gmail.com>
- Find a document with a long abstract. You should see the first 100 words, then a "show more" link to display the full content of abstract.
=> document: add "show more" link

projects/admin/src/app/circulation/patron-transaction.service.ts, projects/admin/src/app/circulation/patron-transaction.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html
* Drop-down menu was displayed far away of the action button if a transaction was expanded.
The menu is now displayed just below the transaction action button.
* As transaction event creation method susribed to `currentPatron$` observable, each time this
observer emit content, a dummy transation event was created (with previously registered data event).
This problem is now solved : the affected patron is now get from the parent transaction event.
* CSS buttons regarding UX chart
* Closes rero/rero-ils-ui#209
- Expand a patron transaction to display history. Click on 'action' button for this transaction. The drop-down menu should be display just below the action button.
- Register a payment for a pending transaction (full or partial).
- Navigate to another page using main menu …
=> transactions: bug fixing

projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html, projects/admin/src/app/record/detail-view/library-detail-view/location/location.component.html, projects/admin/src/app/record/detail-view/library-detail-view/location/location.component.ts
When you display a library detail, locations action buttons are displayed even if
current logged user doesn't have permissions to update the library.
This PR fixes this problem.
Ca-authored-by: Renaud Michotte <renaud.michotte@gmail.com>
- Login as Jean (Librarian)
- Display the detail of library 1 : `~/records/libraries/detail/1`
- No actions should be available for any locations
- Display the detail of Jean's library : `~/records/libraries/detail/2`
- You should view the "add", "delete" and "edit" action buttons for locations
=> locations: hide action buttons depending of parent permissions

projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.spec.ts, projects/admin/src/app/routes/organisations-route.ts, projects/admin/src/app/routes/persons-route.ts, projects/admin/src/app/service/main-title.service.spec.ts, projects/admin/src/app/service/main-title.service.ts, projects/public-search/src/app/service/routing-init.service.ts
* Adapts the configuration for the search views that disables administrative functionalities to be compatible with the new ng-core version. This removes all professional buttons from these search views.
- To fix admin button on the public, organisation and person search views.
- Run the public view server and go to the public search views. The add button should not be present.
=> search view: hide the add button for public views

projects/admin/src/app/circulation/circulation.module.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event/patron-transaction-event.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/default-transaction/default-transaction.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/default-transaction/default-transaction.component.spec.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/default-transaction/default-transaction.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.spec.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.spec.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.spec.ts
When you expand a transaction to display detail, we try to display informations about a document and an item.
These metadata are only sense for a 'overdue' transaction.
This PR check the patron transaction type to display information depending of it
Linked to https://github.com/rero/rero-ils/pull/865 and https://github.com/rero/rero-ils/pull/868
=> transactions: fix patron transaction detail display

package-lock.json, package.json, projects/admin/src/app/frontpage/frontpage-board/frontpage-board.component.html, projects/admin/src/app/menu/menu.component.html, projects/admin/src/app/menu/menu.component.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/route-tool.service.ts, projects/admin/src/app/service/menu.service.ts, projects/public-search/src/app/service/routing-init.service.ts
* Fixes display of organisation facet in dcoument brief view.
* Modifies links to documents brief view to include current organisation as a default parameter.
* Closes #140.
* Removes useless code.
https://tree.taiga.io/project/rero21-reroils/task/1377?kanban-status=1224895
Needs https://github.com/rero/rero-ils/pull/852 and last version of ng-core.
1. Go to documents brief view
1. You should have an `organisation` facet in global view
1. You should have a `library` facet in organisation views.
1. Go to documents brief view
1. The results should be filtered by current organisation by default (test with different users).
1. You should have a hierarchical facet (`organisation` …
=> document: filter results by org in admin view

projects/admin/src/app/interceptor/no-cache-header.interceptor.ts, projects/admin/src/app/menu/menu.component.ts, projects/admin/src/app/record/editor/ref/ref.component.ts, projects/admin/src/app/routes/acquisition-accounts-route.ts, projects/admin/src/app/routes/acquisition-orders-route.ts, projects/admin/src/app/routes/budgets-route.ts, projects/admin/src/app/routes/circulation-policies-route.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/item-types-route.ts, projects/admin/src/app/routes/libraries-route.ts, projects/admin/src/app/routes/patron-types-route.ts, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/routes/persons-route.ts, projects/admin/src/app/routes/vendors-route.ts, projects/public-search/src/app/search-bar/search-bar.component.ts, projects/public-search/src/app/service/routing-init.service.ts
For search boxes, the AND operator should be applied by default and it
should be robust to the query syntax errors.
- Implements: https://tree.taiga.io/project/rero21-reroils/us/1440
* rero-ils: https://github.com/rero/rero-ils/pull/973
- Enter several queries to the public view search box. Check that the AND operator is used by default. Test several queries with parameters that causes query syntax errors.
__Note__: see (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-syntax) for the supported syntax documentation.
=> search: add simple params for the backend calls

projects/admin/src/app/menu/menu.component.ts, projects/admin/src/app/pipe/bio-informations.pipe.ts, projects/admin/src/app/pipe/birth-date.pipe.ts, projects/admin/src/app/pipe/mef-title.pipe.ts, projects/admin/src/app/record/detail-view/person-detail-view/person-detail-view.component.html, projects/admin/src/app/record/editor/ref/ref.component.ts, projects/admin/src/app/record/editor/remote-autocomplete/remote-autocomplete.component.ts, projects/public-search/src/app/pipes/bio-informations.pipe.ts, projects/public-search/src/app/pipes/birth-date.pipe.ts, projects/public-search/src/app/pipes/mef-title.pipe.ts, projects/public-search/src/app/search-bar/search-bar.component.ts
* Links documents to the source authority file, such as GND or IdRef,
through the MEF server, instead of the MEF clusterized record. This
is needed to provide a stable link to the authority.
My PR depends on the following `rero-ils`'s PR(s):
* rero/rero-ils#972
- https://tree.taiga.io/project/rero21-reroils/task/1464
- Try to edit an document and add an person
=> editor: link persons to source instead of MEF

.github/ISSUE_TEMPLATE.md
This commit aims to improve the issue template to avoid opening new issues in
this project instead of the RERO ILS project. It also adds a `triage` label by
default to new issues, thus facilitating the management of new issues.
Just read the commit changes.
=> documentation: improve issue template

projects/admin/src/app/record/editor/remote-autocomplete/remote-autocomplete.component.ts
* Fixes display of wrong dates for autocomplete in form editor.
The function with the problem of caculation the dates for authors
was replaced by using `authorized_access_point_representing_a_person`.
The function was handling the dates in the form like `19..` wrongly.
* closes rero/rero-ils#1038
- https://github.com/rero/rero-ils/issues/1038
- In the documents editor add an author and verify correct dates.
=> autocomplete: fix author wrong date

projects/admin/src/app/record/detail-view/document-detail-view/holding-item/holding-item.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
Adapts the item detail view to display notes related to an item.
https://tree.taiga.io/project/rero21-reroils/us/1352?milestone=266303
use https://github.com/rero/rero-ils/pull/1026 (backend) bootstrap + setup
- Log as a librarian
- Edit an item to add a note a each type
- Display the item detail view
=> items: display items notes

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/item/item.component.ts, projects/admin/src/app/circulation/items.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/scss/styles.scss, projects/admin/src/app/service/items.service.ts
When circulation operations are done, if item contains the corresponding
circulation note, this note will be displayed as a permanent toastr
message.
* refactoring item circulation collapsed informations design.
* adds postprocessRecord behavior to avoid empty notes array on item.
Co-authored-by : Renaud Michotte <renaud.michotte@gmail.com>
https://tree.taiga.io/project/rero21-reroils/us/1352?milestone=266303
(backend) https://github.com/rero/rero-ils/pull/1026
- Identify some items with checkin/checkout notes OR add checkin/checkout notes for some circulating items
- Do some checkin/checkout operation on these items. 
- If a checkin/checkout notes are defined on an item, then a permanent toastr message should be display.
=> circulation: display circulation notes automatically.

projects/admin/src/app/app.module.ts, projects/admin/src/app/pipe/notes-format.pipe.spec.ts, projects/admin/src/app/pipe/notes-format.pipe.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
* Creates a pipe to display the field "notes".
* Corrects detail view accordingly.
To adapt the UI for the correction of the edition of a document with notes.
* https://github.com/rero/rero-ils/pull/1062
Check the detail view of documents with notes.
=> document: adapt display of field "notes"

projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/routes/route-tool.service.ts, projects/admin/src/app/service/record-permission.service.ts
This commit restricts the role management for patrons using the role
management API. Depending of the API result, some roles could be
disabled into the role field.
- Closes rero/rero-ils#930
Co-authored_by: Renaud Michotte <renaud.michotte@gmail.com>
https://tree.taiga.io/project/rero21-reroils/task/1523?kanban-status=1224894
* rero/rero-ils#1043
- Logged as a `system_librarian`
- Go into the professional interface and try to edit a patron
- A system_librarian should be able to manage all roles, no role should be disabled.
- Logged as a `librarian`
- Go into the professional interface and try to edit a patron
- The `system_librarian` role should be displayed but disabled.
=> authorization: limit roles management using API

.travis.yml, README.md, package-lock.json, package.json
To update Node version from 10 to 12.
If you **already have** rero-ils-ui directory:
```bash
cd rero-ils-ui
node --version # and keep the version, for example 10.16.3
nvm install lts/erbium --reinstall-packages-from=10.16.3 # replace here the version 10.16.3 by yours
nvm uninstall 10.16.3
npm i
npm ci
ng --version # to check all is right for you
```
You should obtain something like:
```bash
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/
Angular CLI: 8.3.28
Node: 12.18.2
OS: linux x64 …
```
=> package: upgrade to NodeJS 12

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
Implements new item field 'second_call_number' in professional views.
* Adapts holding-item brief view.
* Adapts item detail view to add second call number field.
https://tree.taiga.io/project/rero21-reroils/task/1577
* rero/rero-ils#1082
- Go to the professional view.
- Create (or edit) an item
- Add a second call number.
- Check if the second call number appears in item detail view.
=> items: display second call number field.

package-lock.json, package.json, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
Limits the title length to 150 characters into the document detail view.
If the title is truncated, then add a 'show more'/'show less' link.
* Closes rero/rero-ils#880
=> document: limit title length into document view

projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/service/items.service.ts
New RERO circulation backend adds more parameter for actions.
For checkout action, `transaction_user_pid` is missing.
* Adds transaction_user_pid to data for a checkout
Because of: https://tree.taiga.io/project/rero21-reroils/task/1565
Do a checkout on an item, check that all is OK.
=> circulation: adapt UI for checkout

projects/admin/src/app/frontpage/frontpage-board/frontpage-board.component.html, projects/admin/src/app/frontpage/frontpage-board/frontpage-board.component.ts, projects/admin/src/app/menu/menu.component.ts, projects/admin/src/app/service/menu.service.ts
In Cypress it's difficult to choose a specific item in the menu if you
don't know in which language you are. Each element can be in French,
English, etc.
To facilitate this work we can add `id=` on each element on the menu.
With a specific word. This way you don't need to know in which language
you are.
* Adds Id on all menus ('My Account' menu, languages menu, help menu,
logout, etc.) for testing purposes.
My PR depends on `ng-core/dev#`.
```
* clone ng-core
* do `npm i && npm ci && npm run pack`
* clone this repository (rero-ils-ui)
* do `npm i && npm i ../ng-core/rero-ng-core-0.5.0.tgz`
* launch rero-ils server `cd rero-ils && poetry run server`
* launch rero-ils-ui: `cd …
```
=> ui: better way to select menu items by Cypress

projects/admin/src/app/frontpage/frontpage-board/frontpage-board.component.html, projects/admin/src/app/frontpage/frontpage-board/frontpage-board.component.ts, projects/admin/src/app/pipe/id-attribute.pipe.spec.ts, projects/admin/src/app/pipe/id-attribute.pipe.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/shared/shared-pipes.module.ts, projects/public-search/src/app/person-brief/person-brief.component.spec.ts
Cypress needs to use `id=` attributes in HTML tags to target elements.
At the moment a getId() method is used in each component. But the need
is global. It's probably better to use a Pipe element (from Angular) to
format `id=` attributes content.
* Adds a new idAttribute Pipe component in Angular application
* Changes document detail view to:
* add `id=` on barcode link
* add `id=` on deletion button link
To improve way we generates `id=` attributes in professional view interface.
Just start a rero-ils instance on port 5000 (Cf. https://localhost:5000).
Then launch `npm run start-admin-proxy`, then go to https://localhost:4200 and check with your developer debug toolbar (in your browser) that main menu have `id=help-menu` (for help menu …
=> ui: replace getId() by idAttribute Pipe

projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.html, projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.ts
* Changes the sequence of editor initalization to avoid concurency
problem with the JSONSchema loading.
My PR depends on the following PR(s):
* https://github.com/rero/ng-core/pull/223
=> document editor: fix bnf import

projects/admin/src/app/app.module.ts, projects/admin/src/app/frontpage/frontpage.component.html, projects/admin/src/app/frontpage/frontpage.component.ts, projects/admin/src/app/menu/menu.component.ts, projects/admin/src/app/record/brief-view/items-brief-view/items-brief-view.component.html, projects/admin/src/app/record/brief-view/items-brief-view/items-brief-view.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/service/items.service.ts, projects/admin/src/app/service/menu.service.ts
This part implements views to process an inventory list for items.
* Renames 'Admin and monitoring' menu entry to 'Admin'
* Adds 'Reports and monitoring' entry to main menu.
* Adds inventory brief view component to display item.
* Adds route configuration.
* Adapts frontpage to center content.
https://tree.taiga.io/project/rero21-reroils/task/1600
* rero/rero-ils#1091
=> reports: implement inventory list for items

package-lock.json, package.json
* Fixes holding type serial detection which make impossible the holding
serials create. This was due to the introduction of the document
issuance field.
* Uses ngx formly 5.9.
* Renames 'Admin and monitoring' menu entry to 'Admin'
* Adds 'Reports and monitoring' entry to main menu.
* Adds items brief view component to display item in results list.
* Adds route configuration.
* Adapts frontpage to center content.
* Adapts holding-item brief views.
* Adapts item detail view to add second call number field.
* Adds new fields: issuance, series statement, partOf.
* Removes partOf field from brief view.
* Corrects notes display.
* Updates ngx-formly to v5.9.1.
* Changes the sequence of editor initalization to avoid concurency
problem with the JSONSchema loading.
* Adds a new idAttribute Pipe …
=> release: v0.4.0

projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/items-list/items-list.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html
* Adds `id=` HTML attributes on each item on item list (from
holding/serials)
* Adds `id=` HTML attributes on item request button
* Adds `id=` HTML attributes on item edit button
* Adds `id=` HTML attributes on item delete button
* Adds `id=` HTML attributes on `Show more` link on serials/holding
=> ui: add `id=` HTML attributes on item lists

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/service/items.service.ts
This commit fixes some problems detected after the test of new invenio
circulation module in the backend :
* adds a toastr message when no circulation are done on checkin page.
* displays a message when no notification process date exists fr an
item into the checkin/checkout component
https://github.com/rero/rero-ils/tree/US1394-invenio-circulation
=> circulation: fix problems on circulation module

projects/admin/src/app/circulation/item/item.component.html
The renewal badges should not be displayed when a checkin action in done
on the corresponding item. This commit change the behavior of this badge
to be conditional depending if a 'checkin' action is done on the item.
Closes rero/rero-ils#797
Test procedure describes a https://github.com/rero/rero-ils/issues/797
=> item: conditional renewal badges.

projects/admin/src/app/circulation/item/item.component.html
* Replaces the item pickup location name by the item library name in
collapsed details.
This is the issue nb 4 reported by Nicolas during the tests of new circulation ui:
Scenario C: after CHECKIN_3.2.2.2
When I expand the loan in the checkin interface, the location displayed is the pickup location name (see screenshot).
Expected: the item location should be displayed, as for a standard checkin.
* rero/rero-ils US1394 branch
Login as (system) librarian and go to a patron circulation view.
Uncollapse the details in the items of the list and check the location name.
Should be:
`Location:        library name: item location name`
=> circulation: replace pickup location name by library name

projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts, projects/admin/src/app/service/loan.service.ts
* Fixes the change of request pickup location.
To resolve the bug reported.
* rero/rero-ils US1394 branch
Try to change the pickup location of a request in item detailed view.
=> request: fix update of request pickup location

projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts
* Updates permissions to allow to cancel a request and to update request pickup location when an item is in transit for pickup.
Task 1685 of US 1665
* https://github.com/rero/rero-ils/pull/1174
Try to change the request pickup location of an item that is in transit for pickup.
=> circulation: update request permissions

projects/admin/src/app/class/items.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/routes/holdings-route.ts, projects/admin/src/app/routes/items-route.ts
This commit updates the item detail view to display a mention about new
acquisition. This commit also fixes a problem when 'location' select
field was populated to avoid a circular stringify error.
Co-Auhtored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
=> item: update UI to manage 'new_acquisition' field

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/class/items.ts
When an item is checked-in and goes in transit, add a toastr message to
informs user about this spec.
Co-Authored-by: Renaud Michote <renaud.michotte@gmail.com>
- Checkin an item to goes in transit. Use the SCENARIO B
=> circulation : toastr message when item goes in transit

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts
* Fixes patron info in loan view: it couldn't be removed in order to go
to checkin view (displayPatronMode is setted to false in checkin view
and not updated when going to loan view).
* Fixes the display of a flash error message saying 'patron is
undefined' when going to loan view after a checkin in checkin view.
Task 1693 of US1665
N/A
Do a checkin or a receive in checkin view (User services > Circulation).
Then type a patron barcode to go to patron loan view. A red button should be displayed in order to remove patron info and go back to checkin view.
No error flash message saying `patron is undefined` should be displayed.
=> circulation: fix patron info in loan view

projects/admin/src/app/routes/documents-route.ts
The `_draft` property is used to specify that the document is a draft and
should not be validated before saving into back-end. When a user click
on the document editor "save" button, this property shouldn't be present into the record, so the record can be validated by the backend API. 
This property could be set using the "save as template" functionality.
Should be tested with https://github.com/rero/rero-ils/tree/US1546-marcxml-support
* Find a document with `_draft` property into backend
* go to the document editor for this pid
* save the document
* check the backend document data for this pid ; `_draft` key should be removed
=> document: clear '_draft' key when saving document.

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts
The request document button was only available for the current library
items. This commit updates this behavior ; now all items of the current
logged user application can be requested.
Closes rero/rero-ils#927
- Try to request a document for another library than the current logged user library (but in the same organisation)
=> circulation: allow request for organisation items

projects/admin/src/app/app.module.ts, projects/admin/src/app/class/documents-typeahead.ts, projects/admin/src/app/service/ui-remote-typeahead.service.spec.ts, projects/admin/src/app/service/ui-remote-typeahead.service.ts
Extends remote typeahead component to be able to search list
of suggestion of documents.
* Adds a new class for custom documents typeahead.
=> editor: define custom documents typeahead type

projects/admin/src/app/app.module.ts, projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/holdings-route.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/routes/templates-route.ts, projects/admin/src/app/service/editor.service.ts
* This commit introduces a new modal widget component able to list
templates (filtered by resource type) and send, to the parent container
(mainly editor), associated data. The parent container has
responsibility to manage the data as it wants (fill the form, transform
data, ...)
* Adapts `editorSettings` for several resources.
* https://github.com/rero/rero-ils/pull/1199
* https://github.com/rero/ng-core/pull/246
- Try to create a new document using 'load template' button
=> template: adapt routes for templates

projects/public-search/src/app/document-brief/document-brief.component.html, projects/public-search/src/app/document-brief/document-brief.component.ts
Fixes wrong link to MEF person in the document brief view of the public interface.
*  Adds function to get MEF Person link.
=> search: fix contribution link

projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts
* Corrects transaction location sent to backend to cancel a request.
Cancel a request was failing due to a wrong transaction location pid.
N/A
=> request: fix cancel request

projects/admin/src/app/routes/documents-route.ts, projects/public-search/src/app/manual_translations.ts, projects/public-search/src/app/service/routing-init.service.ts
The current language used to retrieve only nested i18n aggregation.
* Renames contribution facet to author.
* rero/rero-ils#1195
- Check author facet in public search and admin search
=> document: improve translated aggregations

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts
On the professional interface, when displaying the detailed view of a
journal with lots of issues, a show more… link is collapsed by default
and the number of hidden issues is displayed. This messages was not well
formed for translations. This commit fix this problem.
Closes rero/rero-ils#1223
=> translations: fix show more item link

projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.scss, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/service/editor.service.spec.ts, projects/admin/src/app/service/editor.service.ts
This feature allows you to duplicate a document by clicking on the duplicate button in the detailed view.
- Select a document and click "duplicate" button.
- Modify data and save.
=> document: allow record duplication

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.html
If a document is a serial or electronic, all linked holdings was force
to be displayed as serial/electronic. This PR fix this problem ; despite
of the document metadata, the holding is display depending of the
holding_type metadata from the holding.
Closes rero/rero-ils#1252
https://github.com/rero/rero-ils/issues/1252
- display "serial/electronic" documents detailed view and check holdings display.
=> holding: fix holding display problem.

package-lock.json, package.json, projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.spec.ts, projects/admin/src/app/record/custom-editor/holding-editor/holding-editor.component.spec.ts.disabled, projects/admin/src/app/routes/route-tool.service.ts, projects/admin/src/app/routes/templates-route.ts, projects/admin/src/app/service/record-permission.service.ts
This commit implements the 'canUse' permission function allowing to use
a template as a skeleton for a new resource.
* https://github.com/rero/ng-core/pull/250
- List template ; for each one, a new button should be available to use it in the related editor.
- Into a template detail page : a new button "Use" is also available
=> templates: add 'use it' functionality

projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/service/menu.service.ts
* Replaces 'patron' with 'user' in menu and users list.
Task 1755 of US 1659
* N/A
Go to professional view and check menu and users list.
=> patron: rename as user

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/patron/card/card.component.html, projects/admin/src/app/circulation/patron/card/card.component.ts, projects/admin/src/app/circulation/patron/main/main.component.html, projects/admin/src/app/circulation/patron/profile/profile.component.html, projects/admin/src/app/circulation/patron/profile/profile.component.ts, projects/admin/src/app/class/items.ts, projects/admin/src/app/class/user.ts, projects/admin/src/app/menu/menu.component.ts, projects/admin/src/app/pipe/patron-blocked-message.pipe.ts, projects/admin/src/app/record/brief-view/patrons-brief-view.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.html, projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html, projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.ts, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/service/menu.service.ts, projects/admin/src/app/service/user.service.ts
=> Maj us1590 user resource

package-lock.json, projects/admin/src/app/app.module.ts, projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html, projects/admin/src/app/record/custom-editor/holding-editor/holding-editor.component.spec.ts.disabled, projects/admin/src/app/record/document-record-search/document-record-search.component.html, projects/admin/src/app/record/document-record-search/document-record-search.component.spec.ts, projects/admin/src/app/record/document-record-search/document-record-search.component.ts, projects/admin/src/app/routes/documents-route.ts, projects/public-search/src/app/app.module.ts, projects/public-search/src/app/document-record-search/document-record-search.component.html, projects/public-search/src/app/document-record-search/document-record-search.component.spec.ts, projects/public-search/src/app/document-record-search/document-record-search.component.ts, projects/public-search/src/app/routes/base-route.ts, projects/public-search/src/app/routes/collections-route.service.ts, projects/public-search/src/app/routes/documents-route.service.ts, projects/public-search/src/app/routes/route-factory.service.ts
* Adds a link to extend the search to all documents (public and admin).
* Adds a control on document brief view if the document exists.
* Changes boolean to new observable on adminMode configuration.
* Improves dynamic routing system.
* rero/ng-core#278
- Search for a term that does not exist in the results (Ex: Cheval)
- See if the extend link is present
- Click on the link and see if the url has changed and if you have results.
=> search list: add extend link when no result has been found

projects/admin/src/app/class/items.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-in-collection/holding-item-in-collection.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/service/holdings.service.ts
Updates code to reflect new item note categories (binding, provenance,
condition, patrimonial, acquisition). Adds an icon related to each
note in the item detail view to know if the note is public or not.
https://github.com/rero/rero-ils/pull/1310
- edit the item to add multiples notes with html inside and new_line.
- see result in item detail view
=> item: add item note categories

projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.html, projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.ts, projects/admin/src/app/circulation/patron/pickup/pickup.component.html
When a request is available for pickup, the location name was the short
name. This PR corrects this problem: now the label display is the
'pickup_name' field from location.
Closes rero/rero-ils#1300
Before
After
=> circulation: display pickup location name in patron profile

projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts
* Updates 'cancel request' permissions to allow the cancellation of an
item 'at desk'.
* Adds a method to update the item detailed view after a cancel request.
* Adds a flash message to inform the user about the item status.
* Moves 'cancel' and 'update' logic from the item-transaction component (list item) to
the item-transactions (list) component for a better understanding and to clean the code.
* Closes rero/rero-ils#1293.
Task 1784 of US1762 Issue fixing
N/A
See issue description.
=> request: allow cancellation when item is at desk

projects/admin/src/app/circulation/checkin/checkin.component.html, projects/admin/src/app/circulation/patron/card/card.component.html, projects/admin/src/app/circulation/patron/card/card.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/circulation/patron/main/main.component.html, projects/admin/src/app/circulation/patron/main/main.component.ts, projects/admin/src/app/class/user.ts, projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html, projects/admin/src/app/record/detail-view/template-detail-view/template-detail-view.component.html, projects/admin/src/app/service/patron.service.ts, projects/admin/src/app/service/user.service.ts, projects/admin/src/app/utils/utils.ts
The message return by the backend when a user is blocked has changed.
This commit adapts the UI to this change and display the error message
returned by the backend directly.
This commit also adds counter on tabs of the patron circulation detail
page. Available counter are for checkin/checkout, pickup and pending
tabs.
Small correction on the template detail view.
Closes rero/rero-ils#1278
Closes rero/rero-ils#1281
* ng-core 0.13 (run `npm ci` the new version of ng-core should be installed)
* https://github.com/rero/rero-ils/tree/US1643-borrow-limits
* Use the professional interface to block a user. 
* Go in the circulation interface for this patron ; you should see this message in red (see screenshot)
* Unblock the patron
* Define …
=> circulation infos refactoring 

projects/admin/src/app/circulation/checkin/checkin.component.html, projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/patron/card/card.component.html, projects/admin/src/app/circulation/patron/card/card.component.scss, projects/admin/src/app/circulation/patron/card/card.component.ts
Depending where the card component is sued, the link on the patron name
should be different :
* on the checkin interface : point to the patron circulation view
* on the patron circulation view : point to the patron detail view
Closes rero/rero-ils#1378
=> circulation: improve displayed patron data

projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event-form/patron-transaction-event-form.component.ts
Updates the transaction payment form to allow only 2 decimals.
=> transactions: limit pay with 2 decimals

projects/admin/src/app/record/custom-editor/holding-editor/holding-editor.component.ts
* Reduces the number of http calls when the form is modified.
- To make the holding editor more responsive.
- Go to the holding editor for the serials. This prediction preview should not make too much backend http calls.
=> holdings: improve editor preview rendering

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/circulation.module.ts, projects/admin/src/app/circulation/patron/change-password-form/change-password-form.component.html, projects/admin/src/app/circulation/patron/change-password-form/change-password-form.component.spec.ts, projects/admin/src/app/circulation/patron/change-password-form/change-password-form.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event-form/patron-transaction-event-form.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html, projects/admin/src/app/circulation/patron/profile/profile.component.html, projects/admin/src/app/circulation/patron/profile/profile.component.ts, projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/service/user.service.ts
* Adds missing license in some files.
* Fixes some spelling.
* Adds a button in the circulation patron profile to update the
password.
* Adds a edit button in the circulation patron profile.
- Implements https://tree.taiga.io/project/rero21-reroils/us/1659
* https://github.com/rero/rero-ils-ui/pull/411
- Go to a circulation user profile and try to change the password.
- Log with the patron and test the new password.
- Log with a librarian, try to change the password of a system librarian with a patron role. You should not be able to do it!
=> patron: allows librarians to update user password

projects/admin/src/app/app.module.ts, projects/admin/src/app/class/items.ts, projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.html, projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/routes/issues-route.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/routes/route.service.ts, projects/admin/src/app/service/holdings.service.ts, projects/admin/src/app/service/menu.service.ts
A new item "Late issues" in the Acquisition menu is added
to display late and claimed issues filtered by library and
location and issue status.
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
https://tree.taiga.io/project/rero21-reroils/us/1544?milestone=275632
* https://github.com/rero/rero-ils/pull/1415
* https://github.com/rero/ng-core/pull/299
Full information about the implementation is documented here https://tree.taiga.io/project/rero21-reroils/us/1544?milestone=275632
* login to your organisation as system_librarian (either Irma or Astrid)
* Go to the `Acquisition Menu` and select the item `Late issues`
* you will have a list of `claimed` and `late` issues.
* you can filter by library, location, vendor and issue status
* you …
=> serials: new service to display late/claimed issues

projects/admin/src/app/circulation/main-request/main-request.component.ts, projects/admin/src/app/circulation/main-request/requested-items-list/requested-items-list.component.html, projects/admin/src/app/circulation/patron/card/card.component.html
* At first load of the main request component all requests are marked as
new request. Fixes this problem : the requests are now displayed as
normal request (no callout around the request box)
* the patron notes are displayed on small box. Fixes this problem adding
an automatic max box width for the note box.
=> bugs: fix several bugs into UI

projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
Fix the display note content. The item detail view shows all item notes
type but no content was displayed.
- display the item detail view for any item with some notes.
- check if notes content are displayed
=> items: fix display notes content.

projects/admin/src/app/circulation/patron-transaction.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event/patron-transaction-event.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event/patron-transaction-event.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.ts, projects/admin/src/app/class/documents-typeahead.ts
* Translates labels in patron circulation > fees tab.
* Closes rero/rero-ils#1371.
To close mentioned issue(s)
N/A
See issue description.
=> ui: fix translation issues

projects/admin/src/app/routes/patrons-route.ts
In the patron editor, if the current edited patron doesn't have the
'patron' role, we need to remove all informations linked to this
profile (mainly the default expiration_date set in
`preprocessRecordEditor` function).
=> editor: fix patron editor

projects/admin/src/app/circulation/checkin/checkin.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.html, projects/admin/src/app/circulation/patron/main/main.component.html, projects/admin/src/app/service/menu.service.ts
* Renames checkin/checkout tab into 'on loan'.
* Renames 'Circulation' menu into 'Checkout/checkin'.
* Improves a placeholder.
* Adds a title to the checkin view.
* Closes rero/rero-ils#1280.
Thoses changes were asked by pilot libraries to make the interface
clearer.
=> circulation: improve labels

projects/admin/src/app/class/items.ts, projects/admin/src/app/routes/items-route.ts
For new issue item, the acquisition date should not be set by default to
the current date. This field must be empty (this change automatically
disable the 'new acquisition' toggle in the item editor).
Closes rero/rero-ils#1449
- Try to create a new 'standard' item --> the new acquisition toggle should be enable.
- Try to create a new 'issue' item (irregular item or long received predicted issue) --> the new acquisition toggle should be disabled.
=> items: make acquisition default date optional

projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction/overdue-transaction.component.ts, projects/admin/src/app/circulation/patron/pickup/pickup.component.ts, projects/admin/src/app/menu/menu.component.spec.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/widgets/frontpage/frontpage.component.spec.ts
Closes rero/rero-ils#1487
Fixes item link displayed on an overdue transaction. The link used the
`loan.pid` instead of `loan.item.pid`.
Closes rero/rero-ils#1488
Correct some translation problems n the detail document view (in the
description tab).
Close rero/rero-ils#1482
Updates the pickup counter when a 'ready to pickup' item is checked out.
=> general: fix several UI issues.

projects/admin/src/app/circulation/patron/history/history.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/circulation/patron/main/main.component.html, projects/admin/src/app/circulation/patron/main/main.component.ts, projects/admin/src/app/service/patron.service.ts
Adds a counter for the patron circulation history tab. This counter is
dynamically update when a checkin operation is done for the patron.
Closes rero/rero-ils#1515
=> circulation: adds a counter on history tab

projects/admin/src/app/app.module.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-in-collection/holding-item-in-collection.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-in-collection/holding-item-in-collection.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-note/holding-item-note.component.spec.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-note/holding-item-note.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html
Replaces the sticky icon by the note content into the document detailed
view.
Closes rero/rero-ils#1501
=> item: display item notes

projects/admin/src/app/widgets/frontpage/frontpage-board/frontpage-board.component.html
Fixes the display of dashboard widget. All dashboard widget entries were
rounded with an extra border. This commit fixes this behavior but keeps
the separation between each link sections of the same widget.
=> Widget: fix dashboard widget

projects/admin/src/app/record/custom-editor/document-editor/document-editor.component.ts
When an harvested document is duplicate, then the `harvested` flag must
be removed.
Closes rero/rero-ils#1542
=> document: fix duplicate harvested document

.gitignore, projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy-form.service.ts, projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy.ts, projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.html, projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.scss, projects/admin/src/app/record/custom-editor/circulation-settings/circulation-policy/circulation-policy.component.ts, projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.html
* Moves buttons to the top to harmonize with other editors.
* Corrects editor validation.
* Improves editor appearance.
* Closes rero/rero-ils#1365.
* Closes rero/rero-ils#1305.
* Adds id HTML attribute to circulation policy detail view for Cypress
tests and improve its appearance.
* Removes useless code.
* Closes rero/rero-ils#1363.
This is part of US1759
https://github.com/rero/rero-ils/pull/1477
Login as a librarian and check the cipo editor.
Create a cipo with checkout duration = 0 days.
Create an item linked to this cipo.
Try to check it out, and then check it in for a patron that is also linked to this cipo.
=> circulation policy: improve editor

projects/admin/src/app/circulation/patron/main/main.component.html, projects/admin/src/app/circulation/patron/profile/profile.component.html, projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html, projects/shared/src/lib/class/user.ts
In the patron detailed view, the new field
keep_history is displayed.
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
https://tree.taiga.io/project/rero21-reroils/us/1422?milestone=277700
https://github.com/rero/invenio-userprofiles/pull/2
https://github.com/rero/rero-ils/pull/1512
Case 1:
- Login as system_librarian.
- Find any patron with completed circ transactions
- Edit the patron record and disable the `keep_history` field if enabled. (Note: if disabled already, then enable it and then disable it).
- Go back the patron page, you will not find the the circ history. they are anonymized (not visible anymore)
Case 2:
- Login as patron (simonetta or other).
- Make sure you have completed circ transactions in the history tab.
- Take a look at the `Personal data` tab (re-organiszed) and the …
=> users: display keep_history for patron

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.scss, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts, projects/admin/src/app/scss/styles.scss
* Replaces the 'duplicate' button just near other buttons.
* Update the style of duplicate button to use outline.
* Gives more spaces around abstract for a better readability.
* Gives more horizontal spaces to basic informations (useful for
document with long abstract).
Adds a specific style for item list. This style display a dotted border
between the item label and the item value.
=> document: improve document detail view

projects/admin/src/manual_translations.ts
When an holding has a lot of related items, the interface display the 5
first ones followed by a "show more" link containing a counter
corresponding to the hidden resources number. This message is now
extracted for translation.
Closes rero/rero-ils#1400
Can noly be tested after weblate translation porcess done and integration.
=> translation: fix show more resources link

projects/admin/src/app/routes/ill-requests-route.ts
* Fixes errors when the search results of the ILL requests are displayed.
=> search: fix ILL request search results errors

projects/admin/src/app/circulation/item/item.component.ts
Adds a sort criteria when we search about notifications linked to an
item. The sort criteria used is 'mostrecent'.
Closes rero/rero-ils#1549
https://github.com/rero/rero-ils/pull/1553
=> item: sort notifications by chronological order

projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html, projects/admin/src/app/record/detail-view/local-field/local-field.component.html
The 'add irregular issue' button had bad alignment with other page
components. This button is now on a specific row and right aligned.
The 'add local field' button is also right aligned.
Closes rero/rero-ils#1562
=> holdings: fix holding detail page display

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html
* Puts back some id html attribute that were removed. There are needed
to keep Cypress tests working.
=> merge v1.0.0 branch

projects/admin/src/app/menu/service/menu-user-services.service.ts
The label "patron types" is present twice in the admin menus ; indeed
the first one corresponding to 'item types' result list.
=> menu: fix menu double entries

projects/admin/src/app/app.module.ts, projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html, projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.html, projects/admin/src/app/record/brief-view/items-brief-view/items-brief-view.component.html, projects/admin/src/app/record/detail-view/collection-detail-view/collection-items/collection-items.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/shared/src/lib/pipe/item-holdings-call-number.pipe.spec.ts, projects/shared/src/lib/pipe/item-holdings-call-number.pipe.ts, projects/shared/src/lib/shared.module.ts, projects/shared/src/lib/view/inherited-call-number/inherited-call-number.component.html, projects/shared/src/lib/view/inherited-call-number/inherited-call-number.component.spec.ts, projects/shared/src/lib/view/inherited-call-number/inherited-call-number.component.ts, projects/shared/src/public-api.ts
For items, the parent holdings first
call_number is displayed when the item has no first
call_number. This call number is inherited in the
following screens :
* document, holdings and item details view.
* patron profile: loans, requests, history tabs.
* collection details view.
* Closes #1288
Co-Authored-by: Aly Badr <aly.badr@rero.ch>
=> items: inherit holdings first call_number

projects/public-search/src/app/app.module.ts, projects/public-search/src/main.ts, projects/search-bar/src/app/app.module.ts
With invenio 3.4 the angular application should live with the webpack
bundle. To fix error message and blank public search page, zone.js
should be included.
=> deploy: fix error message with invenio 3.4

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/document-record-search/document-record-search.component.ts, projects/shared/src/lib/view/thumbnail/thumbnail.component.html, projects/shared/src/lib/view/thumbnail/thumbnail.component.scss, projects/shared/src/lib/view/thumbnail/thumbnail.component.ts
* Updates 'types' field according to new transformation.
Task 1893 of US1812 document types
* https://github.com/rero/rero-ils/pull/1616
See https://tree.taiga.io/project/rero21-reroils/us/1812?milestone=280004
Check brief and detail views of document (public and professional)
Thumbnails should be displayed in the views (brief and detailed)
Types should be displayed below the thumbnail
=> document: implement types field

projects/public-search/src/app/app.module.ts, projects/public-search/src/app/interceptor/custom-request.interceptor.ts
Some characters into the params are escaped by default by the query
request encoder. This commit make the request more robust.
Closes rero/rero-ils#1237.
Co-Authored-By : Renaud Michotte <renaud.michotte@gmail.com>
try to call the URL https://localhost:5000/global/search/documents?q=&page=1&size=10&new_acquisition=:now+1w
The server will answer with a HTTP/200 instead of HTTP/500
=> search: fix encoding parameters problem

projects/admin/src/app/app.module.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-temporary-item-type/holding-item-temporary-item-type.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/routes/items-route.ts
Updates the item route definition to use a 'long mode' editor for items.
Updates item brief/detailed templates to add the temporary circulation
category information.
https://github.com/rero/rero-ils/pull/1606
* Add a temporary circulation category (tmp_itty) on an item.
* Try to display the document detailed view for this item
* Try to display the item detail view for this item.
=> items: add temporary circulation category

.github/workflows/stale.yml
* Adds a gh-actions workflow to mark issue and PR opened since 3 months
without activity stale.
- To mark PR with no activity for the last 3 months to be marked as stale. 
- Check changes.
- Check the workflow on https://github.com/iGormilhit/rero-ils-ui/actions
=> gh-actions: mark PR and issue stale

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/item/item.component.ts
* Adds conditions to consider a checkin with no action performed in
order to display item info (for example, when an in-transit item barcode
is scanned at a wrong library).
* Closes rero/rero-ils#1168.
To solve the issue mentioned above.
N/A
See issue description
=> circulation: display item info when no circ action is performed

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts
* Allows to attached a serial type holdings on a document, even if the
document is not a serial.
* Fixes local fields tab display on import.
My PR depends on `rero-ils#1478`'s PR(s):
*https://github.com/rero/rero-ils/pull/1478
- Document actions
=> documents: allow to add either holdings or items

projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts
If the document is marked as harvested, the creation of holdings/items
must be disallowed by hiding the "add" drop-down button.
=> documents: fix items/holdings creation for harvested document

projects/admin/src/app/app.module.ts, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.html, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.spec.ts, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts, projects/admin/src/app/record/editor/wrappers/user-id/user-id.component.html, projects/admin/src/app/record/editor/wrappers/user-id/user-id.component.ts
* Adds a modal dialog with a new user personal information editor.
-  https://tree.taiga.io/project/rero21-reroils/us/1889?milestone=282105
* https://github.com/rero/rero-ils/pull/1675
- Go to the patron editor and edit the personal information.
and
=> patrons: edit the user personal data in a modal

projects/admin/src/app/routes/acquisition-accounts-route.ts, projects/admin/src/app/routes/acquisition-order-lines-route.ts, projects/admin/src/app/routes/acquisition-orders-route.ts, projects/admin/src/app/routes/budgets-route.ts, projects/admin/src/app/routes/circulation-policies-route.ts, projects/admin/src/app/routes/item-types-route.ts, projects/admin/src/app/routes/locations-route.ts, projects/admin/src/app/routes/organisations-route.ts, projects/admin/src/app/routes/patron-types-route.ts, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/routes/persons-route.ts, projects/admin/src/app/routes/templates-route.ts, projects/admin/src/app/routes/vendors-route.ts, projects/admin/src/manual_translations.ts
* Adds missing strings to manual translations.
* Removes some strings from manual translations because they are already
extracted somewhere else in the application.
* Harmonize the translation of the labels in 'resource'-route files.
* Closes rero/rero-ils#1627.
To solve the issue mentioned above.
N/A
See issue description.
=> menu: translate menu entries

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/public-search/src/app/document-brief/document-brief.component.html, projects/shared/src/lib/shared.module.ts, projects/shared/src/lib/view/brief/part-of/part-of.component.html, projects/shared/src/lib/view/brief/part-of/part-of.component.spec.ts, projects/shared/src/lib/view/brief/part-of/part-of.component.ts, projects/shared/src/public-api.ts
* Moves 'part of' template and code to a new component in shared
library. This component is used in detailed and brief views.
* Closes rero/rero-ils#1596.
To solve the issue mentioned above.
N/A
See issue description.
=> documents: display 'part of' in brief views

projects/admin/src/app/class/typeahead/documents-typeahead.ts, projects/admin/src/app/class/typeahead/patrons-typeahead.ts
The ngx-bootstrap library doesn't allow html tags into typeahead
suggestion anymore.
Closes rero/rero-ils#1708
=> typeahead: remove HTML tags from suggestion

projects/admin/src/app/circulation/patron/loan/fixed-date-form/fixed-date-form.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/utils/validators.ts
It was impossible to choose the current date for a fixed date checkout.
Additionally, the end date sent to backend was time agnostic ; we now
set it to 23:59.
Closes rero/rero-ils#1574
- Execute a fixed date checkout on the current date.
=> circulation: fix fixed date datepicker input

projects/admin/src/app/api/library-api.service.spec.ts, projects/admin/src/app/api/library-api.service.ts, projects/admin/src/app/circulation/patron/loan/fixed-date-form/fixed-date-form.component.ts, projects/admin/src/app/menu/service/library-switch.service.ts, projects/shared/src/lib/class/user.ts
Uses the backend closed dates library API to disallow user to choose a
closed date for a fixed date checkout.
- Try to execute a fixed date checkout for any patrons.
- The datepicker field should reflect directly the closed date depending of the current used library.
=> circulation: improve library closed dates handling

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/public-holdings-items/src/index.html, projects/public-search/src/app/api/item-api.service.ts
Sorts issue items for public document view based on expected date
instead of `enumeration_and_chronology` (standard holding items continue
to be sort by `enumeration_and_chronology`).
Already validated here : https://github.com/rero/rero-ils-ui/pull/543
Bad click closed the PR instead of merge it
Closes rero/rero-ils#1625
Co-Authored-By: Renaud Michotte <renaud.michotte@gmaiil.com>
=> document: sort issue item in document view.

projects/admin/src/app/classes/library.ts, projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts, projects/admin/src/app/record/custom-editor/libraries/library.component.html, projects/admin/src/app/record/custom-editor/libraries/library.component.ts, projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html, projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.ts, proxy.conf.json
* Improves library editor appearance for large screens. It doesn't take
the full width anymore.
* Adds tabs in the library detailed view.
* Adds notifications settings in library custom editor.
* Displays notification settings in library detail view.
To implement task 2013 of US1922 https://tree.taiga.io/project/rero21-reroils/us/1922?milestone=282105
* https://github.com/rero/rero-ils/pull/1691
=> libraries: add notification settings

projects/admin/src/app/app.module.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/record/detail-view/record-masked/record-masked.component.spec.ts, projects/admin/src/app/record/detail-view/record-masked/record-masked.component.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/manual_translations.ts, projects/public-search/src/app/document-detail/holdings/holding/holding.component.html, projects/public-search/src/app/document-detail/item/item.component.html, projects/shared/src/lib/pipe/key-exists.pipe.spec.ts, projects/shared/src/lib/pipe/key-exists.pipe.ts, projects/shared/src/lib/shared.module.ts, projects/shared/src/public-api.ts
* Adds new fields on item detail.
* Adds masked holdings and item on document detail view.
* Activated buttons on item detail view.
* Fixes a bug on holdings availability.
My PR depends on branch:
- https://github.com/rero/rero-ils/tree/US-1906-item-model
- new fields added to the item record
* url
* pac_code
* price
* _masked
* legacy_checkout_count (migrated from Virtua, not possible to edit)
* legacy_circulation_rules (migrated from Virtua, not possible to edit)
- new fields added to the document record
* _masked
- the new fields are displayed in the `item detailed view`
- A new `eye` badge in the admin view to indicate that `item` or `holdings is masked.
- a masked record is not displayed in the public interface
- when a …
=> items: complete item model

projects/admin/src/app/record/custom-editor/libraries/library.component.ts
When the editor get the library metadata, the $ref doesn't need to be
resolved.
- Edit your current library
- Do some changes and save
- Try to edit again
=> library: fix editor problem.

projects/admin/src/app/circulation/classes/patron-transaction.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.ts
* Adds a library column in the fees tabs.
* Adds a dropdown button to pay all the fees related to the current
logged user library.
* Closes #1533.
- issue #1533
* https://github.com/rero/rero-ils/pull/1773
- Go to the patron fees, a new library column should be present, a new dropdown button is present to pay only the current library fees.
=> fees: pay only the fees of my library

projects/admin/src/app/circulation/patron/loan/loan.component.html
In the patron profile, the pending loans should initially be sorted by
transaction date descending order.
Closes rero/rero-ils#1703
=> patron profile: initial sorting parameter.

angular.json, projects/admin/src/app/app.module.ts, projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html, projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.scss, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/record/detail-view/item-type-detail-view/item-type-detail-view.component.html, projects/admin/src/app/record/detail-view/item-type-detail-view/item-type-detail-view.component.ts, projects/admin/src/app/routes/item-types-route.ts, projects/admin/src/app/scss/variables.scss, projects/public-holdings-items/src/index.html, projects/public-search/src/app/api/item-api.service.ts, projects/public-search/src/app/document-detail/holdings/holding/holding.component.html, projects/public-search/src/app/document-detail/holdings/holding/holding.component.spec.ts, projects/public-search/src/app/document-detail/holdings/holding/holding.component.ts, projects/public-search/src/app/document-detail/item/item.component.html, projects/shared/src/lib/pipe/get-translated-label.pipe.spec.ts, projects/shared/src/lib/pipe/get-translated-label.pipe.ts, projects/shared/src/lib/shared.module.ts, projects/shared/src/public-api.ts
* Updates display of circulation category detailed view with new fields.
* Use the circulation informations labels instead of category name if
the label is available in the current used UI language.
* Updates the "availability" colored circle and text behavior according
to new fields.
* Closes rero/rero-ils#1586.
=> Circulation category: update display

package-lock.json, package.json, projects/admin/src/app/app.module.ts, projects/admin/src/app/record/detail-view/document-detail-view/dialog-import/dialog-import.component.html, projects/admin/src/app/record/detail-view/document-detail-view/dialog-import/dialog-import.component.spec.ts, projects/admin/src/app/record/detail-view/document-detail-view/dialog-import/dialog-import.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts, projects/admin/src/app/record/editor/wrappers/identifiedby-value.component.ts, projects/admin/src/app/record/editor/wrappers/user-id/user-id.component.ts
* Validates the EAN/ISBN/ISSN/ISSN-L identifier as it is entered in the document editor.
* Checks if the identifier already exists in the instance (non-blocking validation).
* Validates and checks all `identifiedyBy` fields of the document as it is imported.
* Closes rero/rero-ils#1664.
- To fix issue https://github.com/rero/rero-ils/issues/1664
My PR depends on `rero-ils`'s PR(s):
* rero/rero-ils#1832
- Check form field "identified by"
- Check import document
=> documents: validate and check the identifier

package-lock.json, package.json, projects/admin/src/app/routes/documents-route.ts, projects/public-search/src/app/routes/documents-route.service.ts
* Closes rero/rero-ils#1728.
* Renames the title of the "Organisations" tab into "Corporate bodies".
* Allows to configure the aggregation name.
- To personalize aggregation title
My PR depends on `ng-core`'s PR(s):
* rero/ng-core#375
- check if the name of the "organization" aggregation is personalized
=> search: update search tab title & aggregation name

projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.ts, projects/admin/src/app/classes/typeahead/mef-typeahead.ts, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts, projects/admin/src/app/record/editor/wrappers/user-id/user-id.component.ts, projects/admin/src/app/routes/patrons-route.ts, projects/shared/src/lib/service/app-settings.service.spec.ts, projects/shared/src/lib/service/app-settings.service.ts, projects/shared/src/tests/user.ts
* Removes useless console log messages.
* Adds a role patron editor validator to avoid multiple professional
accounts
Only the last commit.
- https://tree.taiga.io/project/rero21-reroils/us/2034?milestone=289558
- https://github.com/rero/rero-ils/pull/1797
=> patrons: add a role async validator

projects/admin/src/app/circulation/classes/patron-transaction.ts, projects/admin/src/app/circulation/services/patron-transaction.service.ts, projects/admin/src/app/classes/ill-request.ts, projects/admin/src/app/classes/items.ts, projects/admin/src/app/classes/library.ts, projects/admin/src/app/classes/loans.ts, projects/admin/src/manual_translations.ts
* The `marker` funuction (used to mark a string as extractable for
translation) cannot be used as enum value. Place these values into the
manual_translation file.
* Fix translation issues.
* Closes rero/rero-ils#1814
=> translations: fix string extraction problem

projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.html, projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.ts, projects/admin/src/app/circulation/patron/pending/pending.component.html, projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.html, projects/admin/src/app/circulation/patron/pickup/pickup.component.html
* Adds a column into `pending` patron profile tab to display the request
creation date.
* Adds a column into `pickup` patron profile tab to display the
"available until" date.
* Closes rero/rero-ils#1778.
=> circulation: add data into pending/pickup patron profile

projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.html, projects/admin/src/app/record/brief-view/issues-brief-view/issues-brief-view.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/scss/styles.scss
* For a late issue brief view, the main ink should point to the holdings
detail view instead of item detail view. The item detail link is now
placed on the barcode.
* Adds a link to point on holding parent detail view on the item detail
view if the item is an issue.
* Closes rero/rero-ils#1808.
=> Issue: update links on late issue brief view

.github/labeler.yml, .github/workflows/labeler.yml
* Creates a github actions labeler configuration file that rule which
label to apply when.
* Creates a github actions labeler workflow.
- To implement gh-actions labeler
=> documentation: create gh-actions labeler

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/related-resource/related-resource.component.html
* Moves online resources from the "Descriptions" tab to the header.
* Closes rero/rero-ils#1722.
- https://github.com/rero/rero-ils/issues/1722
- Check online resources on header (admin interface)
=> documents: improve online access information

projects/admin/src/app/circulation/patron/card/card.component.html, projects/admin/src/app/circulation/patron/card/card.component.ts, projects/admin/src/app/circulation/patron/main/main.component.html
Display circulation messages (blocked, max item checkout, ...) related
to the loaded patrons on the patron circulation view.
Closes rero/rero-ils#1964.
- Edit a "patron" user ; block it for some reasons.
- Go to the circulation view of this patron.
- The block message will be displayed.
=> circulation: display circulation messages

projects/admin/src/app/circulation/patron/patron-transactions/overdue-transaction/overdue-transaction.component.spec.ts, projects/admin/src/app/pipe/subject-process.pipe.spec.ts, projects/admin/src/environments/environment.prod.ts, projects/admin/src/environments/environment.ts, projects/public-holdings-items/src/environments/environment.prod.ts, projects/public-holdings-items/src/environments/environment.ts, projects/public-patron-profile/src/environments/environment.prod.ts, projects/public-patron-profile/src/environments/environment.ts, projects/public-search/src/environments/environment.prod.ts, projects/public-search/src/environments/environment.ts, projects/shared/src/tests/user.ts
* Renames the base URL from `ils.rero.ch` to `bib.rero.ch`
as it is the production web site URL.
=> instance: change base URL

projects/admin/src/app/acquisition/acquisition.module.ts, projects/admin/src/app/acquisition/api/acq-account-api.service.ts, projects/admin/src/app/acquisition/components/account/account-transfer/account-transfer.component.spec.ts, projects/admin/src/app/acquisition/components/account/account-transfer/account-transfer.component.ts, projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.html, projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.scss, projects/admin/src/app/acquisition/components/editor/widget/select-account-editor-widget/select-account-editor-widget.component.ts, projects/admin/src/app/acquisition/routes/accounts-route.ts, projects/admin/src/app/acquisition/routes/order-lines-route.ts, projects/admin/src/app/app.module.ts
Creates a formly widget especially for `AcqAccount` resource. This
widget will generate a hierarchical dropdown list with a remaining
balance statement.
=> acquisitions: account selector widget

projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/serial-holding-detail-view.component.ts, projects/admin/src/app/routes/holdings-route.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/routes/route-tool.service.ts, projects/admin/src/app/service/record-permission.service.ts, projects/public-search/src/app/api/holdings-api.service.ts
The standard holdings present on the document are filtered
according to a count of the displayable items.
The serial holdings present on the document are automatically displayed.
Permissions: If a library field exists on the resource,
it allows you to check if it matches the connected user.
* Fixes the display of the masking information on the item.
* Improves permission controls.
* Closes rero/rero-ils#1989
- Filter holdings on document display
* rero/rero-ils#2012
__Public view:__
- Check document view with filter (field masked on item and holdings)
__Interface pro:__
- Check permission on holdings/items with a librarian account
- Check permission on holdings/items with a system …
=> documents: filters holdings by items

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/public-search/src/app/document-brief/document-brief.component.html, projects/shared/src/lib/view/brief/part-of/part-of.component.html, projects/shared/src/lib/view/brief/part-of/part-of.component.ts
* Fixes subject badges text on detailed view of the professional interface.
* Fixes `partOf` link on detailed view of the public interface.
- Part-of link on public view.
=> documents: fix detailed view

projects/public-holdings-items/src/app/app-initializer.service.ts, projects/public-search/src/app/app-initializer.service.spec.ts, projects/public-search/src/app/app-initializer.service.ts, projects/public-search/src/app/app.component.ts, projects/public-search/src/app/document-brief/document-brief.component.html, projects/shared/src/lib/view/thumbnail/thumbnail.component.html
* Fixes the current language on public interface.
* Improves center the text above thumbnail on document brief view.
* Moves the document availability at the end of the metadata of the
document brief view.
* Closes rero/rero-ils#1391.
=> ui: fix language setting on the public interface

.github/labeler.yml
* Adds a rule for the acquisition label.
- To add a missing label rule.
=> documentation: extend gh-actions labeler rules

projects/admin/src/app/api/operation-logs-api.service.spec.ts, projects/admin/src/app/api/operation-logs-api.service.ts, projects/admin/src/app/app.module.ts, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.css, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.html, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.spec.ts, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.ts, projects/admin/src/app/record/circulation-logs/circulation-logs-dialog/circulation-logs-dialog.component.html, projects/admin/src/app/record/circulation-logs/circulation-logs-dialog/circulation-logs-dialog.component.spec.ts, projects/admin/src/app/record/circulation-logs/circulation-logs-dialog/circulation-logs-dialog.component.ts, projects/admin/src/app/record/circulation-logs/circulation-logs.component.css, projects/admin/src/app/record/circulation-logs/circulation-logs.component.html, projects/admin/src/app/record/circulation-logs/circulation-logs.component.spec.ts, projects/admin/src/app/record/circulation-logs/circulation-logs.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html
* Displays the circulation history of the item on
the item detailed view of the professional interface.
- Check `circulation history` on item
=> items: implement circulation history

projects/admin/src/app/routes/corporate-bodies-route.ts
Includes the pre-filter `bf:Organisation` on the corporate bodies search
page.
Update the corporate bodies search page title to `Organisation` (use the
same label than the menu label).
=> search: fix corporate bodies search

projects/admin/src/app/service/record-permission.service.ts
Fixes reason why not to delete a record if the record doesn't belong to
the current library.
Co-aurhored-by: Renaud Michotte <renaud.michotte@gmail.com>
=> general: fix tooltip membership message

projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts, projects/admin/src/app/record/editor/wrappers/user-id/user-id.component.ts
Closes rero/rero-ils#2098.
- Edit the user information about a patron. This will use the modal user form.
- Try to click outside of the modal. The modal should not closed.
=> users: close modal by clicking outside the form

package-lock.json, package.json, projects/admin/src/app/record/document-record-search/document-record-search.component.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/patrons-route.ts
* Disables the list of results for patrons and documents search view for
empty query.
=> admin: do not display default result list

angular.json, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts, projects/public-holdings-items/src/index.html, projects/public-search/src/app/api/item-api.service.ts, projects/public-search/src/app/api/location-api.service.spec.ts, projects/public-search/src/app/api/patron-transaction-api.service.spec.ts, projects/public-search/src/app/document-detail/holdings/holding/holding.component.html, projects/public-search/src/app/document-detail/holdings/holding/holding.component.spec.ts, projects/public-search/src/app/document-detail/holdings/holding/holding.component.ts, projects/public-search/src/app/document-detail/holdings/holdings.component.html, projects/public-search/src/app/document-detail/holdings/holdings.component.spec.ts, projects/public-search/src/app/document-detail/holdings/holdings.component.ts, projects/public-search/src/app/document-detail/holdings/items/items.component.html, projects/public-search/src/app/document-detail/holdings/items/items.component.ts, projects/public-search/src/app/document-detail/item/item.component.html, projects/public-search/src/app/document-detail/item/item.component.spec.ts, projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.spec.ts, projects/public-search/src/app/document-detail/request/request.component.spec.ts
* Loads/displays more holding by default (10). Collapse holdings panels if
there are more than 1 holdings to display.
* Loads/displays more items by default (10).
* Fixes linting of `public-search` project.
* Harmonizes public/professional document view.
* Closes rero/rero-ils#2134.
* Closes rero/rero-ils#2133.
* Closes rero/rero-ils#2172.
=> documents: optimize holdings/items display

projects/public-search/src/app/document-brief/document-brief.component.html, projects/shared/src/lib/view/thumbnail/thumbnail.component.scss
Fixes the document brief view for small screen. On small screen the
thumbnail is displayed above the metadata and is not yet maximized to
prevent thumbnail pixelisation.
=> search: fix document brief view

projects/public-search/src/app/document-detail/holdings/holding/holding.component.html, projects/public-search/src/app/document-detail/holdings/holding/holding.component.spec.ts, projects/public-search/src/app/document-detail/holdings/holding/holding.component.ts, projects/public-search/src/app/document-detail/holdings/items/items.component.html, projects/public-search/src/app/document-detail/holdings/items/items.component.ts
When displaying the document detail view, items metadata are loaded for
each holdings causing a backend call even if the holding is collapsed.
Now, the items metadata are loaded only if user expand holding;
=> document: dynamic loading for items informations

projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/import-documents-route.ts
* Disallows empty search to be able to search with a query in BNF
import view.
* Hides `holdings` in tabs.
* Displays the title Documents in documents search view.
Co-Authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
=> search: fix several issues

projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.html, projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts
=> items: add spinner during request process

projects/admin/src/app/circulation/checkin/checkin.component.html, projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/main-request/main-request.component.html, projects/admin/src/app/circulation/main-request/main-request.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.ts
The input field is automatically disabled during
the transaction on the "checkin/checkout" and "Request" screens.
* Closes rero/rero-ils#2244.
* rero/ng-core (last dev)
- Check checkin/checkout and request screens.
=> circulation: clear input after checkout action

projects/admin/src/app/record/detail-view/contribution-detail-view/contribution-detail-view.component.html, projects/admin/src/app/record/detail-view/contribution-detail-view/corporate-bodies-detail-view/corporate-bodies-detail-view.component.html, projects/admin/src/app/record/detail-view/contribution-detail-view/corporate-bodies-detail-view/corporate-bodies-detail-view.component.ts, projects/admin/src/app/record/detail-view/contribution-detail-view/person-detail-view/person-detail-view.component.html, projects/admin/src/app/record/detail-view/contribution-detail-view/person-detail-view/person-detail-view.component.ts
=> contributions: remove link on source title

projects/admin/src/app/circulation/checkin/checkin.component.html, projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/items-list/items-list.component.ts, projects/admin/src/app/circulation/main-request/main-request.component.ts, projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html, projects/admin/src/app/circulation/main-request/requested-items-list/requested-items-list.component.html, projects/admin/src/app/circulation/patron/history/history-item/history-item.component.html, projects/admin/src/app/circulation/patron/history/history-item/history-item.component.ts, projects/admin/src/app/circulation/patron/history/history.component.html, projects/admin/src/app/circulation/patron/history/history.component.ts, projects/admin/src/app/circulation/patron/loan/loan.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.ts, projects/admin/src/app/circulation/patron/pending/pending-item/pending-item.component.html, projects/admin/src/app/circulation/patron/pending/pending.component.html, projects/admin/src/app/circulation/patron/pending/pending.component.ts, projects/admin/src/app/circulation/patron/pickup/pickup-item/pickup-item.component.html, projects/admin/src/app/circulation/patron/pickup/pickup.component.html, projects/admin/src/app/circulation/patron/pickup/pickup.component.ts, projects/admin/src/app/record/detail-view/acquisition-order-detail-view/order-lines/order-line/order-line.component.html, projects/admin/src/app/record/detail-view/budget-detail-view/acquisition-account/acquisition-account.component.html, projects/admin/src/app/record/detail-view/library-detail-view/location/location.component.html, projects/public-search/src/app/document-detail/holdings/items/items.component.html, projects/public-search/src/app/document-detail/holdings/items/items.component.ts
* Removes loading wheels during the backend transactions as it reload
completely the view and has been implemented using `ngx-loading-bar`.
* Closes rero/rero-ils#2259.
Co-authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
- Close issue rero/rero-ils#2259.
- Check all the circulation operations.
=> circulation: remove loading wheels

projects/admin/src/app/record/brief-view/patrons-brief-view/patrons-brief-view.component.html, projects/admin/src/app/scss/styles.scss
Use a link instead of a button to access circulation screen into the
patron brief view. This allows to open the patron circulation screen
into a new window (right click on the link + open in a new window).
=> patrons: use link instead of button for circulation link.

package-lock.json, package.json, projects/admin/src/app/record/brief-view/items-brief-view/items-brief-view.component.html, projects/admin/src/app/routes/circulation-policies-route.ts, projects/admin/src/app/routes/collections-route.ts, projects/admin/src/app/routes/corporate-bodies-route.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/item-types-route.ts, projects/admin/src/app/routes/items-route.ts, projects/admin/src/app/routes/libraries-route.ts, projects/admin/src/app/routes/patron-types-route.ts, projects/admin/src/app/routes/patrons-route.ts, projects/admin/src/app/routes/persons-route.ts, projects/admin/src/app/routes/templates-route.ts, projects/admin/src/app/routes/vendors-route.ts, projects/public-search/src/app/routes/collections-route.service.ts, projects/public-search/src/app/routes/documents-route.service.ts
* Adds sorting feature to the following search result list:
* Circulation policies.
* Collections.
* Corporates bodies.
* Documents.
* Item types (circulation categories).
* Items.
* Libraries.
* Patron types.
* Patrons.
* Persons.
* Templates.
* Vendors.
* Adds second call number field on item inventory list.
My PR depends on PR(s):
* rero/ng-core#444
=> search: added sort on some resources

projects/admin/src/app/api/holdings-api.service.spec.ts, projects/admin/src/app/api/holdings-api.service.ts, projects/admin/src/app/api/item-api.service.spec.ts, projects/admin/src/app/api/item-api.service.ts, projects/admin/src/app/app.module.ts, projects/admin/src/app/guard/can-access.guard.spec.ts, projects/admin/src/app/guard/can-access.guard.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding-organisation/holding-organisation.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding-organisation/holding-organisation.component.scss, projects/admin/src/app/record/detail-view/document-detail-view/holding-organisation/holding-organisation.component.spec.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding-organisation/holding-organisation.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holdings/holdings.component.ts, projects/admin/src/app/routes/holdings-route.ts, projects/admin/src/app/routes/items-route.ts, projects/shared/src/lib/shared.module.ts
Display of other organizations' holdings/items in the document detail view.
* Closes rero/rero-ils#1945.
=> documents: allow to show other organisations holdings/items

projects/admin/src/app/circulation/checkin/checkin-action/checkin-action.component.html, projects/admin/src/app/circulation/checkin/checkin-action/checkin-action.component.spec.ts, projects/admin/src/app/circulation/checkin/checkin-action/checkin-action.component.ts, projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/circulation.module.ts
A dialog appears when there is an item and a patron with the same barcode.
The library chooses the action to execute.
* Closes rero/rero-ils#2597.
=> circulation: checkin operations when item/patron barcode are identical

projects/admin/src/app/acquisition/components/order/order-brief-view/order-brief-view.component.ts
When an order has multiple reception date, take the first one as display
value.
=> acquisition: fix receipt date in order brief view

projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-transaction/item-transaction.component.html
Add the request time to the request date into the `requestedBy` box. At
this time, only the date was displayed : it was not precise enough.
Closes rero/rero-ils#1704.
https://github.com/rero/rero-ils/pull/2646
=> request: display the request time

projects/admin/src/app/record/detail-view/patron-types-detail-view/patron-types-detail-view.component.html, projects/admin/src/app/routes/patron-types-route.ts
Display the new restriction limit for "unpaid subscription" into the
patron_type detailed view.
=> patron_type: display of unpaid subscription limit

projects/admin/src/app/routes/items-route.ts
- Adds config for temporary item type facet.
- Adds config for temporary location facet.
Co-Authored-by: Laurent Dubois <laurent.dubois@itld-solutions.be>
* rero/rero-ils#2612
=> items: configure new facets for inventory list

projects/admin/src/app/routes/items-route.ts
This new filter allows to display only the items of the user's organization.
- items filter on inventory list
* [https://github.com/rero/rero-ils/pull/2718](https://github.com/rero/rero-ils/pull/2718)
- Check if the item's list is filter.
=> item: add organisation filter

projects/public-holdings-items/src/index.html, projects/public-search/src/app/document-detail/holdings/holding/holding.component.html, projects/public-search/src/app/document-detail/holdings/holdings.component.html
The carret button is now visible if the holding has at least one  linked item doesn't matter the holding type.
Closes rero/rero-ils#2502.
=> holdings: fix item collapsing

projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/received-issue/received-issue.component.html, projects/admin/src/app/record/detail-view/holding-detail-view/serial-holding-detail-view/received-issue/received-issue.component.ts, projects/admin/src/app/routes/items-route.ts
* Displays 'reception date' only if issue has the 'received' status.
* Displays the 'status date' just after the status when an issue is not
collapsed.
* Cleans data before sent them to server.
https://github.com/rero/rero-ils/pull/2721
=> holdings: fix detailed view for issue items.

projects/public-search/src/app/api/loan-api.service.ts, projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loans.component.html, projects/public-search/src/app/patron-profile/patron-profile-loans/patron-profile-loans.component.ts
Add sort for due date in patron profile view.
Closes: https://github.com/rero/rero-ils/issues/2263
=> patron profile: add sort by due date

projects/admin/src/app/record/editor/wrappers/identifiedby-value.component.ts
The control of the isbn or issn value has been improved.
If the value is identified on the same record, it no longer
displays the validation message.
* Improves validation on isbn/issn field.
* Closes rero/rero-ils#2407.
=> document: improve isbn and issn check

projects/admin/src/app/circulation/item/item.component.html
Display due date (loans last_end_date) at checkin.
Solves issue https://github.com/rero/rero-ils/issues/2637
My PR depends on the following `rero-ils`'s PR(s):
* rero/rero-ils/pull/2897
=> circulation: display due date at checkin

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html
* Adds tooltips to buttons in the holding component (admin UI)
* Concerns RT 282
=> holdings: small ui fix

projects/admin/src/app/record/detail-view/contribution-detail-view/corporate-bodies-detail-view/corporate-bodies-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/holding.component.html, projects/admin/src/app/record/detail-view/document-detail-view/related-resource/related-resource.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/public-search/src/app/document-brief/document-brief.component.html, projects/public-search/src/app/document-detail/item/item.component.html, projects/shared/src/lib/pipe/safe-url.pipe.ts, projects/shared/src/lib/shared.module.ts, projects/shared/src/public-api.ts
Allow to specify that URL are safe. In this case, Angular doesn't add an
"unsafe:" protocol string on the href link.
Closes rero/rero-ils#2893.
Adds a item URL with a "rtsp" protocol and check all screens where this url could be displayed :
* item detail view
* holdings panel view
* ...
=> general: Safe URL pipe

projects/admin/src/app/classes/identifiers.ts, projects/admin/src/app/classes/typeahead/documents-typeahead.ts, projects/admin/src/app/record/editor/wrappers/identifiedby-value.component.ts
When encoding a identifier for a document, check if another document
already hold this identifier (or an alternative to this identifier).
Closes rero/rero-ils#1893.
https://github.com/rero/rero-ils/pull/2909
=> document: `identifiedBy` duplicate check.

angular.json, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts, projects/public-search/src/app/patron-profile/patron-profile-personal-editor/patron-profile-personal-editor.component.ts
Updates form fields related to email to directly validate an email
address without submitting the form.
https://github.com/rero/ng-core/pull/499
=> forms: add email validation behavior

projects/admin/src/app/guard/can-access.guard.spec.ts
=> guard: fix tests on CanAccessGuard

projects/admin/src/app/circulation/item/item.component.html
* Closes rero/rero-ils#3014.
Call numbers are display below the item barcode when information is collapsed ; into the item/circulation information when item is expended (as other badges, notes, ...)
=> circulation: add call-numbers on loan circulation information.

projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts, projects/public-search/src/app/document-detail/holdings/holding/holding.component.html, projects/public-search/src/app/document-detail/holdings/holding/holding.component.ts, projects/public-search/src/app/document-detail/holdings/items/items.component.html, projects/public-search/src/app/document-detail/holdings/items/items.component.ts, projects/public-search/src/app/document-detail/item/item.component.html, projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.html, projects/public-search/src/app/document-detail/request/pickup-location/pickup-location.component.ts, projects/public-search/src/app/document-detail/request/request.component.html, projects/public-search/src/app/document-detail/request/request.component.ts
The holdings request button has been removed from the holdings block.
This button now appears at the end of the items list.
* Closes rero/rero-ils#2943.
=> documents: Improved display of the request button on the holdings

projects/admin/src/app/menu/service/menu-user-services.service.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/route.service.ts, projects/public-search/src/app/routes/documents-route.service.spec.ts, projects/public-search/src/app/routes/documents-route.service.ts, projects/public-search/src/index.html
- Marks the aggregation as open if the url contains a corresponding filter including children filters.
- Adds the ActivatedRoute service for the document route class.
Co-Authored-by: Johnny Mariéthoz [Johnny.Mariethoz@rero.ch](mailto:Johnny.Mariethoz@rero.ch)
Co-Authored-by: Valeria Granata [valeria@chaw.com](mailto:valeria@chaw.com)
US: https://github.com/rero/rero-ils/issues/2763
* rero/rero-ils#2953
* https://github.com/rero/ng-core/pull/503/
=> documents: open aggregation with filters and add more facets for documents search

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts, projects/shared/src/lib/view/brief/part-of/part-of.component.html, projects/shared/src/lib/view/brief/part-of/part-of.component.ts
The `partOf` (collection) fields is now displayed as a main title.
Co-authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
=> document: fix collection display

projects/admin/src/app/acquisition/components/order/order-detail-view/order-line/order-line.component.ts, projects/admin/src/app/service/record-permission.service.ts
In the Order detail view, the order line button actions were not
displayed correctly.
* Adds plural links messages.
=> acquisitions: fix message info on order line edit button

projects/admin/src/manual_translations.ts
* Adds manual translation for "current loans".
=> menu: translation for current loans

projects/admin/src/app/record/detail-view/document-detail-view/document-description/document-description.component.ts
* Adds number and name fields in the title variant.
* Closes rero/rero-ils#2906 (part 2).
=> documents: formatting of the title variant

projects/admin/src/app/classes/library.ts, projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts, projects/admin/src/app/record/custom-editor/libraries/library.component.html, projects/admin/src/app/record/custom-editor/libraries/library.component.ts, projects/admin/src/app/record/detail-view/library-detail-view/library-detail-view.component.html
* Adds new rollover settings form on acquisitions tab.
* Adds rollover settings on the library detailed view.
**Library form**
**Library detailed view**
=> libraries: add rollover settings

projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/patron/main/main.component.ts
* Adds the link on the patron's name to bounce to his account.
* Closes rero/rero-ils#2997.
=> circulation: add link to patron name

projects/admin/src/app/classes/typeahead/documents-typeahead.ts
The filter option has been added to the document query. This allows to customize the query by specifying it in the json schema.
* Closes rero/rero-ils#3018.
[document: add filter on the remoteTypeahead](https://github.com/rero/rero-ils/pull/3114)
=> document: filter on the remote typeahead

proxy.conf.json
Since new version of webpack the dev server should support Keep-Alive header to avoid dev server crashes.
=> devel: add keep alive header for proxy

projects/admin/src/app/record/brief-view/patron-transaction-events-brief-view/patron-transaction-event-overdue.component.html, projects/admin/src/app/record/search-view/patron-transaction-event-search-view/payments-data/pie/payment-data-pie.component.scss, projects/admin/src/app/scss/styles.scss
* If some fee related resource doesn't still exists, this will cause an error. Now if data is missing, a label containing the related resource pid is displayed.
* Fix fees pie widget legend display
See missing "item:466" (third search result hit)
=> Fees: fix labels for missing data

package-lock.json, package.json, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.html, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts, projects/public-search/src/app/api/user-api.service.ts, projects/public-search/src/app/patron-profile/patron-profile-password/patron-profile-password.component.ts
The password is mandatory if the user is not loaded,
otherwise it is optional
* Adds validator on new password on change password dialog.
* Fixes the identifier of the delete button so that it is unique.
=> user: password validator

projects/admin/src/app/record/brief-view/patrons-brief-view/patrons-brief-view.component.html
=> patron: fix the display of the badges on brief view

projects/admin/src/manual_translations.ts
=> menus: add missing translation

projects/admin/src/app/api/notification-api.service.spec.ts, projects/admin/src/app/api/notification-api.service.ts, projects/admin/src/app/api/operation-logs-api.service.ts, projects/admin/src/app/app.module.ts, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.html, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.scss, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.ts, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-notification/circulation-log-notification.component.html, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-notification/circulation-log-notification.component.scss, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-notification/circulation-log-notification.component.ts, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.html, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.scss, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log.component.spec.ts, projects/admin/src/app/record/circulation-logs/circulation-logs.component.html, projects/admin/src/app/record/circulation-logs/circulation-logs.component.ts, projects/admin/src/manual_translations.ts
Circulation related notifications are now visible in the operation logs. There are also filters to select a type.
* Closes rero/rero-ils#2639.
=> item circulation history: add notification

projects/admin/src/app/classes/library.ts
Sunday was not disabled in the fixed Date Loan dialog.
* Closes rero/rero-ils#2370.
=> circulation: fix fixed date sunday not disabled

projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction-event-form/patron-transaction-event-form.component.ts, projects/admin/src/app/circulation/services/patron-transaction.service.ts
* When a librarian will pay for multiple transactions, it was possible that the calculated total amount had more than 2 decimals. This is due to floating-point decimal precision with float numbers in Javascript. This PR ensure than all amount/calculation about fees are maximum 2 decimals.
* Closes rero/rero-ils#2961.
=> Transactions: fix transactions total amount calculation

projects/admin/src/app/api/item-api.service.ts, projects/admin/src/app/app.module.ts, projects/admin/src/app/record/circulation-logs/circulation-logs.component.html, projects/admin/src/app/record/circulation-logs/circulation-stats/circulation-stats.component.html, projects/admin/src/app/record/circulation-logs/circulation-stats/circulation-stats.component.ts
On the item operation history screen, there are now statistics
on checkout and extend (total and past year)
* Closes rero/rero-ils#2996.
[item operation history: add statistics (ILS)](https://github.com/rero/rero-ils/pull/3314)
=> item operation history: add statistics

.gitignore, projects/admin/src/app/service/keyboard-shortcuts.service.ts
* Addresses RT 555.
* Adds dev proxy file to gitignore.
=> keyboard shortcuts: add inventory list hotkey

projects/admin/src/app/app.module.ts, projects/admin/src/app/interceptor/user-current-library.interceptor.ts
Administration: `current_library` parameter added to all http requests to identify the user's library.
- https://github.com/rero/rero-ils/pull/3372
=> http: add current_library parameter on api call

projects/admin/src/app/menu/service/library-switch-menu-storage.service.ts, projects/admin/src/app/menu/service/menu-factory.service.ts, projects/admin/src/app/menu/service/menu.service.ts
The default library was deleted on logout. This is no longer the case.
* Closes rero/rero-ils#3362.
=> user: default active library

projects/admin/src/app/app.module.ts, projects/admin/src/app/classes/typeahead/mef-typeahead.ts, projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.component.html, projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.component.scss, projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.component.ts, projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.interface.ts, projects/admin/src/app/scss/styles.scss, projects/admin/src/app/service/ui-remote-typeahead.service.ts
Creates a remote typeahead component that allows to split suggestions
into several column. Suggestions box includes a button to create a new
local entity if current logged user has permissions to create it.
https://github.com/rero/ng-core/pull/558
=> typeahead: custom remote entity typeahead component

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
On the admin interface, subjects and form types have a link to the entity's detailed display. If the information is textual, there is no link.
=> document: add link to subjects and genreForm

projects/admin/src/app/record/formly/type/entity-typeahead/entity-typeahead.component.ts
If there are no results and the user does not have authorization to add a local entity, the menu is no longer displayed.
=> editor: entity typeahead menu behavior

projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction-detail/overdue-transaction-detail.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/overdue-transaction-detail/overdue-transaction-detail.component.ts
=> fix: display manual overdue

projects/admin/src/app/record/brief-view/patron-transaction-events-brief-view/patron-transaction-event-default.component.html, projects/admin/src/app/record/brief-view/patron-transaction-events-brief-view/patron-transaction-event-overdue.component.html
In the case of manual charges, there is no document and no item. We display either the note or the type.
=> fees: fix error on display

projects/admin/src/app/circulation/item/item.component.html
* Adds location pickup name when the loan is in at_desk status during the checkin.
* Closes rero/rero-ils#3433.
* https://github.com/rero/rero-ils/pull/3450
=> circulation: add pickup name on checkin

projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/main-request/requested-item/requested-item.component.html
=> circulation: fix patron barcode

projects/admin/src/app/record/brief-view/documents-brief-view/documents-brief-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.html, projects/admin/src/app/record/detail-view/document-detail-view/holding/default-holding-item/default-holding-item.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/holding/serial-holding-item/serial-holding-item.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.ts, projects/admin/src/app/service/items.service.ts, projects/public-search/src/app/document-brief/document-brief.component.html, projects/public-search/src/app/document-detail/holdings/holding/holding.component.html, projects/public-search/src/app/document-detail/item/item.component.html, projects/shared/src/lib/view/availability/availability.component.html, projects/shared/src/lib/view/availability/availability.component.ts
=> item: update status after request

angular.json, package.json, projects/admin/src/environments/environment.prod.ts, projects/admin/src/environments/environment.ts, projects/public-holdings-items/src/environments/environment.prod.ts, projects/public-holdings-items/src/environments/environment.ts, projects/public-patron-profile/src/environments/environment.prod.ts, projects/public-patron-profile/src/environments/environment.ts, projects/public-search/src/environments/environment.prod.ts, projects/public-search/src/environments/environment.ts, projects/public-user-password-change/src/environments/environment.prod.ts, projects/public-user-password-change/src/environments/environment.ts, projects/public-user-profile-edit/src/environments/environment.prod.ts, projects/public-user-profile-edit/src/environments/environment.ts, projects/search-bar/src/environments/environment.prod.ts, projects/search-bar/src/environments/environment.ts, projects/shared/ng-package.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/ar.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/de.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/en.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/en_US.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/es.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/fr.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/it.json, projects/shared/src/assets/rero-ils-ui/shared/i18n/nl.json
- Adds cli commands to extract and update translations.
- Copies shared assets to the app projects.
- Fixes assets pathes with the node dev server.
=> shared: enable translations

projects/admin/src/app/classes/typeahead/mef-typeahead.ts, projects/shared/src/lib/class/entities.ts, projects/shared/src/lib/component/entities/entity-brief-view/entity-brief-view.component.ts
=> editor: add icon type on entity typeahead

projects/admin/src/app/record/detail-view/patron-detail-view/patron-detail-view.component.html
=> patron: fix display of optional address fields

projects/admin/src/app/api/ill-request-api.service.ts, projects/admin/src/app/circulation/patron/ill-request/ill-request-item/ill-request-item.component.html, projects/admin/src/app/circulation/patron/ill-request/ill-request.component.html, projects/admin/src/app/record/detail-view/ill-request-detail-view/ill-request-detail-view.component.html, projects/public-search/src/app/api/ill-request-api.service.ts
* Sorts ILL Requests by descending created-date in the ApiService.
* Displays the ILL 'request date' and 'pickup location' inline instead
of in the collapsible details.
=> ill requests: improve pro patron view

projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts, projects/admin/src/app/routes/statistics-cfg-route.ts
* Adds library editor validators for notification settings.
* Display facettes in the stat config editor when no result occurs.
=> libraies: add editor validation

projects/admin/src/app/app.module.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/document-detail/document-detail.component.html, projects/admin/src/app/record/detail-view/document-detail-view/document-detail/document-detail.component.ts, projects/admin/src/app/routes/documents-route.ts, projects/admin/src/app/routes/import-documents-route.ts
- https://github.com/rero/ng-core/pull/574
=> documents: refactoring action buttons

projects/admin/src/app/app.module.ts, projects/admin/src/app/circulation/services/patron-transaction.service.ts, projects/admin/src/app/routes/import-documents-route.ts, projects/admin/src/app/service/record.handle-error.service.ts
* Implements the new handle error service.
* Personalizes the error message for the document import.
* Closes https://github.com/rero/rero-ils/issues/3564.
- ILS: https://github.com/rero/rero-ils/pull/3566
- NG-Core: https://github.com/rero/ng-core/pull/577
=> chore: implement new handle error service

projects/admin/src/app/record/detail-view/document-detail-view/document-detail-view.component.html
In the case of import, we hide the related entities tab.
=> feat(documents): hide related entities tab

projects/admin/src/app/service/items.service.ts
* When performing a receive action on a loan, the ui didn't append the loan info and so the item could be treated as having no loan.
* Closes https://github.com/rero/rero-ils/issues/3612.
=> fix(circulation): no loan info on receive

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/item/item.component.ts, projects/admin/src/app/classes/items.ts
The check-in note is displayed when an item arrives from transit.
* Closes rero/rero-ils#3610.
=> feat(circulation): display check-in note

projects/admin/src/app/service/record-permission.service.ts
=> fix(permission): missing collections message

projects/admin/src/app/app.module.ts, projects/admin/src/app/menu/menu-definition/menu-app.ts, projects/admin/src/app/menu/menu.component.ts
To avoid redirection if the default settings are not present, they are added directly to the menu items.
=> chore(menu): add query params on some routes

projects/public-search/src/app/service/bucket-name.service.ts
The language facet was not translated correctly,
as the key starts with `lang_'.
=> fix(document): language facet translation

projects/admin/src/app/circulation/patron/cancel-request-button.component.ts
When we cancel a request, if another request is active on the item, an additional message is added to the dialog.
* Closes rero/rero-ils#3571.
=> feat(circulation): add message on alert

projects/admin/src/app/circulation/checkin/checkin.component.ts, projects/admin/src/app/circulation/item/item.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.ts, projects/admin/src/app/classes/items.ts, projects/admin/src/app/record/brief-view/collection-brief-view.component.ts, projects/public-search/src/app/collection-brief/collection-brief.component.html
During a check-in, if the item is in a collection and at a temporary location, and if the item belongs to the current library, this information is added to the message intended for the professional.
* Closes rero/rero-ils#1321.
- https://github.com/rero/rero-ils/pull/3640
=> feat(circulation): add informations message

projects/admin/src/app/api/patron-transaction-api.service.ts, projects/admin/src/app/app.module.ts, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.ts, projects/admin/src/app/record/brief-view/patron-transaction-events-brief-view/patron-transaction-event-overdue.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-detail-view.component.ts, projects/admin/src/app/record/detail-view/item-detail-view/item-fees/item-fees.component.html, projects/admin/src/app/record/detail-view/item-detail-view/item-fees/item-fees.component.ts
* Adds fees on item detail view.
* Changes patron link on fees brief view to redirect to the patron circulation fees tab.
* Closes rero/rero-ils#3578.
=> feat(item): add fees on item detail view

projects/admin/src/app/classes/notification.ts, projects/admin/src/app/record/circulation-logs/circulation-log/circulation-log-loan/circulation-log-loan.component.html, projects/admin/src/app/record/custom-editor/libraries/library-form.service.ts, projects/admin/src/manual_translations.ts
* Depends on https://github.com/rero/rero-ils/pull/3691.
* Adds the info for auto_extends in the circulation log.
* Adds new notification type so that it can be displayed in the
library editor.
* Fixes the notification type `claim_issue` being wrongly displayed in
the library editor.
=> feat(circulation): automatic renewals

projects/admin/src/app/record/detail-view/circ-policy-detail-view/circ-policy-detail-view.component.html
* Adds a line to display the state of the `automatic_renewal` setting in the circulation policy detailed view.
=> fix(detailed cipo): display automatic renewal

projects/admin/src/app/record/detail-view/entities-detail-view/remote/entities-remote-detail-view.component.html, projects/admin/src/app/record/detail-view/entities-detail-view/remote/entities-remote-detail-view.component.ts, projects/admin/src/app/record/detail-view/entities-detail-view/remote/remote-organisation-detail-view/remote-entities-organisation-detail-view.component.html, projects/admin/src/app/record/detail-view/entities-detail-view/remote/remote-person-detail-view/remote-entities-person-detail-view.component.html, projects/admin/src/app/record/detail-view/entities-detail-view/remote/remote-topic-detail-view/remote-topic-detail-view.component.html, projects/admin/src/app/scss/styles.scss, projects/shared/src/lib/view/entity-link.component.ts
* Adds identifiedBy uri on all ressources.
* Translates subject to language change.
=> refactor(entity): add identifiedBy on all ressources

projects/admin/src/app/migration/deduplication/record/brief-view/migration-data-deduplication/migration-data-deduplication.component.html, projects/admin/src/app/migration/deduplication/record/brief-view/migration-data-deduplication/migration-data-deduplication.component.ts, projects/admin/src/app/migration/migration.module.ts
* Adds a "reject" button to speed up the user action.
* Fixes the ILS Pid focus.
* Do not display the first candidate for a "no match" deduplication status.
=> migration: add reject action

package-lock.json, projects/admin/src/app/circulation/items-list/items-list.component.html, projects/admin/src/app/circulation/main-request/requested-items-list/requested-items-list.component.html, projects/admin/src/app/circulation/patron/loan/loan.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transaction/patron-transaction.component.html, projects/admin/src/app/circulation/patron/patron-transactions/patron-transactions.component.html, projects/admin/src/app/circulation/patron/pickup/pickup.component.html, projects/admin/src/app/record/custom-editor/libraries/exception-dates-edit/exception-dates-edit.component.html, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.html, projects/admin/src/app/record/custom-editor/user-id-editor/user-id-editor.component.ts, projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.html, projects/admin/src/app/record/detail-view/document-detail-view/item-request/item-request.component.ts, projects/admin/src/app/record/detail-view/entities-detail-view/local/local-topic-detail-view/local-topic-detail-view.component.html, projects/admin/src/app/record/detail-view/item-type-detail-view/item-type-detail-view.component.html, projects/admin/src/app/record/editor/wrappers/user-id.component.ts, projects/search-bar/src/index.html
* Fixes display of calendar in library exception dates.
* Improves display of the item type detail view.
* Fixes modal title of the user editor.
* Fixes user form not saved.
* Fixes request on item.
* Updates dependencies.
* Closes rero/rero-ils#3825.
=> chore: improvements and fixes

projects/admin/src/app/routes/circulation-policies-route.ts, projects/admin/src/manual_translations.ts
* Fixes wrap of "/ day" cipo editor addon because of brekable space.
=> fix(cipo): editor addon wrap display

projects/admin/src/app/app.component.html
* Removes the useless footer in the admin app so that it does not conflict with other elements (e.g.: the table of contents in editors), and replace the bottom padding with a small margin.
=> fix(pro ui): remove footer

projects/public-holdings-items/src/index.html, projects/public-search/src/app/document-detail/document-detail-view/document-detail-view.component.html
Linked to https://github.com/rero/rero-ils/pull/3871.
=> fix(babeltheque): display "more info" after loading the ng app

projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-form.ts, projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-view.component.html, projects/admin/src/app/acquisition/components/receipt/receipt-form/order-receipt-view.component.ts, projects/admin/src/app/acquisition/components/receipt/receipt-list/receipt-list.component.ts, projects/admin/src/app/acquisition/components/receipt/receipt-summary/receipt-summary.component.html, projects/admin/src/app/acquisition/components/receipt/receipt-summary/receipt-summary.component.ts, projects/admin/src/app/acquisition/formly/type/repeat-section.type.ts, projects/admin/src/app/acquisition/routes/guards/can-order-receipt.guard.spec.ts, projects/admin/src/app/acquisition/routes/guards/can-order-receipt.guard.ts, projects/admin/src/app/acquisition/utils/permissions.ts
An acquisition receipt should be editable as long as it is in the active budget.
=> feat(acquistions): add receipt editor

projects/admin/src/app/record/editor/type/repeat-section.type.ts, projects/admin/src/app/record/search-view/document-advanced-search-form/document-advanced-search-form.component.ts
* Fixes the disabled type if only one value on select.
* Removes the clear action on select if value is required.
Deps: https://github.com/rero/ng-core/pull/721
=> fix: advanced search type disabled if only one type

projects/admin/src/app/record/detail-view/document-detail-view/holding/holding-item-temporary-item-type/holding-item-temporary-item-type.component.ts
The term temporary circulation category is misleading and not used anymore: replaced by "temporary item type".
=> fix: rename temporary circulation category

projects/admin/src/app/record/detail-view/item-detail-view/item-transactions/item-transactions.component.html
Deleting a request from an item detailed view displays the wrong pickup location for the next requests
* Closes rero/rero-ils#3889.
=> fix(item): request list pickup location

projects/shared/src/lib/component/remote-search/remote-search.component.ts
The document search from the top bar should be filtered by my organisation by default, unless it has been manuallly disabled.
* Closes rero/rero-ils#3887.
=> fix: global document search not filtered

projects/admin/src/app/circulation/patron/card/card.component.html, projects/admin/src/app/circulation/patron/service/circulation-stats.service.ts
When checkout an item, if the patron has messages, these are duplicated.
* Adjusts messages display.
* Closes rero/rero-ils#3902.
=> fix(circulation): patron message

projects/admin/src/app/record/detail-view/document-detail-view/files-collections/upload-files/upload-files.component.ts, projects/admin/src/app/service/resources-files.service.ts
* Adapts files upload service to new structure of `invenio_record_files`. `Label` is now in `metadata`.
* Closes https://github.com/rero/rero-ils/issues/3936.
=> fix(files): upload, label change
